// Governance > Meetings (T-DG4-FE-D; p4-work-split §D.5; ADR-0032 §2-§3). SYNTHETIC data only.
// The meetings of the transformation's forums (generated by a series or created ad hoc), with status, chair, quorum
// state and the agenda cut-off date — Unknown with its reason when no working-day calendar exists, never guessed.
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router";
import { MEETING_STATUSES } from "@mth/shared/schemas";
import { useP4Refresh } from "../../api/p4.ts";
import { useLocale } from "../../app/locale.ts";
import { Icon } from "../../components/Icon.tsx";
import { PersonName, usePeople } from "../../components/People.tsx";
import { RegisterTable } from "../../components/RegisterTable.tsx";
import { Section } from "../../components/Section.tsx";
import { QueryState } from "../../components/States.tsx";
import { useWorkspace, WorkspaceFrame } from "../../components/Workspace.tsx";
import { formatBusinessDate } from "../../lib/format.ts";
import { useForumName } from "../forums/ForumsPage.tsx";
import { DueDate, P4FormDialog, textOf } from "../my-work/p4ui.tsx";
import { govPaths, useForums, useMeetings } from "./api.ts";
import { GovSubNav, MEETING_WRITE_PERMISSIONS, MeetingStatusText, NS, QuorumState } from "./ui.tsx";

export function MeetingsPage() {
  const { t } = useTranslation();
  return (
    <WorkspaceFrame
      tab="meetings"
      title={t("governanceP4.meetings.title")}
      subtitle={t("governanceP4.meetings.intro")}
      writePermissions={MEETING_WRITE_PERMISSIONS}
    >
      <MeetingsBody />
    </WorkspaceFrame>
  );
}

function MeetingsBody() {
  const { t } = useTranslation();
  const locale = useLocale();
  const ws = useWorkspace();
  const forums = useForums(ws.tid);
  const name = useForumName();
  const [forumId, setForumId] = useState("");
  const [status, setStatus] = useState("");
  const meetings = useMeetings(ws.tid, { ...(forumId ? { forumId } : {}), ...(status ? { status } : {}) });
  const { byId } = usePeople(ws.tid);
  const refresh = useP4Refresh(ws.tid);
  const [creating, setCreating] = useState(false);
  const forumById = new Map((forums.data ?? []).map((f) => [f.id, f]));
  return (
    <>
      <GovSubNav tid={ws.tid} />
      <Section
        id="meetings"
        title={t("governanceP4.meetings.tableTitle")}
        actions={
          ws.can("meeting.prepare") ? (
            <button type="button" className="button button--primary" onClick={() => setCreating(true)}>
              <Icon name="plus" /> {t("governanceP4.meetings.create")}
            </button>
          ) : null
        }
      >
        <div className="filters" role="group" aria-label={t("governanceP4.filters")}>
          <div className="filters__select">
            <label htmlFor="meeting-filter-forum">{t("governanceP4.meetings.forum")}</label>
            <select id="meeting-filter-forum" value={forumId} onChange={(e) => setForumId(e.target.value)}>
              <option value="">{t("governanceP4.all")}</option>
              {(forums.data ?? []).map((f) => (
                <option key={f.id} value={f.id}>
                  {name(f)}
                </option>
              ))}
            </select>
          </div>
          <div className="filters__select">
            <label htmlFor="meeting-filter-status">{t("governanceP4.meetings.status")}</label>
            <select id="meeting-filter-status" value={status} onChange={(e) => setStatus(e.target.value)}>
              <option value="">{t("governanceP4.all")}</option>
              {MEETING_STATUSES.map((s) => (
                <option key={s} value={s}>
                  {t(`governanceP4.meetingStatus.${s}`)}
                </option>
              ))}
            </select>
          </div>
        </div>
        <QueryState query={meetings}>
          {(rows) => (
            <RegisterTable
              id="meetings"
              caption={t("governanceP4.meetings.tableTitle")}
              rows={rows}
              getRowId={(m) => m.id}
              emptyTitle={t("governanceP4.meetings.empty")}
              emptyBody={t("governanceP4.meetings.emptyBody")}
              defaultSort={{ id: "date", dir: "asc" }}
              columns={[
                {
                  id: "date",
                  header: t("governanceP4.meetings.date"),
                  rowHeader: true,
                  hideable: false,
                  cell: (m) => (
                    <Link className="link" to={`/transformations/${ws.tid}/meetings/${m.id}`} data-meeting={m.id}>
                      {formatBusinessDate(m.scheduledDate, locale)}
                    </Link>
                  ),
                  sortValue: (m) => m.startsAt,
                },
                {
                  id: "forum",
                  header: t("governanceP4.meetings.forum"),
                  cell: (m) => name(forumById.get(m.forumId)),
                  sortValue: (m) => name(forumById.get(m.forumId)),
                },
                {
                  id: "status",
                  header: t("governanceP4.meetings.status"),
                  cell: (m) => <MeetingStatusText status={m.status} />,
                  sortValue: (m) => MEETING_STATUSES.indexOf(m.status),
                  filterText: (m) => t(`governanceP4.meetingStatus.${m.status}`),
                },
                {
                  id: "chair",
                  header: t("governanceP4.meetings.chair"),
                  cell: (m) =>
                    m.chairUserId ? (
                      <PersonName id={m.chairUserId} people={byId} />
                    ) : (
                      <span className="status-chip status-chip--unknown" data-chair="unassigned">
                        <Icon name="question" /> {t("governanceP4.meetings.noChair")}
                      </span>
                    ),
                },
                {
                  id: "quorum",
                  header: t("governanceP4.meetings.quorum"),
                  cell: (m) => <QuorumState state={m.quorumState} present={m.presentCount} required={m.quorumMin} />,
                },
                {
                  id: "cutoff",
                  header: t("governanceP4.meetings.cutoff"),
                  cell: (m) => <DueDate date={m.cutoffDate} reason={m.cutoffUnknownReason} />,
                  sortValue: (m) => m.cutoffDate,
                },
              ]}
            />
          )}
        </QueryState>
      </Section>
      {creating ? (
        <P4FormDialog
          title={t("governanceP4.meetings.create")}
          fields={[
            {
              name: "forumId",
              label: t("governanceP4.meetings.forum"),
              kind: "select",
              required: true,
              options: (forums.data ?? [])
                .filter((f) => f.status === "active")
                .map((f) => ({ value: f.id, label: name(f) })),
            },
            { name: "scheduledDate", label: t("governanceP4.meetings.date"), kind: "date", required: true },
            {
              name: "startTime",
              label: t("governanceP4.series.startTime"),
              kind: "text",
              required: true,
              ltr: true,
              hint: "HH:MM",
            },
            {
              name: "durationMinutes",
              label: t("governanceP4.series.duration"),
              kind: "number",
              required: true,
              min: 15,
              max: 480,
            },
            { name: "location", label: t("governanceP4.series.location"), kind: "text", max: 300 },
          ]}
          initial={{ startTime: "09:00", durationMinutes: "60" }}
          submitLabel={t("governanceP4.meetings.createSubmit")}
          url={govPaths.meetings(ws.tid)}
          namespaces={NS}
          toBody={(v) => ({
            forumId: v["forumId"],
            scheduledDate: v["scheduledDate"],
            startTime: v["startTime"],
            durationMinutes: Number(v["durationMinutes"]),
            ...(textOf(v["location"]) ? { location: v["location"] } : {}),
          })}
          onDone={refresh}
          onClose={() => setCreating(false)}
        />
      ) : null}
    </>
  );
}
