import json, collections, sys
EN = collections.OrderedDict([
# ADR-0031 §11
("raid.type_invalid","Type must be Risk, Assumption, Issue or Dependency."),
("raid.probability_required","A Risk needs a Probability (High, Medium or Low)."),
("raid.probability_not_applicable","Probability is n/a for Assumption, Issue and Dependency entries; leave it empty."),
("raid.status_transition","A RAID entry moves between Open and In progress; use Close to close it."),
("raid.closed","This RAID entry is closed and can no longer be changed."),
("corrective_case.status_transition","A corrective action moves between Open and In progress; use Close to close it."),
("corrective_case.closed","This corrective action is closed and can no longer be changed."),
("corrective_case.owner_required","Assign an owner before closing this corrective action."),
("corrective_case.follow_up_past","The follow-up date cannot be before today."),
("corrective_case.already_open","An open corrective action already exists for this finding."),
("corrective_rule.severity_kpi_only","A severity applies to KPI deviations only, and a KPI deviation rule needs one."),
("corrective_rule.persistence_series_only","A failed check is one event: its persistence is 1 cycle."),
("corrective_rule.exists","A rule for this source already exists in this transformation; update it instead."),
("budget_line.amount_invalid","Amounts must be zero or more, with at most 16 digits before and 4 after the decimal point."),
("budget_line.period_invalid","The month must be given as its first day (YYYY-MM-01)."),
("budget_line.archived","This budget line is archived and can no longer be changed."),
("budget_line.duplicate","An active budget line with this label and month already exists for the initiative."),
("initiative_schedule.exists","This initiative already has a planned duration; update it instead."),
# ADR-0031 A2
("validation.not_applicable","This field does not apply here."),
# ADR-0032 §11
("executive_decision.field_required","This element of the executive ask is required."),
("executive_decision.options_too_few","An executive ask states at least two options."),
("executive_decision.owner_not_executive","The decision owner must be an executive who holds the decision right in this transformation."),
("executive_decision.required_date_past","The required date cannot be before today."),
("executive_decision.option_unknown","This option is not one of the decision's options."),
("executive_decision.closed","This executive decision is no longer open and can no longer be changed."),
("executive_decision.defer_date_required","A deferral needs a new date after today."),
("executive_decision.not_owner","Only the decision owner, or an active delegate acting for them, can record the outcome."),
("executive_decision.blocker_ask_open","An open executive ask already exists for this blocker."),
("agenda_item.executive_ask_incomplete","An executive agenda item must state the decision required, why now, options, recommendation, impact of delay, decision owner and required date before it is published."),
("agenda_item.executive_asks_only","Escalate decisions, not status: this forum's agenda takes executive asks only."),
("agenda_item.after_cutoff","The agenda cut-off for this meeting has passed, and this forum does not accept late items."),
("agenda_item.max_items","This forum's agenda has reached its maximum number of items."),
("agenda_item.not_draft","Only a draft agenda item can be changed."),
("agenda_item.final","This agenda item is closed or withdrawn and can no longer be changed."),
("agenda_item.decision_not_linkable","Only an open executive ask of this transformation can be linked."),
("meeting.quorum_not_met","This meeting has not reached its quorum. Decisions cannot be recorded below quorum."),
("meeting.not_in_session","Decisions and blocker status are recorded while the meeting is in session or held."),
("meeting.status_transition","This meeting cannot move to that status from its current one."),
("meeting.final","This meeting is closed or cancelled and can no longer be changed."),
("meeting.agenda_empty","The agenda has no published item."),
("meeting.agenda_has_drafts","Publish or withdraw every draft agenda item before publishing the agenda."),
("meeting.chair_unassigned","This meeting has no chair. Map the forum's chair role or name a chair first."),
("meeting.not_chair","Only the meeting's chair can do this."),
("meeting.frozen","This meeting's records can no longer be changed."),
("meeting_attendance.exists","Attendance for this person is already recorded; update it instead."),
("meeting_minutes.exists","This meeting already has minutes; update them instead."),
("meeting_minutes.status_transition","These minutes cannot move to that status from their current one."),
("meeting_minutes.published","Published minutes are immutable."),
("meeting_minutes.approved_frozen","Approved minutes are edited only after they are returned to draft."),
("meeting_minutes.meeting_not_held","Minutes are published after the meeting is held."),
("meeting_minutes.required_output_missing","This forum's minutes cannot be published without at least one of its required outputs."),
("meeting_output.kind_not_in_forum","This is not an output of this forum."),
("meeting_output.record_required","This output links a record of a specific type."),
("meeting_output.record_not_found","The linked record does not exist in this transformation."),
("forum.party_unknown","This is not a known governance role."),
("forum.output_kind_invalid","Outputs are chosen from: decisions, unblockers, benefit view, integrated status, decision log, milestones, actions, RAID, test, evidence, recommendation, benefit evidence, forecast, corrective action."),
("forum.publish_output_not_listed","A required publication output must be one of this forum's outputs."),
("forum.archived","This forum is archived and can no longer be changed."),
("forum_participant.exists","This person or group is already a participant of the forum."),
("forum_participant.removed","This participant was removed and can no longer be changed."),
("meeting_series.rule_invalid","A weekly series needs its weekdays, a monthly series a day of the month (1–28), and a daily series neither."),
("meeting_series.exists","This forum already has an active meeting series; change it instead."),
("meeting_series.ended","This meeting series has ended and can no longer be changed."),
("blocker_status.exists","A RAG for this blocker is already recorded in this meeting."),
("blocker_status.record_not_found","The blocker does not exist in this transformation."),
("escalation_rule.exists","A rule of this kind already exists in this transformation; update it instead."),
("escalation_rule.shape","A decision-SLA rule takes an escalation chain only; a blocker rule takes red cycles (2–12), a deadline in working days and an owner role."),
# ADR-0032 A2
("meeting.quorum_locked","The quorum is set before the session starts; it can no longer be changed for this meeting."),
("validation.user_unknown","Choose an active user of this transformation's organization."),
("validation.group_unknown","Choose an active group of this transformation's organization."),
("validation.forum_unknown","Choose a forum of this transformation."),
("validation.end_before_start","The end date cannot be before the start date."),
("validation.decision_right_unknown","Choose an active decision-rights row of this transformation."),
("validation.blocker_pair","A blocker link names both its record type and its record."),
("validation.empty_patch","Change at least one field."),
("validation.local_time","Enter a time as HH:MM (24-hour clock)."),
("validation.option_label","An option label is one capital letter, A to Z."),
# codes emitted by BE-F2/BE-G outside the ADR tables
("agenda_item.not_published","Only a published agenda item can take an outcome."),
("agenda_item.ordinal_taken","Another agenda item of this meeting has this position."),
("agenda_item.outcome_not_ask","Only an executive ask records a decision; record this item as noted or deferred."),
("validation.agenda_ask_shape","Only an executive ask links a decision or carries a brief, and never both."),
("validation.evidence_unknown","Choose evidence of this transformation."),
("validation.agenda_item_unknown","Choose an agenda item of this meeting."),
("validation.attendance_proxy","A representative is recorded only for a present person, and never for themselves."),
("validation.record_pair","A linked record names both its record type and its record."),
])
AR = {
"raid.type_invalid":"يجب أن يكون النوع خطرًا أو افتراضًا أو مشكلة أو اعتمادية.",
"raid.probability_required":"يحتاج الخطر إلى احتمالية (مرتفعة أو متوسطة أو منخفضة).",
"raid.probability_not_applicable":"الاحتمالية لا تنطبق على الافتراضات والمشكلات والاعتماديات؛ اتركها فارغة.",
"raid.status_transition":"ينتقل قيد السجل بين 'مفتوح' و'قيد التنفيذ'؛ استخدم 'إغلاق' لإغلاقه.",
"raid.closed":"هذا القيد مغلق ولا يمكن تغييره بعد الآن.",
"corrective_case.status_transition":"ينتقل الإجراء التصحيحي بين 'مفتوح' و'قيد التنفيذ'؛ استخدم 'إغلاق' لإغلاقه.",
"corrective_case.closed":"هذا الإجراء التصحيحي مغلق ولا يمكن تغييره بعد الآن.",
"corrective_case.owner_required":"عيّن مالكًا قبل إغلاق هذا الإجراء التصحيحي.",
"corrective_case.follow_up_past":"لا يمكن أن يكون تاريخ المتابعة قبل اليوم.",
"corrective_case.already_open":"يوجد إجراء تصحيحي مفتوح لهذه الملاحظة بالفعل.",
"corrective_rule.severity_kpi_only":"تنطبق الشدة على انحرافات مؤشرات الأداء فقط، وتحتاج قاعدة انحراف المؤشر إليها.",
"corrective_rule.persistence_series_only":"الفحص الفاشل حدث واحد: استمراره دورة واحدة.",
"corrective_rule.exists":"توجد قاعدة لهذا المصدر في هذا التحوّل؛ حدّثها بدلًا من ذلك.",
"budget_line.amount_invalid":"يجب أن تكون المبالغ صفرًا أو أكثر، بحد أقصى 16 رقمًا قبل الفاصلة العشرية و4 بعدها.",
"budget_line.period_invalid":"يجب إدخال الشهر بيومه الأول (YYYY-MM-01).",
"budget_line.archived":"بند الميزانية هذا مؤرشف ولا يمكن تغييره بعد الآن.",
"budget_line.duplicate":"يوجد بند ميزانية نشط بهذا الوصف والشهر لهذه المبادرة.",
"initiative_schedule.exists":"لهذه المبادرة مدة مخططة بالفعل؛ حدّثها بدلًا من ذلك.",
"validation.not_applicable":"هذا الحقل لا ينطبق هنا.",
"executive_decision.field_required":"هذا العنصر من طلب القرار التنفيذي مطلوب.",
"executive_decision.options_too_few":"يذكر طلب القرار التنفيذي خيارين على الأقل.",
"executive_decision.owner_not_executive":"يجب أن يكون مالك القرار تنفيذيًا يملك صلاحية القرار في هذا التحوّل.",
"executive_decision.required_date_past":"لا يمكن أن يكون التاريخ المطلوب قبل اليوم.",
"executive_decision.option_unknown":"هذا الخيار ليس من خيارات القرار.",
"executive_decision.closed":"هذا القرار التنفيذي لم يعد مفتوحًا ولا يمكن تغييره بعد الآن.",
"executive_decision.defer_date_required":"يحتاج التأجيل إلى تاريخ جديد بعد اليوم.",
"executive_decision.not_owner":"لا يسجّل النتيجة إلا مالك القرار أو مفوَّضه النشط الذي يتصرف نيابة عنه.",
"executive_decision.blocker_ask_open":"يوجد طلب قرار تنفيذي مفتوح لهذا العائق بالفعل.",
"agenda_item.executive_ask_incomplete":"يجب أن يذكر بند جدول الأعمال التنفيذي القرار المطلوب، ولماذا الآن، والخيارات، والتوصية، وأثر التأخير، ومالك القرار، والتاريخ المطلوب قبل نشره.",
"agenda_item.executive_asks_only":"صعّد القرارات لا الحالة: جدول أعمال هذا المنتدى يقبل طلبات القرار التنفيذية فقط.",
"agenda_item.after_cutoff":"انقضى الموعد النهائي لجدول أعمال هذا الاجتماع، وهذا المنتدى لا يقبل البنود المتأخرة.",
"agenda_item.max_items":"بلغ جدول أعمال هذا المنتدى الحد الأقصى لعدد البنود.",
"agenda_item.not_draft":"لا يمكن تغيير إلا بند جدول أعمال في حالة المسودة.",
"agenda_item.final":"هذا البند مغلق أو مسحوب ولا يمكن تغييره بعد الآن.",
"agenda_item.decision_not_linkable":"لا يمكن ربط إلا طلب قرار تنفيذي مفتوح في هذا التحوّل.",
"meeting.quorum_not_met":"لم يكتمل نصاب هذا الاجتماع. لا يمكن تسجيل القرارات دون اكتمال النصاب.",
"meeting.not_in_session":"تُسجَّل القرارات وحالة العوائق أثناء انعقاد الاجتماع أو بعد عقده.",
"meeting.status_transition":"لا يمكن نقل هذا الاجتماع إلى تلك الحالة من حالته الحالية.",
"meeting.final":"هذا الاجتماع منتهٍ أو ملغى ولا يمكن تغييره بعد الآن.",
"meeting.agenda_empty":"لا يحتوي جدول الأعمال على بند منشور.",
"meeting.agenda_has_drafts":"انشر كل بند مسودة أو اسحبه قبل نشر جدول الأعمال.",
"meeting.chair_unassigned":"لا يوجد رئيس لهذا الاجتماع. اربط دور رئيس المنتدى أو سمِّ رئيسًا أولًا.",
"meeting.not_chair":"لا يقوم بهذا إلا رئيس الاجتماع.",
"meeting.frozen":"لا يمكن تغيير سجلات هذا الاجتماع بعد الآن.",
"meeting_attendance.exists":"حضور هذا الشخص مسجّل بالفعل؛ حدّثه بدلًا من ذلك.",
"meeting_minutes.exists":"لهذا الاجتماع محضر بالفعل؛ حدّثه بدلًا من ذلك.",
"meeting_minutes.status_transition":"لا يمكن نقل هذا المحضر إلى تلك الحالة من حالته الحالية.",
"meeting_minutes.published":"المحضر المنشور غير قابل للتغيير.",
"meeting_minutes.approved_frozen":"لا يُعدَّل المحضر المعتمد إلا بعد إرجاعه إلى مسودة.",
"meeting_minutes.meeting_not_held":"يُنشر المحضر بعد عقد الاجتماع.",
"meeting_minutes.required_output_missing":"لا يمكن نشر محضر هذا المنتدى دون واحد على الأقل من مخرجاته المطلوبة.",
"meeting_output.kind_not_in_forum":"هذا ليس من مخرجات هذا المنتدى.",
"meeting_output.record_required":"يرتبط هذا المخرج بسجل من نوع محدد.",
"meeting_output.record_not_found":"السجل المرتبط غير موجود في هذا التحوّل.",
"forum.party_unknown":"هذا ليس دور حوكمة معروفًا.",
"forum.output_kind_invalid":"تُختار المخرجات من: القرارات، وإزالة العوائق، وعرض المنافع، والحالة المتكاملة، وسجل القرارات، والمعالم، والإجراءات، وسجل المخاطر، والاختبار، والأدلة، والتوصية، وأدلة المنافع، والتوقعات، والإجراء التصحيحي.",
"forum.publish_output_not_listed":"يجب أن يكون مخرج النشر المطلوب من مخرجات هذا المنتدى.",
"forum.archived":"هذا المنتدى مؤرشف ولا يمكن تغييره بعد الآن.",
"forum_participant.exists":"هذا الشخص أو المجموعة مشارك في المنتدى بالفعل.",
"forum_participant.removed":"أُزيل هذا المشارك ولا يمكن تغييره بعد الآن.",
"meeting_series.rule_invalid":"تحتاج السلسلة الأسبوعية إلى أيام الأسبوع، والشهرية إلى يوم من الشهر (1–28)، واليومية إلى لا شيء منهما.",
"meeting_series.exists":"لهذا المنتدى سلسلة اجتماعات نشطة بالفعل؛ غيّرها بدلًا من ذلك.",
"meeting_series.ended":"انتهت سلسلة الاجتماعات هذه ولا يمكن تغييرها بعد الآن.",
"blocker_status.exists":"حالة هذا العائق مسجلة بالفعل في هذا الاجتماع.",
"blocker_status.record_not_found":"العائق غير موجود في هذا التحوّل.",
"escalation_rule.exists":"توجد قاعدة من هذا النوع في هذا التحوّل؛ حدّثها بدلًا من ذلك.",
"escalation_rule.shape":"تأخذ قاعدة اتفاقية مستوى خدمة القرار سلسلة تصعيد فقط؛ وتأخذ قاعدة العائق عدد دورات الأحمر (2–12) ومهلة بأيام العمل ودور المالك.",
"meeting.quorum_locked":"يُحدَّد النصاب قبل بدء الجلسة؛ ولم يعد ممكنًا تغييره لهذا الاجتماع.",
"validation.user_unknown":"اختر مستخدمًا نشطًا من جهة هذا التحوّل.",
"validation.group_unknown":"اختر مجموعة نشطة من جهة هذا التحوّل.",
"validation.forum_unknown":"اختر منتدى من هذا التحوّل.",
"validation.end_before_start":"لا يمكن أن يكون تاريخ الانتهاء قبل تاريخ البدء.",
"validation.decision_right_unknown":"اختر صفًا نشطًا من مصفوفة صلاحيات القرار في هذا التحوّل.",
"validation.blocker_pair":"يذكر رابط العائق نوع السجل والسجل معًا.",
"validation.empty_patch":"غيّر حقلًا واحدًا على الأقل.",
"validation.local_time":"أدخل الوقت بصيغة HH:MM (نظام 24 ساعة).",
"validation.option_label":"رمز الخيار حرف لاتيني كبير واحد من A إلى Z.",
"agenda_item.not_published":"لا يأخذ نتيجة إلا بند جدول أعمال منشور.",
"agenda_item.ordinal_taken":"لبند آخر في هذا الاجتماع هذا الترتيب.",
"agenda_item.outcome_not_ask":"لا يسجّل قرارًا إلا طلب القرار التنفيذي؛ سجّل هذا البند 'أُخذ علمًا' أو 'مؤجل'.",
"validation.agenda_ask_shape":"لا يربط قرارًا أو يحمل ملخصًا إلا طلب القرار التنفيذي، ولا يجمع بينهما.",
"validation.evidence_unknown":"اختر دليلًا من هذا التحوّل.",
"validation.agenda_item_unknown":"اختر بندًا من جدول أعمال هذا الاجتماع.",
"validation.attendance_proxy":"يُسجَّل الممثل لشخص حاضر فقط، ولا يكون الشخص ممثلًا عن نفسه.",
"validation.record_pair":"يذكر السجل المرتبط نوع السجل والسجل معًا.",
}
assert set(AR)==set(EN), set(EN)^set(AR)
added=[]; present=[]
for lang, texts in (("en", EN), ("ar", AR)):
    p=f"/home/user/wt/dg4-fe-d/apps/web/src/i18n/{lang}/problems.json"
    d=json.load(open(p), object_pairs_hook=collections.OrderedDict)
    for code in EN:
        k=code.replace(".","__")
        if k in d:
            if lang=="en": present.append(code)
            continue
        d[k]=texts[code]
        if lang=="en": added.append(code)
    open(p,"w").write(json.dumps(d,ensure_ascii=False,indent=2)+"\n")
print("total", len(EN), "added", len(added), "already present", present)
json.dump({"codes":list(EN), "added":added, "present":present}, open(sys.argv[1],"w"), indent=1)
