#!/usr/bin/env node
// =====================================================================================================================
// DRILL FIXTURE — NOT FOR ANY OTHER USE. Local stand-ins for the enterprise services a production installation needs
// (used only by scripts/ops/fresh-install-drill.sh, inside a network namespace that has nothing but loopback):
//
//   idp      HTTPS OpenID Provider: discovery, JWKS, authorization (auto-consents as the user the drill selected),
//            token endpoint with client authentication and PKCE S256, RS256 ID token with nonce, email_verified and the
//            optional MFA claims (amr / acr). It stands in for Mobily's IdP; the API runs its real openid-client path.
//   s3       HTTPS S3-compatible object store: path-style PUT / GET / HEAD / DELETE on one bucket, every SigV4
//            signature re-computed from the request as received (the app's own signer), objects persisted under
//            <dir>/<key> so that backup.sh / restore.sh copy the bucket like `mc mirror` would.
//   ingress  HTTPS reverse proxy like the Helm ingress: /api/* → API service, everything else → web service; it
//            OVERWRITES X-Forwarded-For (HUB_TRUST_PROXY=1) and sets X-Forwarded-Proto/Host.
//
// Certificates come from a throwaway CA generated by the drill at run time (custom CA, REQ-DEP-009); the API trusts it
// through NODE_EXTRA_CA_CERTS only — TLS verification is never disabled.
//
//   node stand-ins.mjs <config.json>     config: { tls: {key, cert}, idp: {port, clientId, clientSecret},
//                                                 s3: {port, dir, bucket, accessKeyId, secretAccessKey, region},
//                                                 ingress: {port, api, web}, readyFile }
// =====================================================================================================================
import { createHash, generateKeyPairSync, randomBytes, sign } from 'node:crypto';
import { createServer as createHttpsServer } from 'node:https';
import { request as httpRequest } from 'node:http';
import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, writeFileSync, existsSync, renameSync, rmSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../../..');
const cfg = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const tls = { key: readFileSync(cfg.tls.key), cert: readFileSync(cfg.tls.cert) };
const require = createRequire(import.meta.url);
// The app's own SigV4 signer (compiled API), so the stand-in verifies exactly what the adapter signs.
const { signV4, sha256Hex } = require(join(ROOT, 'apps/api/dist/modules/documents/storage/sigv4.js'));
const log = (m) => process.stdout.write(`[stand-ins] ${m}\n`);

const readBody = async (req) => {
  const chunks = [];
  for await (const c of req) chunks.push(c);
  return Buffer.concat(chunks);
};
const json = (res, status, body) => {
  res.writeHead(status, { 'content-type': 'application/json', 'cache-control': 'no-store' });
  res.end(JSON.stringify(body));
};

// ---------------------------------------------------------------------------------------------------------------- IdP
function startIdp() {
  const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });
  const kid = randomBytes(6).toString('hex');
  const jwk = { ...publicKey.export({ format: 'jwk' }), kid, alg: 'RS256', use: 'sig' };
  const issuer = `https://127.0.0.1:${cfg.idp.port}`;
  const codes = new Map();
  let nextUser = null;
  const stats = { authorizations: 0, tokens: 0, rejected: 0 };
  const signJwt = (claims) => {
    const enc = (o) => Buffer.from(JSON.stringify(o)).toString('base64url');
    const input = `${enc({ alg: 'RS256', typ: 'JWT', kid })}.${enc(claims)}`;
    return `${input}.${sign('RSA-SHA256', Buffer.from(input), privateKey).toString('base64url')}`;
  };
  const server = createHttpsServer(tls, async (req, res) => {
    try {
      const url = new URL(req.url ?? '/', issuer);
      if (url.pathname === '/.well-known/openid-configuration') {
        return json(res, 200, {
          issuer,
          authorization_endpoint: `${issuer}/authorize`,
          token_endpoint: `${issuer}/token`,
          jwks_uri: `${issuer}/jwks`,
          response_types_supported: ['code'],
          subject_types_supported: ['public'],
          id_token_signing_alg_values_supported: ['RS256'],
          code_challenge_methods_supported: ['S256'],
          token_endpoint_auth_methods_supported: ['client_secret_basic', 'client_secret_post'],
          scopes_supported: ['openid', 'email', 'profile'],
          claims_supported: ['sub', 'email', 'email_verified', 'amr', 'acr'],
        });
      }
      if (url.pathname === '/jwks') return json(res, 200, { keys: [jwk] });
      // Drill control (loopback only, this fixture only): which identity the next authorization signs in as.
      if (url.pathname === '/__drill/next-user' && req.method === 'POST') {
        nextUser = JSON.parse((await readBody(req)).toString() || 'null');
        return json(res, 200, { ok: true });
      }
      if (url.pathname === '/__drill/stats') return json(res, 200, stats);
      if (url.pathname === '/authorize') {
        const q = url.searchParams;
        if (q.get('client_id') !== cfg.idp.clientId || q.get('response_type') !== 'code' || q.get('code_challenge_method') !== 'S256' || !q.get('code_challenge')) {
          return json(res, 400, { error: 'invalid_request' });
        }
        if (!nextUser) return json(res, 400, { error: 'no drill user selected' });
        const code = randomBytes(16).toString('base64url');
        codes.set(code, { redirectUri: q.get('redirect_uri'), challenge: q.get('code_challenge'), nonce: q.get('nonce') ?? '', user: nextUser, acrValues: q.get('acr_values') });
        stats.authorizations++;
        const back = new URL(q.get('redirect_uri'));
        back.searchParams.set('code', code);
        if (q.get('state')) back.searchParams.set('state', q.get('state'));
        res.writeHead(302, { location: back.href });
        return res.end();
      }
      if (url.pathname === '/token' && req.method === 'POST') {
        const form = new URLSearchParams((await readBody(req)).toString());
        let id = form.get('client_id');
        let secret = form.get('client_secret');
        const auth = req.headers.authorization;
        if (auth?.startsWith('Basic ')) {
          const [u, p] = Buffer.from(auth.slice(6), 'base64').toString().split(':');
          id = decodeURIComponent(u ?? '');
          secret = decodeURIComponent(p ?? '');
        }
        const entry = codes.get(form.get('code') ?? '');
        const challengeOk = entry && createHash('sha256').update(form.get('code_verifier') ?? '').digest('base64url') === entry.challenge;
        if (id !== cfg.idp.clientId || secret !== cfg.idp.clientSecret || form.get('grant_type') !== 'authorization_code' || !entry || entry.redirectUri !== form.get('redirect_uri') || !challengeOk) {
          stats.rejected++;
          return json(res, 400, { error: 'invalid_grant' });
        }
        codes.delete(form.get('code'));
        stats.tokens++;
        const now = Math.floor(Date.now() / 1000);
        const u = entry.user;
        const claims = { iss: issuer, sub: u.sub, aud: cfg.idp.clientId, iat: now, exp: now + 300, nonce: entry.nonce };
        if (u.email) Object.assign(claims, { email: u.email, email_verified: u.emailVerified ?? true });
        if (u.amr) claims.amr = u.amr;
        if (u.acr) claims.acr = u.acr;
        return json(res, 200, { access_token: randomBytes(16).toString('base64url'), token_type: 'Bearer', expires_in: 300, id_token: signJwt(claims) });
      }
      return json(res, 404, { error: 'not_found' });
    } catch (e) {
      return json(res, 500, { error: String(e?.message ?? e) });
    }
  });
  return new Promise((ok) => server.listen(cfg.idp.port, '127.0.0.1', () => ok({ server, issuer })));
}

// ----------------------------------------------------------------------------------------------------------------- S3
function startS3() {
  const base = resolve(cfg.s3.dir);
  mkdirSync(base, { recursive: true });
  const endpoint = `https://127.0.0.1:${cfg.s3.port}`;
  const stats = { put: 0, get: 0, head: 0, delete: 0, denied: 0, sse: {} };
  const xml = (res, status, code) => {
    res.writeHead(status, { 'content-type': 'application/xml' });
    res.end(`<?xml version="1.0"?><Error><Code>${code}</Code><Message>drill-s3</Message></Error>`);
  };
  const server = createHttpsServer(tls, async (req, res) => {
    try {
      const body = await readBody(req);
      const url = new URL(req.url ?? '/', endpoint);
      if (url.pathname === '/__drill/stats') return json(res, 200, stats);
      const auth = String(req.headers.authorization ?? '');
      const m = /^AWS4-HMAC-SHA256 Credential=([^/]+)\/(\d{8})\/([^/]+)\/s3\/aws4_request, SignedHeaders=([a-z0-9;-]+), Signature=([0-9a-f]{64})$/.exec(auth);
      if (!m || m[1] !== cfg.s3.accessKeyId) return stats.denied++, xml(res, 403, 'AccessDenied');
      const payloadHash = String(req.headers['x-amz-content-sha256'] ?? '');
      if (payloadHash !== sha256Hex(body)) return stats.denied++, xml(res, 400, 'XAmzContentSHA256Mismatch');
      const d = String(req.headers['x-amz-date'] ?? '');
      const now = new Date(`${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)}T${d.slice(9, 11)}:${d.slice(11, 13)}:${d.slice(13, 15)}Z`);
      if (Number.isNaN(now.getTime()) || Math.abs(Date.now() - now.getTime()) > 15 * 60_000) return stats.denied++, xml(res, 403, 'RequestTimeTooSkewed');
      const signed = m[4].split(';').filter((h) => !['host', 'x-amz-content-sha256', 'x-amz-date'].includes(h));
      const extra = Object.fromEntries(signed.map((h) => [h, String(req.headers[h] ?? '')]));
      const expected = signV4({ method: req.method, url: new URL(`https://${String(req.headers.host)}${url.pathname}`), headers: extra, payloadHash, accessKeyId: cfg.s3.accessKeyId, secretAccessKey: cfg.s3.secretAccessKey, region: m[3], now });
      if (expected.authorization !== auth) return stats.denied++, xml(res, 403, 'SignatureDoesNotMatch');
      const [, bucket, ...rest] = url.pathname.split('/');
      if (bucket !== cfg.s3.bucket) return xml(res, 404, 'NoSuchBucket');
      const key = rest.map(decodeURIComponent).join('/');
      const file = resolve(base, key);
      if (!key || !file.startsWith(base + sep)) return xml(res, 400, 'InvalidKey');
      switch (req.method) {
        case 'PUT': {
          mkdirSync(dirname(file), { recursive: true });
          writeFileSync(`${file}.part`, body);
          renameSync(`${file}.part`, file);
          stats.put++;
          const sse = String(req.headers['x-amz-server-side-encryption'] ?? 'none');
          stats.sse[sse] = (stats.sse[sse] ?? 0) + 1;
          res.writeHead(200, { etag: `"${sha256Hex(body).slice(0, 32)}"`, ...(sse !== 'none' ? { 'x-amz-server-side-encryption': sse } : {}) });
          return res.end();
        }
        case 'GET':
        case 'HEAD': {
          if (!existsSync(file)) return xml(res, 404, 'NoSuchKey');
          const data = readFileSync(file);
          stats[req.method === 'GET' ? 'get' : 'head']++;
          res.writeHead(200, { 'content-type': 'application/octet-stream', 'content-length': String(data.length) });
          return res.end(req.method === 'GET' ? data : undefined);
        }
        case 'DELETE':
          rmSync(file, { force: true });
          stats.delete++;
          res.writeHead(204);
          return res.end();
        default:
          return xml(res, 405, 'MethodNotAllowed');
      }
    } catch (e) {
      return json(res, 500, { error: String(e?.message ?? e) });
    }
  });
  return new Promise((ok) => server.listen(cfg.s3.port, '127.0.0.1', () => ok({ server, endpoint })));
}

// ------------------------------------------------------------------------------------------------------------ ingress
function startIngress() {
  const stats = { api: 0, web: 0, upstreamErrors: 0 };
  const server = createHttpsServer(tls, (req, res) => {
    if (req.url === '/__drill/ingress-stats') return json(res, 200, stats);
    const toApi = req.url === '/api' || req.url?.startsWith('/api/');
    const target = new URL(toApi ? cfg.ingress.api : cfg.ingress.web);
    stats[toApi ? 'api' : 'web']++;
    const headers = { ...req.headers };
    // Like the Helm ingress: the client address REPLACES any forwarded chain sent by the client (ADR-0017).
    headers['x-forwarded-for'] = req.socket.remoteAddress ?? '';
    headers['x-forwarded-proto'] = 'https';
    headers['x-forwarded-host'] = req.headers.host ?? '';
    for (const h of ['forwarded', 'x-real-ip']) delete headers[h];
    const up = httpRequest({ host: target.hostname, port: target.port, method: req.method, path: req.url, headers }, (ur) => {
      res.writeHead(ur.statusCode ?? 502, ur.headers);
      ur.pipe(res);
    });
    up.on('error', () => {
      stats.upstreamErrors++;
      if (!res.headersSent) res.writeHead(502, { 'content-type': 'text/plain' });
      res.end('bad gateway');
    });
    req.pipe(up);
  });
  return new Promise((ok) => server.listen(cfg.ingress.port, '127.0.0.1', () => ok({ server })));
}

const started = {};
if (cfg.idp) started.idp = (await startIdp()).issuer;
if (cfg.s3) started.s3 = (await startS3()).endpoint;
if (cfg.ingress) {
  await startIngress();
  started.ingress = `https://127.0.0.1:${cfg.ingress.port}`;
}
log(`ready ${JSON.stringify(started)}`);
if (cfg.readyFile) writeFileSync(cfg.readyFile, JSON.stringify(started));
const stop = () => process.exit(0);
process.on('SIGTERM', stop);
process.on('SIGINT', stop);
