# qa-verifier DG2 round 17: summary of integration/*.log (vitest --reporter=verbose). Usage:
#   python3 -I summarize.py <log>... > ../10-integration-series-summary.log
# Per log: totals, exit status, the cluster's server_encoding line, per-suite passing/failing counts for the suites the
# assignment names, and every line outside a passing test that matches error/fail/timeout/warn (counted, deduplicated).
import re
import sys
from collections import Counter

SUITES = [
    ("contract.test.ts", "contract.test.ts"),
    ("blank-text.test.ts", "blank-text.test.ts"),
    ("encoding.test.ts", "/encoding.test.ts"),
    ("invalid-character.test.ts", "invalid-character.test.ts"),
    ("framework-errors.test.ts", "framework-errors.test.ts"),
    ("invalid-utf8.test.ts", "invalid-utf8.test.ts"),
    ("media-types.test.ts", "media-types.test.ts"),
    ("evidence", "evidence"),
    ("db guards", "guards"),
    ("oidc.test.ts", "oidc.test.ts"),
    ("dg2-qa-acceptance", "dg2-qa-acceptance"),
    ("dg2-qa-design-r2", "dg2-qa-design-r2"),
    ("dg2-qa-journey-r2", "dg2-qa-journey-r2"),
    ("dg2-qa-blank-sweep-r3", "dg2-qa-blank-sweep-r3"),
    ("dg2-qa-regress-r3", "dg2-qa-regress-r3"),
]
print("# qa-verifier DG2 round 17: summary of integration/*.log (generated by integration/summarize.py)")
for path in sys.argv[1:]:
    lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
    tests = next((l.strip() for l in reversed(lines) if re.match(r"^\s+Tests\s", l)), "?")
    files = next((l.strip() for l in reversed(lines) if re.match(r"^\s+Test Files\s", l)), "?")
    print(f"== {path.split('/round-17/')[-1]}: {tests} | {files} | {lines[-1]}")
    print("   " + next((l for l in lines if "server_encoding" in l), "server_encoding line: MISSING"))
    print("   " + next((l for l in lines if l.startswith("port-policy")), "port-policy line: none"))
    for label, needle in SUITES:
        ok = sum(1 for l in lines if "✓" in l and needle in l)
        bad = sum(1 for l in lines if ("×" in l or "✗" in l or "FAIL" in l) and needle in l)
        print(f"   {label:28s} {ok} passing lines, {bad} failing lines")
    other = Counter(
        re.sub(r"\d+ms", "", re.sub(r"\(node:\d+\)", "(node:PID)", l.strip()))
        for l in lines
        if re.search(r"error|fail|timeout|warn", l, re.I) and "✓" not in l
    )
    print(f"   lines outside passing tests matching error/fail/timeout/warn: {sum(other.values())}")
    for text, n in other.most_common():
        print(f"     {n:3d} {text[:220]}")
