#!/usr/bin/env node
// Collect third-party licence and notice texts for everything the product SHIPS (scopes runtime + bundled; see
// lib/lockfile.mjs), for /app/licenses in the image (ADR-0011) and for the handover package (§19 item 2).
//
//   node licenses/collect-notices.mjs --out <dir>
//
// Writes <dir>/THIRD-PARTY-NOTICES.md (one section per package: licence id and the full text of each LICENSE,
// LICENCE, NOTICE, COPYING or OFL file) and <dir>/packages/<name>@<version>/<file> copies. Packages that ship no
// licence file are listed explicitly at the top, never silently skipped. Deterministic; no network.
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildInventory } from "./lib/lockfile.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outIdx = process.argv.indexOf("--out");
if (outIdx === -1 || !process.argv[outIdx + 1]) {
  console.error("usage: node licenses/collect-notices.mjs --out <dir>");
  process.exit(64);
}
const out = process.argv[outIdx + 1];
const NOTICE = /^(licen[cs]e|notice|copying|ofl|third[-_]party)([-_.].*)?$/i;

const { entries, lockSha256 } = buildInventory(root);
const shipped = entries.filter((e) => e.scope !== "development");
const missingDir = shipped.filter((e) => !e.installedDir);
if (missingDir.length > 0) {
  console.error(`BLOCKED: not installed: ${missingDir.map((e) => `${e.name}@${e.version}`).join(", ")}`);
  process.exit(3);
}

mkdirSync(join(out, "packages"), { recursive: true });
const sections = [];
const withoutFile = [];
let fileCount = 0;
for (const e of shipped) {
  const files = readdirSync(e.installedDir)
    .filter((f) => NOTICE.test(f) && statSync(join(e.installedDir, f)).isFile())
    .sort();
  const id = `${e.name}@${e.version}`;
  if (files.length === 0) withoutFile.push(e);
  const target = join(out, "packages", id.replace("/", "__"));
  mkdirSync(target, { recursive: true });
  const texts = [];
  for (const f of files) {
    copyFileSync(join(e.installedDir, f), join(target, f));
    fileCount++;
    texts.push(
      `#### ${f}\n\n\`\`\`text\n${readFileSync(join(e.installedDir, f), "utf8").replace(/```/g, "'''").trimEnd()}\n\`\`\``,
    );
  }
  sections.push(
    `### ${id}\n\n- Licence: ${e.license}\n- Scope: ${e.scope}${e.homepage ? `\n- Homepage: ${e.homepage}` : ""}\n\n${
      texts.length > 0
        ? texts.join("\n\n")
        : "_No licence file is shipped in this package; the licence id above is from its package.json._"
    }`,
  );
}

const header = `# Third-party notices: Mobily Transformation Hub

Generated by \`licenses/collect-notices.mjs\` from \`pnpm-lock.yaml\` (sha256 \`${lockSha256}\`).
Covers every package shipped in the application image (scope \`runtime\`) or compiled into the web bundle (scope
\`bundled\`): ${shipped.length} packages, ${fileCount} licence/notice files. The full inventory, including development-only
tooling, is in \`inventory.csv\` and \`sbom.cdx.json\`.

Base-image and service-image licences (Node.js/Debian, PostgreSQL, Keycloak for tests) are listed in
\`deploy/images.lock.json\` and the SBOM; their own notices ship inside those images.

This product is not an official PMI standard or a certified product.

## Packages without a licence file (${withoutFile.length})

${withoutFile.length === 0 ? "None." : withoutFile.map((e) => `- ${e.name}@${e.version} (${e.license})`).join("\n")}

## Packages
`;
writeFileSync(join(out, "THIRD-PARTY-NOTICES.md"), `${header}\n${sections.join("\n\n")}\n`);
console.log(
  `collect-notices: ${shipped.length} shipped packages, ${fileCount} files, ${withoutFile.length} without a licence file -> ${out}`,
);
if (!existsSync(join(out, "THIRD-PARTY-NOTICES.md"))) process.exit(1);
