import { and, eq } from 'drizzle-orm';
import { schema } from '@hub/db';
import { REPORT_SCHEMA_VERSION } from '@hub/domain';
import type { ModuleSeed } from '../../cli/seed-modules';
import { DbService } from '../../platform/db.service';
import { SnapshotsService } from './snapshots.service';

/**
 * Demo sandbox scenario for reporting (idempotent): one executive summary of the demo DC project, generated by the demo
 * project manager through the snapshot command (policy, audit and outbox apply). Its content is computed from the demo
 * records seeded before it — nothing is typed in — and it is badged Demo like every record of the demo project.
 * No export is seeded (files are rendered on request by the worker).
 */
export const reportingSeed: ModuleSeed = {
  name: 'reporting',
  run: async ({ app, dcProjectId: pid, asUser, log }) => {
    const db = app.get(DbService);
    const snapshots = app.get(SnapshotsService);
    await asUser('pm', async (ctx) => {
      const S = schema.reportSnapshot;
      const [existing] = await db
        .tx()
        .select({ id: S.id })
        .from(S)
        .where(and(eq(S.projectId, pid), eq(S.kind, 'executive_summary'), eq(S.schemaVersion, REPORT_SCHEMA_VERSION)))
        .limit(1);
      if (existing) return;
      const s = await snapshots.generate(ctx, pid, { kind: 'executive_summary' });
      log(`reporting: demo executive summary snapshot ${s.id} (${s.contentHash.slice(0, 12)}…)`);
    });
  },
};
