# qa-verifier DG2 round 17: summary of Playwright list-reporter logs. Usage:
#   python3 -I summarize-e2e.py <log>... > 19-e2e-results-summary.log
# Per log: the final counts line and exit status, the server_encoding line, passed/failed/not-run tests per spec file and
# project, the R16-06 and R17 measurement lines printed by the qa specs, and every line outside a passing test that
# matches error/fail/timeout/warn (counted, deduplicated) so that each one can be explained.
import re
import sys
from collections import Counter, defaultdict

RESULT = re.compile(r"^\s+([✓✘-])\s+\d+\s+\[(chromium-(?:en|ar))\]\s+›\s+(\S+?):\d+:\d+\s+›\s+(.*?)(?:\s+\(([\d.]+m?s)\))?\s*$")
print("# qa-verifier DG2 round 17: e2e results (generated by summarize-e2e.py)")
for path in sys.argv[1:]:
    lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
    finals = [l.strip() for l in lines if re.match(r"^\s+\d+ (passed|failed|flaky|skipped|did not run)", l)]
    print(f"== {path.split('/round-17/')[-1]}: {' | '.join(finals)} | {lines[-1] if lines else '(empty)'}")
    print("   " + next((l.strip() for l in lines if "server_encoding" in l), "server_encoding line: none"))
    per = defaultdict(Counter)
    failed = []
    for l in lines:
        m = RESULT.match(l)
        if m:
            mark, proj, spec, title, _ = m.groups()
            per[(spec, proj)][{"✓": "passed", "✘": "FAILED", "-": "not-run"}[mark]] += 1
            if mark != "✓":
                failed.append(f"{mark} [{proj}] {spec} › {title}")
    for (spec, proj), c in sorted(per.items()):
        print(f"   {spec:48s} {proj:12s} " + ", ".join(f"{k} {v}" for k, v in sorted(c.items())))
    for f in failed:
        print(f"   NOT PASSED: {f}")
    for l in lines:
        if re.search(r"\] (r16-06|r17-0\d[a-z-]*|observer-hits):", l) and "timeline" not in l and "-api:" not in l:
            print(f"   MEASURED {l.strip()[:400]}")
    other = Counter(
        re.sub(r"\(\d+(\.\d+)?m?s\)", "", l.strip())
        for l in lines
        if re.search(r"error|fail|timeout|warn", l, re.I) and not RESULT.match(l) and "MEASURED" not in l
    )
    print(f"   lines outside test-result lines matching error/fail/timeout/warn: {sum(other.values())}")
    for text, n in other.most_common():
        print(f"     {n:3d} {text[:240]}")
