# qa-verifier DG2 round 17: tally of the axe summaries written by the e2e runs (e2e-<product|qa>-<loc>/*.json). Usage:
#   python3 -I summarize-axe.py <dir>... > 22-axe-summary.log
# Per file: page checks, and violations by impact. Every serious or critical violation is listed by page and rule.
import json
import os
import sys
from collections import Counter

print("# qa-verifier DG2 round 17: axe tally (generated by summarize-axe.py)")
grand = Counter()
for d in sys.argv[1:]:
    for name in sorted(os.listdir(d)):
        if not name.endswith(".json"):
            continue
        data = json.load(open(os.path.join(d, name), encoding="utf-8"))
        imp = Counter()
        bad = []
        for page, res in data.items():
            for v in res["violations"]:
                imp[v["impact"]] += 1
                if v["impact"] in ("serious", "critical"):
                    bad.append(f"{page}: {v['id']} ({v['impact']}, {v['nodes']} nodes)")
        grand["pages"] += len(data)
        for k, n in imp.items():
            grand[k] += n
        print(f"{d.rstrip('/').split('/')[-1]}/{name}: {len(data)} page checks; violations by impact {dict(imp) or '{}'}")
        for b in bad:
            print(f"   SERIOUS/CRITICAL {b}")
print(f"TOTAL: {grand['pages']} page checks; serious {grand['serious']}, critical {grand['critical']}, moderate {grand['moderate']}, minor {grand['minor']}")
