import { z } from 'zod';
import {
  DOCUMENT_KINDS,
  SCAN_STATUSES,
  EXTRACTION_STATUSES,
  EVIDENCE_LINK_STATUSES,
  SOURCE_TYPES,
  EVIDENCE_TARGET_TYPES,
  CLAIM_TARGET_TYPES,
  CLAIM_INITIAL_STATUSES,
  ALLOWED_FILE_TYPES,
} from '@hub/domain';
import { defineRoute, registerRoutes } from './route';
import {
  Uuid,
  IsoDate,
  IsoInstant,
  ClassificationSchema,
  VerificationStatusSchema,
  PageQuery,
  NoSort,
  SortParam,
  paged,
  Text,
  RequiredText,
  ProjectParams,
  idParams,
  ExpectedVersion,
} from './common';

/**
 * Documents, versions, evidence links, source register & claims (spec §2, §5, §12.1, §14, §15, §17).
 * Every list applies project scope + clearance + room grants inside SQL; totals count visible rows only (AT-03).
 */

const T = ['documents'];
const DocParams = idParams('documentId');
const VersionParams = DocParams.extend({ versionId: Uuid });

export const DocumentKindSchema = z.enum(DOCUMENT_KINDS);
export const ScanStatusSchema = z.enum(SCAN_STATUSES);
export const ExtractionStatusSchema = z.enum(EXTRACTION_STATUSES);
export const EvidenceTargetTypeSchema = z.enum(EVIDENCE_TARGET_TYPES);
export const ClaimTargetTypeSchema = z.enum(CLAIM_TARGET_TYPES as unknown as [string, ...string[]]);

export const DocumentVersionDto = z.object({
  id: Uuid,
  versionNo: z.number().int(),
  filename: z.string(),
  mimeType: z.string(),
  detectedType: z.enum(ALLOWED_FILE_TYPES).nullable(),
  sizeBytes: z.number().int(),
  sha256: z.string(),
  /** `not_scanned` = only the built-in signature check ran (no enterprise scanner configured) — never "clean". */
  scanStatus: ScanStatusSchema,
  scanDetail: z.string().nullable(),
  extractionStatus: ExtractionStatusSchema,
  uploadedBy: Uuid,
  uploadedAt: z.string(),
  note: z.string().nullable(),
  downloadable: z.boolean(),
});

export const DocumentSummaryDto = z.object({
  id: Uuid,
  title: z.string(),
  kind: DocumentKindSchema,
  classification: ClassificationSchema,
  roomId: Uuid.nullable(),
  isDemo: z.boolean(),
  legalHold: z.boolean(),
  retentionUntil: z.string().nullable(),
  currentVersion: DocumentVersionDto.pick({ id: true, versionNo: true, filename: true, detectedType: true, sizeBytes: true, scanStatus: true, extractionStatus: true, uploadedAt: true }).nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
  version: z.number().int(),
});

export const DocumentDetailDto = DocumentSummaryDto.extend({
  legalHoldReason: z.string().nullable(),
  ownerUserId: Uuid.nullable(),
  createdBy: Uuid.nullable(),
  versions: z.array(DocumentVersionDto),
  evidence: z.object({ active: z.number().int(), conflicting: z.number().int() }),
  pendingDisposalRequest: z.object({ id: Uuid, requestedBy: Uuid, reason: z.string().nullable(), createdAt: z.string() }).nullable(),
});

export const UploadResultDto = z.object({
  documentId: Uuid,
  versionId: Uuid,
  versionNo: z.number().int(),
  filename: z.string(),
  detectedType: z.enum(ALLOWED_FILE_TYPES).nullable(),
  mimeType: z.string(),
  sizeBytes: z.number().int(),
  sha256: z.string(),
  scanStatus: ScanStatusSchema,
  scanDetail: z.string().nullable(),
  extractionStatus: ExtractionStatusSchema,
  isCurrent: z.boolean(),
});

export const SearchHitDto = z.object({
  documentId: Uuid,
  title: z.string(),
  kind: DocumentKindSchema,
  classification: ClassificationSchema,
  matchedIn: z.enum(['title', 'content']),
  versionId: Uuid.nullable(),
  section: z.string().nullable(),
  snippet: z.string().nullable(),
});

export const EvidenceLinkDto = z.object({
  id: Uuid,
  targetType: z.string(),
  targetId: Uuid,
  documentId: Uuid.nullable(),
  documentVersionId: Uuid.nullable(),
  documentTitle: z.string().nullable(),
  versionNo: z.number().int().nullable(),
  note: z.string().nullable(),
  purpose: z.string().nullable(),
  status: z.enum(EVIDENCE_LINK_STATUSES),
  conflictWithLinkId: Uuid.nullable(),
  conflictNote: z.string().nullable(),
  reviewedBy: Uuid.nullable(),
  reviewedAt: z.string().nullable(),
  addedBy: Uuid,
  createdAt: z.string(),
  version: z.number().int(),
});

export const SourceDto = z.object({
  id: Uuid,
  code: z.string(),
  sourceType: z.enum(SOURCE_TYPES),
  filename: z.string().nullable(),
  sourceVersion: z.string().nullable(),
  checksum: z.string().nullable(),
  ownerLabel: z.string().nullable(),
  uploadedAt: z.string().nullable(),
  /** Date stated inside the source (report date) — distinct from as-of and extraction dates (spec §2). */
  reportDate: z.string().nullable(),
  asOfDate: z.string().nullable(),
  extractionDate: z.string().nullable(),
  extractionStatus: ExtractionStatusSchema,
  extractionNote: z.string().nullable(),
  documentVersionId: Uuid.nullable(),
  supersedesSourceId: Uuid.nullable(),
  supersededBySourceId: Uuid.nullable(),
  classification: ClassificationSchema,
  isDemo: z.boolean(),
  claimCount: z.number().int(),
  createdAt: z.string(),
  version: z.number().int(),
});

export const ClaimDto = z.object({
  id: Uuid,
  sourceId: Uuid,
  location: z.string(),
  subject: z.string(),
  targetType: z.string().nullable(),
  targetId: Uuid.nullable(),
  field: z.string().nullable(),
  extractedValue: z.string(),
  sourceReportedValue: z.string().nullable(),
  confirmedValue: z.string().nullable(),
  /** 0–1 decimal string (null = not assessed). */
  confidence: z.string().nullable(),
  verificationStatus: VerificationStatusSchema,
  /** Status the claim entered with (immutable; `historical_unverified` claims keep that origin — DOM-P2-04). */
  originStatus: VerificationStatusSchema,
  /** Newer source cited when a claim of historical origin was confirmed (null otherwise). */
  verificationSourceId: Uuid.nullable(),
  reviewerUserId: Uuid.nullable(),
  reviewedAt: z.string().nullable(),
  conflictWithClaimId: Uuid.nullable(),
  appliedToRecord: z.boolean(),
  pendingProposalId: Uuid.nullable(),
  isDemo: z.boolean(),
  createdAt: z.string(),
  createdBy: Uuid.nullable(),
  version: z.number().int(),
});

export const SourceDetailDto = SourceDto.extend({ claims: z.array(ClaimDto) });

export const CompareRowDto = z.object({
  claimId: Uuid,
  subject: z.string(),
  location: z.string(),
  targetType: z.string().nullable(),
  targetId: Uuid.nullable(),
  field: z.string().nullable(),
  /** Current value in the record (read-only). */
  currentValue: z.string().nullable(),
  claimValue: z.string(),
  sourceReportedValue: z.string().nullable(),
  /** Value for the same record field in the superseded (previous) source, if any. */
  previousSourceValue: z.string().nullable(),
  verificationStatus: VerificationStatusSchema,
  differs: z.boolean().nullable(),
  applicable: z.boolean(),
  reason: z.string(),
});

export const ProposedChangeDto = z.object({
  proposalId: Uuid,
  claimId: Uuid,
  targetType: z.string(),
  targetId: Uuid,
  field: z.string(),
  currentValue: z.string().nullable(),
  proposedValue: z.string(),
  status: z.literal('pending'),
  requiredPermission: z.string(),
  message: z.string(),
});

export const UploadPolicyDto = z.object({
  maxUploadBytes: z.number().int(),
  acceptedTypes: z.array(z.object({ type: z.enum(ALLOWED_FILE_TYPES), mime: z.string(), extensions: z.array(z.string()), textExtractable: z.boolean() })),
  /** `enterprise: false` = only the built-in signature check runs; files are never reported "clean". */
  scanner: z.object({ engine: z.string(), enterprise: z.boolean() }),
  /** Whether `not_scanned` files may be downloaded / linked / indexed in this deployment (ADR-0010). */
  allowUnscanned: z.boolean(),
  storageStatus: z.enum(['configured', 'not_configured']),
});

const Confidence = z.string().regex(/^(0(\.\d{1,3})?|1(\.0{1,3})?)$/, 'Decimal between 0 and 1 (max 3 dp)');
const Reason = RequiredText(1000);
const DocIdOnly = z.object({ id: Uuid, version: z.number().int() });

export const documentsRoutes = registerRoutes({
  // ------------------------------------------------------------------------------------------------ documents
  listDocuments: defineRoute({
    id: 'documents.listDocuments',
    method: 'GET',
    path: '/api/v1/projects/:projectId/documents',
    summary: 'Documents visible to the caller (scope + clearance + room grants in SQL; q searches titles)',
    tags: T,
    access: 'documents.document.read',
    params: ProjectParams,
    // Default order: most recently updated first, then title.
    query: PageQuery.extend({ kind: DocumentKindSchema.optional(), classification: ClassificationSchema.optional(), sort: SortParam(['title', 'kind', 'createdAt', 'updatedAt']) }),
    response: paged(DocumentSummaryDto),
  }),
  searchDocuments: defineRoute({
    id: 'documents.searchDocuments',
    method: 'GET',
    path: '/api/v1/projects/:projectId/documents/search',
    summary: 'Full-text search over titles and indexed content of documents the caller may read (ACL before ranking)',
    tags: T,
    access: 'documents.document.read',
    params: ProjectParams,
    // Results are ranked by relevance (then title): no sort.
    query: z.object({ q: RequiredText(200), page: PageQuery.shape.page, pageSize: PageQuery.shape.pageSize, kind: DocumentKindSchema.optional(), classification: ClassificationSchema.optional(), sort: NoSort }),
    response: paged(SearchHitDto),
  }),
  uploadPolicy: defineRoute({
    id: 'documents.uploadPolicy',
    method: 'GET',
    path: '/api/v1/projects/:projectId/documents/upload-policy',
    summary: 'Upload limits, accepted file types and the honest scanner / storage status (for upload screens)',
    tags: T,
    access: 'documents.document.read',
    params: ProjectParams,
    response: UploadPolicyDto,
  }),
  createDocument: defineRoute({
    id: 'documents.createDocument',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents',
    summary: "Create document metadata (classification cannot exceed the uploader's clearance); upload versions separately",
    tags: T,
    access: 'documents.document.upload',
    command: true,
    params: ProjectParams,
    body: z.object({
      title: RequiredText(300),
      kind: DocumentKindSchema,
      classification: ClassificationSchema.default('confidential'),
      roomId: Uuid.optional(),
      retentionUntil: IsoDate.optional(),
    }),
    response: DocIdOnly,
  }),
  getDocument: defineRoute({
    id: 'documents.getDocument',
    method: 'GET',
    path: '/api/v1/projects/:projectId/documents/:documentId',
    summary: 'Document metadata, versions, evidence counts',
    tags: T,
    access: 'documents.document.read',
    params: DocParams,
    response: DocumentDetailDto,
  }),
  uploadVersion: defineRoute({
    id: 'documents.uploadVersion',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents/:documentId/versions',
    summary:
      'Upload a version: raw application/octet-stream body, headers x-filename (percent-encoded UTF-8) and x-file-type (declared, untrusted). Size limit → signature check (quarantine) → magic-byte allowlist → SHA-256 → storage',
    tags: T,
    access: 'documents.document.upload',
    command: true,
    upload: true,
    params: DocParams,
    query: z.object({ note: Text(500).optional() }),
    response: UploadResultDto,
  }),
  downloadVersion: defineRoute({
    id: 'documents.downloadVersion',
    method: 'GET',
    path: '/api/v1/projects/:projectId/documents/:documentId/versions/:versionId/download',
    summary: 'Authorised, audited download stream (attachment, nosniff, checksum verified). Quarantined/rejected versions are never served',
    tags: T,
    access: 'documents.document.download',
    binary: true,
    params: VersionParams,
    response: z.any(),
  }),
  classifyDocument: defineRoute({
    id: 'documents.classifyDocument',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents/:documentId/classify',
    summary: 'Set or raise the classification (lowering requires declassify). Invalidates the retrieval index',
    tags: T,
    access: 'documents.document.classify',
    command: true,
    params: DocParams,
    body: z.object({ expectedVersion: ExpectedVersion, classification: ClassificationSchema, reason: Reason }),
    response: DocIdOnly,
  }),
  declassifyDocument: defineRoute({
    id: 'documents.declassifyDocument',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents/:documentId/declassify',
    summary: 'Lower the classification (separation of duties: not the document owner/creator). Invalidates the retrieval index',
    tags: T,
    access: 'documents.document.declassify',
    command: true,
    params: DocParams,
    body: z.object({ expectedVersion: ExpectedVersion, classification: ClassificationSchema, reason: Reason }),
    response: DocIdOnly,
  }),
  moveDocumentRoom: defineRoute({
    id: 'documents.moveDocumentRoom',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents/:documentId/move-room',
    summary: 'Move a document into/out of a partner or clean-team room (ACL change; caller needs access to both). Invalidates the index',
    tags: T,
    access: 'documents.document.classify',
    command: true,
    params: DocParams,
    body: z.object({ expectedVersion: ExpectedVersion, roomId: Uuid.nullable(), reason: Reason }),
    response: DocIdOnly,
  }),
  setLegalHold: defineRoute({
    id: 'documents.setLegalHold',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents/:documentId/legal-hold',
    summary: 'Place (hold=true) or release (hold=false) a legal hold',
    tags: T,
    access: 'documents.legal_hold.manage',
    command: true,
    params: DocParams,
    body: z.object({ expectedVersion: ExpectedVersion, hold: z.boolean(), reason: Reason }),
    response: DocIdOnly,
  }),
  setRetention: defineRoute({
    id: 'documents.setRetention',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents/:documentId/retention',
    summary: 'Set or clear the retention date (disposal is refused before it)',
    tags: T,
    access: 'documents.legal_hold.manage',
    command: true,
    params: DocParams,
    body: z.object({ expectedVersion: ExpectedVersion, retentionUntil: IsoDate.nullable(), reason: Reason }),
    response: DocIdOnly,
  }),
  requestDisposal: defineRoute({
    id: 'documents.requestDisposal',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents/:documentId/disposal-requests',
    summary: 'Request authorised disposal (refused under legal hold / before retention expiry). Executed by a different person',
    tags: T,
    access: 'documents.document.archive',
    command: true,
    params: DocParams,
    body: z.object({ expectedVersion: ExpectedVersion, reason: Reason }),
    response: z.object({ requestId: Uuid }),
  }),
  disposeDocument: defineRoute({
    id: 'documents.disposeDocument',
    method: 'POST',
    path: '/api/v1/projects/:projectId/documents/:documentId/dispose',
    summary: 'Execute a pending disposal request (soft delete). not_self (requester, owner) + authority; refused under hold/retention (DB trigger too)',
    tags: T,
    access: 'documents.document.dispose',
    command: true,
    params: DocParams,
    body: z.object({ expectedVersion: ExpectedVersion, requestId: Uuid, reason: Reason }),
    response: DocIdOnly,
  }),

  // ------------------------------------------------------------------------------------------------ evidence
  listEvidence: defineRoute({
    id: 'documents.listEvidence',
    method: 'GET',
    path: '/api/v1/projects/:projectId/evidence',
    summary: 'Evidence links for a record (links to documents the caller cannot read are omitted, including from the total)',
    tags: T,
    access: 'documents.document.read',
    params: ProjectParams,
    query: z.object({ targetType: EvidenceTargetTypeSchema, targetId: Uuid, includeInactive: z.enum(['true', 'false']).default('true'), sort: NoSort }),
    response: z.object({ items: z.array(EvidenceLinkDto), total: z.number().int() }),
  }),
  linkEvidence: defineRoute({
    id: 'documents.linkEvidence',
    method: 'POST',
    path: '/api/v1/projects/:projectId/evidence',
    summary: 'Link a document version (or a note) as evidence to a record of the same project; optionally mark it as contradicting an earlier link (AT-14)',
    tags: T,
    access: 'documents.evidence.link',
    command: true,
    params: ProjectParams,
    body: z
      .object({
        targetType: EvidenceTargetTypeSchema,
        targetId: Uuid,
        documentId: Uuid.optional(),
        documentVersionId: Uuid.optional(),
        note: Text(4000).optional(),
        purpose: Text(500).optional(),
        conflictsWithLinkId: Uuid.optional(),
        conflictNote: Text(2000).optional(),
      })
      .refine((b) => !!b.documentId || !!b.documentVersionId || !!b.note?.trim(), { message: 'A document (version) or a note is required' }),
    response: z.object({ id: Uuid, status: z.enum(EVIDENCE_LINK_STATUSES) }),
  }),
  verifyEvidence: defineRoute({
    id: 'documents.verifyEvidence',
    method: 'POST',
    path: '/api/v1/projects/:projectId/evidence/:linkId/verify',
    summary: 'Accept or reject linked evidence (not the linker or the version uploader); SHA-256 re-verified',
    tags: T,
    access: 'documents.evidence.verify',
    command: true,
    params: idParams('linkId'),
    body: z.object({ expectedVersion: ExpectedVersion, decision: z.enum(['accept', 'reject']), note: Text(2000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(EVIDENCE_LINK_STATUSES), version: z.number().int() }),
  }),
  flagEvidenceConflict: defineRoute({
    id: 'documents.flagEvidenceConflict',
    method: 'POST',
    path: '/api/v1/projects/:projectId/evidence/:linkId/flag-conflict',
    summary: 'Flag two links on the same record as conflicting (both preserved; triggers reassessment)',
    tags: T,
    access: 'documents.evidence.link',
    command: true,
    params: idParams('linkId'),
    body: z.object({ expectedVersion: ExpectedVersion, withLinkId: Uuid, note: RequiredText(2000) }),
    response: z.object({ id: Uuid, status: z.enum(EVIDENCE_LINK_STATUSES), version: z.number().int() }),
  }),
  supersedeEvidence: defineRoute({
    id: 'documents.supersedeEvidence',
    method: 'POST',
    path: '/api/v1/projects/:projectId/evidence/:linkId/supersede',
    summary: 'Mark a link as superseded (kept for history; triggers reassessment)',
    tags: T,
    access: 'documents.evidence.link',
    command: true,
    params: idParams('linkId'),
    body: z.object({ expectedVersion: ExpectedVersion, note: RequiredText(2000) }),
    response: z.object({ id: Uuid, status: z.enum(EVIDENCE_LINK_STATUSES), version: z.number().int() }),
  }),

  // ------------------------------------------------------------------------------------------------ sources
  listSources: defineRoute({
    id: 'documents.listSources',
    method: 'GET',
    path: '/api/v1/projects/:projectId/sources',
    summary: 'Source register (report / as-of / extraction dates kept separate)',
    tags: T,
    access: 'documents.document.read',
    params: ProjectParams,
    // Default order: code.
    query: PageQuery.extend({ sort: SortParam(['code', 'filename', 'reportDate', 'asOfDate', 'extractionDate', 'createdAt']) }),
    response: paged(SourceDto),
  }),
  createSource: defineRoute({
    id: 'documents.createSource',
    method: 'POST',
    path: '/api/v1/projects/:projectId/sources',
    summary: 'Register a source. A superseded source is preserved (supersedesSourceId). Checksum/filename come from the linked version when given',
    tags: T,
    access: 'documents.source.manage',
    command: true,
    params: ProjectParams,
    body: z.object({
      sourceType: z.enum(SOURCE_TYPES),
      filename: Text(300).optional(),
      sourceVersion: Text(32).optional(),
      checksum: z.string().regex(/^[0-9a-f]{64}$/, 'SHA-256 hex').optional(),
      ownerLabel: Text(200).optional(),
      uploadedAt: IsoInstant.optional(),
      reportDate: IsoDate.optional(),
      asOfDate: IsoDate.optional(),
      extractionDate: IsoDate.optional(),
      extractionStatus: ExtractionStatusSchema.default('not_performed'),
      extractionNote: Text(2000).optional(),
      documentVersionId: Uuid.optional(),
      supersedesSourceId: Uuid.optional(),
      classification: ClassificationSchema.default('confidential'),
    }),
    response: z.object({ id: Uuid, code: z.string() }),
  }),
  getSource: defineRoute({
    id: 'documents.getSource',
    method: 'GET',
    path: '/api/v1/projects/:projectId/sources/:sourceId',
    summary: 'Source with its claims',
    tags: T,
    access: 'documents.document.read',
    params: idParams('sourceId'),
    response: SourceDetailDto,
  }),
  updateSource: defineRoute({
    id: 'documents.updateSource',
    method: 'PATCH',
    path: '/api/v1/projects/:projectId/sources/:sourceId',
    summary: 'Update descriptive source fields (no status fields)',
    tags: T,
    access: 'documents.source.manage',
    params: idParams('sourceId'),
    body: z.object({
      expectedVersion: ExpectedVersion,
      filename: Text(300).nullable().optional(),
      sourceVersion: Text(32).nullable().optional(),
      ownerLabel: Text(200).nullable().optional(),
      reportDate: IsoDate.nullable().optional(),
      asOfDate: IsoDate.nullable().optional(),
    }),
    response: z.object({ id: Uuid, version: z.number().int() }),
  }),
  recordExtraction: defineRoute({
    id: 'documents.recordExtraction',
    method: 'POST',
    path: '/api/v1/projects/:projectId/sources/:sourceId/extraction',
    summary: 'Record the extraction result (status, date, note) of a source',
    tags: T,
    access: 'documents.source.manage',
    command: true,
    params: idParams('sourceId'),
    body: z.object({ expectedVersion: ExpectedVersion, extractionStatus: ExtractionStatusSchema, extractionDate: IsoDate.nullable(), extractionNote: Text(2000).optional() }),
    response: z.object({ id: Uuid, version: z.number().int() }),
  }),
  compareSource: defineRoute({
    id: 'documents.compareSource',
    method: 'GET',
    path: '/api/v1/projects/:projectId/sources/:sourceId/compare',
    summary: 'Claims side-by-side with current record values and the previous source — proposed changes only; nothing is merged',
    tags: T,
    access: 'documents.document.read',
    params: idParams('sourceId'),
    response: z.object({ sourceId: Uuid, previousSourceId: Uuid.nullable(), rows: z.array(CompareRowDto) }),
  }),
  createClaim: defineRoute({
    id: 'documents.createClaim',
    method: 'POST',
    path: '/api/v1/projects/:projectId/sources/:sourceId/claims',
    summary: 'Add an extracted claim (enters as unknown / proposed / historical_unverified / assumed — never confirmed)',
    tags: T,
    access: 'documents.source.manage',
    command: true,
    params: idParams('sourceId'),
    body: z.object({
      location: RequiredText(500),
      subject: RequiredText(500),
      targetType: ClaimTargetTypeSchema.optional(),
      targetId: Uuid.optional(),
      field: z.string().trim().max(64).optional(),
      extractedValue: RequiredText(4000),
      sourceReportedValue: Text(4000).optional(),
      confidence: Confidence.optional(),
      verificationStatus: z.enum(CLAIM_INITIAL_STATUSES).default('unknown'),
    }),
    response: z.object({ id: Uuid }),
  }),
  updateClaim: defineRoute({
    id: 'documents.updateClaim',
    method: 'PATCH',
    path: '/api/v1/projects/:projectId/claims/:claimId',
    summary: 'Correct descriptive claim fields (location, subject, record mapping, confidence). Extracted/source-reported values and status are immutable here; locked once confirmed',
    tags: T,
    access: 'documents.source.manage',
    params: idParams('claimId'),
    body: z.object({
      expectedVersion: ExpectedVersion,
      location: RequiredText(500).optional(),
      subject: RequiredText(500).optional(),
      targetType: ClaimTargetTypeSchema.nullable().optional(),
      targetId: Uuid.nullable().optional(),
      field: z.string().trim().max(64).nullable().optional(),
      confidence: Confidence.nullable().optional(),
    }),
    response: z.object({ id: Uuid, version: z.number().int() }),
  }),
  reviewClaim: defineRoute({
    id: 'documents.reviewClaim',
    method: 'POST',
    path: '/api/v1/projects/:projectId/claims/:claimId/review',
    summary: 'Set a claim verification status (not the claim author). A historical claim is confirmed only with a verifying newer source, by someone other than its extractor and previous reviewer',
    tags: T,
    access: 'documents.claim.verify',
    command: true,
    params: idParams('claimId'),
    body: z.object({
      expectedVersion: ExpectedVersion,
      verificationStatus: VerificationStatusSchema,
      confirmedValue: Text(4000).optional(),
      /** With `conflicting`: the other claim is flagged conflicting too (AT-14, DOM-P2-19). */
      conflictWithClaimId: Uuid.optional(),
      /** Required to confirm a claim of historical origin: a different, newer source of the project (DOM-P2-04). */
      verificationSourceId: Uuid.optional(),
      note: Text(2000).optional(),
    }),
    response: z.object({ id: Uuid, verificationStatus: VerificationStatusSchema, version: z.number().int() }),
  }),
  proposeClaimChange: defineRoute({
    id: 'documents.proposeClaimChange',
    method: 'POST',
    path: '/api/v1/projects/:projectId/claims/:claimId/propose-change',
    summary: "'Apply' a confirmed claim by creating a PROPOSED change for the record owner's review; the record itself is not changed (AT-01)",
    tags: T,
    access: 'documents.source.manage',
    command: true,
    params: idParams('claimId'),
    body: z.object({ expectedVersion: ExpectedVersion, note: Text(2000).optional() }),
    response: ProposedChangeDto,
  }),
});
