import { z } from 'zod';
import {
  ASSESSMENT_BASES,
  CLOSING_DELIVERABLE_STATUSES,
  CLOSING_KINDS,
  CLOSING_STATUSES,
  CONDITION_KINDS,
  CONDITION_STATUSES,
  DD_DOMAINS,
  DD_EXTERNAL_STATUSES,
  DD_RELEASE_STATUSES,
  DISCLOSURE_STATUSES,
  FINDING_STATUSES,
  FUNDS_FLOW_STATUSES,
  MATERIALITY,
  NDA_STATUSES,
  NEGOTIATION_ISSUE_STATUSES,
  PARTNER_CONFLICT_STATUSES,
  PARTNER_STAGES,
  POST_CLOSE_KINDS,
  POST_CLOSE_STATUSES,
  PROGRAM_CLOSURE_STATUSES,
  ROLE_KEYS,
  ROOM_ACCESS_EVENT_KINDS,
  ROOM_ACCESS_LEVELS,
  ROOM_TYPES,
  APPROVAL_STATES,
  APPROVAL_REQUEST_STATUSES,
  GATE_ASSESSMENT_STATUSES,
} from '@hub/domain';
import { defineRoute, registerRoutes } from './route';
import {
  ClassificationSchema,
  Currency,
  DecimalString,
  ExpectedVersion,
  IsoDate,
  IsoInstant,
  MoneySchema,
  PageQuery,
  ProjectParams,
  RequiredText,
  ServerMessageSchema,
  SortParam,
  Text,
  UnitScale,
  Uuid,
  paged,
} from './common';
import { LinkedDecisionSummaryDto } from './readiness';

/**
 * JV / partner process / due diligence / signing & closing (spec §8; REQ-JV-001..019, REQ-LCY-008/009, REQ-ENT-012;
 * AT-03, AT-11, AT-12, AT-13, AT-19). Status changes are explicit commands (POST …/<verb>) with `expectedVersion`; PATCH
 * routes change descriptive fields only. Room content is visible only with a room grant (404 otherwise); external
 * (partner) accounts use the `/partner-access/...` projection. The platform never executes payments (funds flow is
 * record-only) and never invents partner identities, ownership percentages, valuations or terms.
 */

const P = '/api/v1/projects/:projectId';
const tags = ['jv'];

const Stage = z.enum(PARTNER_STAGES);
const Role = z.enum(ROLE_KEYS);
const Evidence = z.object({ active: z.number().int(), conflicting: z.number().int() });
const VersionResult = z.object({ id: Uuid, version: z.number().int() });
const CreatedResult = z.object({ id: Uuid, code: z.string().nullable(), version: z.number().int() });
const Cmd = z.object({ expectedVersion: ExpectedVersion, note: Text(4000).optional() });
const CmdWithReason = z.object({ expectedVersion: ExpectedVersion, reason: RequiredText(4000) });
/** Display names of the users referenced in the response (so the UI never shows bare ids). */
const People = z.record(z.string(), z.string());
const ServerMessages = z.array(ServerMessageSchema);
const DecimalPercent = z.string().regex(/^\d{1,3}(\.\d{1,4})?$/, 'Expected a percentage (max 4 dp)');
const Score = z.string().regex(/^\d(\.\d{1,2})?$/, 'Expected a score 0–5 (max 2 dp)');
const Weight = z.string().regex(/^\d{1,3}(\.\d{1,2})?$/, 'Expected a weight (max 2 dp)');

const idP = <K extends string>(key: K) => ProjectParams.extend({ [key]: Uuid } as { [X in K]: typeof Uuid });
const PartnerParams = idP('partnerId');
const RoomParams = idP('roomId');
const EventParams = idP('eventId');

// ---------------------------------------------------------------------------------------------------------------
// Partners (REQ-JV-002..006)

export const PartnerDto = z.object({
  id: Uuid,
  code: z.string(),
  name: z.string(),
  stage: Stage,
  shortlisted: z.boolean(),
  ndaStatus: z.enum(NDA_STATUSES),
  outreachApproved: z.boolean(),
  /** Weighted screening score (0–5) — null until every approved criterion is scored. */
  weightedScore: z.string().nullable(),
  classification: ClassificationSchema,
  isDemo: z.boolean(),
  updatedAt: z.string(),
  version: z.number().int(),
});

export const PartnerConflictDto = z.object({
  id: Uuid,
  declarantUserId: Uuid.nullable(),
  description: z.string(),
  mitigation: z.string().nullable(),
  status: z.enum(PARTNER_CONFLICT_STATUSES),
  createdAt: z.string(),
  createdBy: Uuid.nullable(),
});

export const PartnerContactDto = z.object({ id: Uuid, userId: Uuid, note: z.string().nullable(), createdAt: z.string(), revokedAt: z.string().nullable() });

const ApprovalStep = z.object({ requestId: Uuid, status: z.enum(APPROVAL_REQUEST_STATUSES), requestedBy: Uuid, requestedAt: z.string() });

export const PartnerDetailDto = PartnerDto.extend({
  description: z.string().nullable(),
  legalEntityId: Uuid.nullable(),
  stageChangedAt: z.string().nullable(),
  /** Outreach approval (separate from NDA and from materials access — REQ-JV-004). */
  outreach: z.object({ request: ApprovalStep.nullable(), approvedBy: Uuid.nullable(), approvedAt: z.string().nullable() }),
  /** NDA execution — grants no document access by itself (REQ-JV-005). */
  nda: z.object({ status: z.enum(NDA_STATUSES), executedOn: z.string().nullable(), documentId: Uuid.nullable(), request: ApprovalStep.nullable(), recordedBy: Uuid.nullable(), recordedAt: z.string().nullable() }),
  materialsAccessApprovedBy: Uuid.nullable(),
  materialsAccessApprovedAt: z.string().nullable(),
  withdrawnReason: z.string().nullable(),
  /** Stages reachable next through `advance` (guarded stages use their own approval commands). */
  nextStages: z.array(Stage),
  conflicts: z.array(PartnerConflictDto),
  contacts: z.array(PartnerContactDto),
  createdAt: z.string(),
  createdBy: Uuid.nullable(),
  people: People,
});

export const ScreeningCriterionDto = z.object({ key: z.string(), name: z.string(), nameAr: z.string().nullable(), weight: z.string() });
export const CriteriaSetDto = z.object({ id: Uuid, criteria: z.array(ScreeningCriterionDto), totalWeight: z.string(), note: z.string().nullable(), updatedAt: z.string(), version: z.number().int() });

export const AssessmentEntryDto = z.object({
  id: Uuid,
  partnerId: Uuid,
  proposalId: Uuid.nullable(),
  criterionKey: z.string().nullable(),
  /** `fact` (cites its source) or `judgement` (the team's view) — REQ-JV-006. */
  basis: z.enum(ASSESSMENT_BASES),
  statement: z.string(),
  score: z.string().nullable(),
  sourceReference: z.string().nullable(),
  documentId: Uuid.nullable(),
  isDemo: z.boolean(),
  createdAt: z.string(),
  createdBy: Uuid.nullable(),
});

export const ProposalDto = z.object({
  id: Uuid,
  partnerId: Uuid,
  code: z.string(),
  title: z.string(),
  receivedOn: z.string().nullable(),
  scope: z.string().nullable(),
  termsSummary: z.string().nullable(),
  documentId: Uuid.nullable(),
  supersedesProposalId: Uuid.nullable(),
  classification: ClassificationSchema,
  isDemo: z.boolean(),
  createdAt: z.string(),
  createdBy: Uuid.nullable(),
  version: z.number().int(),
});

export const PartnerComparisonDto = z.object({
  criteria: z.array(ScreeningCriterionDto),
  items: z.array(
    z.object({
      partnerId: Uuid,
      code: z.string(),
      name: z.string(),
      stage: Stage,
      shortlisted: z.boolean(),
      /** Latest score per criterion (0–5), null when not scored. */
      scores: z.record(z.string(), z.string().nullable()),
      weightedScore: z.string().nullable(),
      missing: z.array(z.string()),
      facts: z.number().int(),
      judgements: z.number().int(),
    }),
  ),
  /** How to read the comparison (facts vs judgement; unscored criteria are not guessed). */
  basisNote: z.string(),
});

// ---------------------------------------------------------------------------------------------------------------
// Deal scenarios (REQ-JV-007) and negotiation issues (REQ-JV-008)

const OwnershipLine = z.object({ party: RequiredText(200), percent: DecimalPercent.nullable(), note: Text(1000).nullable().optional() });
const ContributionLine = z.object({
  party: RequiredText(200),
  description: RequiredText(2000),
  amount: DecimalString.nullable().optional(),
  currency: Currency.nullable().optional(),
  unitScale: UnitScale.nullable().optional(),
});
const OwnershipDto = z.object({ party: z.string(), percent: z.string().nullable(), note: z.string().nullable() });
const ContributionDto = z.object({ party: z.string(), description: z.string(), amount: MoneySchema.nullable() });

export const DealScenarioDto = z.object({
  id: Uuid,
  code: z.string().nullable(),
  name: z.string(),
  partnerId: Uuid.nullable(),
  versionNo: z.number().int(),
  versionLabel: z.string(),
  ownership: z.array(OwnershipDto),
  /** True only when every party has an entered percentage (never defaulted). */
  ownershipComplete: z.boolean(),
  ownershipTotal: z.string().nullable(),
  approvalState: z.enum(APPROVAL_STATES),
  classification: ClassificationSchema,
  isDemo: z.boolean(),
  updatedAt: z.string(),
  version: z.number().int(),
});
export const DealScenarioVersionDto = z.object({
  versionNo: z.number().int(),
  versionLabel: z.string(),
  ownership: z.array(OwnershipDto),
  contributions: z.array(ContributionDto),
  governanceTerms: z.string().nullable(),
  assumptions: z.string().nullable(),
  changeNote: z.string().nullable(),
  createdAt: z.string(),
  createdBy: Uuid.nullable(),
});
export const DealScenarioDetailDto = DealScenarioDto.extend({
  contributions: z.array(ContributionDto),
  governanceTerms: z.string().nullable(),
  assumptions: z.string().nullable(),
  versions: z.array(DealScenarioVersionDto),
  people: People,
});

const Position = z.object({ party: RequiredText(200), position: RequiredText(4000) });
export const NegotiationIssueDto = z.object({
  id: Uuid,
  code: z.string(),
  partnerId: Uuid.nullable(),
  agreementId: Uuid.nullable(),
  issue: z.string(),
  positions: z.array(z.object({ party: z.string(), position: z.string() })),
  alternatives: z.string().nullable(),
  requiredApproval: z.string().nullable(),
  requiresApproval: z.boolean(),
  decisionId: Uuid.nullable(),
  /** The linked governance decision — null when none is linked or the caller cannot read it. */
  decision: LinkedDecisionSummaryDto.nullable(),
  documentId: Uuid.nullable(),
  documentRef: z.string().nullable(),
  resolution: z.string().nullable(),
  status: z.enum(NEGOTIATION_ISSUE_STATUSES),
  allowedCommands: z.array(z.string()),
  classification: ClassificationSchema,
  isDemo: z.boolean(),
  updatedAt: z.string(),
  version: z.number().int(),
});

// ---------------------------------------------------------------------------------------------------------------
// Rooms, grants, VDR index, disclosures, access history (REQ-JV-001/005/009, REQ-ENT-012)

export const RoomDto = z.object({
  id: Uuid,
  name: z.string(),
  type: z.enum(ROOM_TYPES),
  partnerId: Uuid.nullable(),
  classification: ClassificationSchema,
  locked: z.boolean(),
  /** The caller holds an active grant (can open the room); administrators see room metadata without content. */
  canOpen: z.boolean(),
  myAccessLevel: z.enum(ROOM_ACCESS_LEVELS).nullable(),
  isDemo: z.boolean(),
  createdAt: z.string(),
  version: z.number().int(),
});

export const RoomDetailDto = RoomDto.extend({
  description: z.string().nullable(),
  lockedAt: z.string().nullable(),
  lockReason: z.string().nullable(),
  /** Counts inside the room (computed in SQL with the caller's ACL). */
  counts: z.object({ documents: z.number().int(), disclosuresReleased: z.number().int(), ddRequests: z.number().int(), findings: z.number().int() }),
});

export const RoomIndexItemDto = z.object({
  documentId: Uuid,
  title: z.string(),
  kind: z.string(),
  classification: ClassificationSchema,
  currentVersion: z.object({ id: Uuid, versionNo: z.number().int(), filename: z.string(), scanStatus: z.string() }).nullable(),
  /** Latest disclosure of this document in the room (requested / released / rejected / revoked). */
  disclosure: z.object({ id: Uuid, status: z.enum(DISCLOSURE_STATUSES), documentVersionId: Uuid, releasedAt: z.string().nullable() }).nullable(),
});

export const RoomGrantDto = z.object({
  id: Uuid,
  roomId: Uuid,
  userId: Uuid,
  displayName: z.string().nullable(),
  accountType: z.enum(['internal', 'external']).nullable(),
  accessLevel: z.enum(ROOM_ACCESS_LEVELS),
  role: Role.nullable(),
  reason: z.string(),
  attestationRef: z.string().nullable(),
  grantedBy: Uuid,
  grantedAt: z.string(),
  expiresAt: z.string().nullable(),
  revokedAt: z.string().nullable(),
  revokedBy: Uuid.nullable(),
  revokeReason: z.string().nullable(),
  active: z.boolean(),
});

export const DisclosureDto = z.object({
  id: Uuid,
  roomId: Uuid,
  documentId: Uuid,
  documentTitle: z.string(),
  documentVersionId: Uuid,
  versionNo: z.number().int(),
  filename: z.string(),
  diligenceRequestId: Uuid.nullable(),
  status: z.enum(DISCLOSURE_STATUSES),
  requestNote: z.string().nullable(),
  requestedBy: Uuid,
  requestedAt: z.string(),
  releasedBy: Uuid.nullable(),
  releasedAt: z.string().nullable(),
  revokedBy: Uuid.nullable(),
  revokedAt: z.string().nullable(),
  statusReason: z.string().nullable(),
  version: z.number().int(),
});

export const RoomAccessEventDto = z.object({
  id: Uuid,
  kind: z.enum(ROOM_ACCESS_EVENT_KINDS),
  actorUserId: Uuid.nullable(),
  subjectUserId: Uuid.nullable(),
  grantId: Uuid.nullable(),
  disclosureId: Uuid.nullable(),
  diligenceRequestId: Uuid.nullable(),
  documentVersionId: Uuid.nullable(),
  note: z.string().nullable(),
  createdAt: z.string(),
});

/** External (counterparty) projection: only the room's name and items DISCLOSED into it. */
export const ExternalRoomDto = z.object({ id: Uuid, name: z.string() });
export const ExternalDisclosureDto = z.object({ id: Uuid, title: z.string(), filename: z.string(), versionNo: z.number().int(), sizeBytes: z.number().int(), releasedAt: z.string() });
export const ExternalDdRequestDto = z.object({
  id: Uuid,
  number: z.number().int(),
  question: z.string(),
  domain: z.string(),
  dueDate: z.string().nullable(),
  status: z.enum(DD_EXTERNAL_STATUSES),
  /** The RELEASED answer only (never drafts, reviewers or assignees). */
  answer: z.string().nullable(),
  answeredAt: z.string().nullable(),
  createdAt: z.string(),
});

// ---------------------------------------------------------------------------------------------------------------
// DD requests / Q&A (REQ-JV-010) and findings (REQ-JV-011)

export const DdRequestDto = z.object({
  id: Uuid,
  number: z.number().int(),
  roomId: Uuid.nullable(),
  partnerId: Uuid.nullable(),
  origin: z.enum(['internal', 'partner']),
  question: z.string(),
  domain: z.string(),
  requesterLabel: z.string().nullable(),
  assigneeUserId: Uuid.nullable(),
  reviewerUserId: Uuid.nullable(),
  dueDate: z.string().nullable(),
  releaseStatus: z.enum(DD_RELEASE_STATUSES),
  classification: ClassificationSchema,
  isDemo: z.boolean(),
  createdAt: z.string(),
  createdBy: Uuid.nullable(),
  version: z.number().int(),
});
export const DdRequestDetailDto = DdRequestDto.extend({
  answerDraft: z.string().nullable(),
  draftedBy: Uuid.nullable(),
  evidenceDocumentIds: z.array(Uuid),
  /**
   * DOM-P4-05: the version of each evidence document pinned when the answer was submitted for review — the version the
   * reviewer approves and the release discloses. `current` = still the document's current version.
   */
  evidenceVersions: z.array(z.object({ documentId: Uuid, versionId: Uuid, current: z.boolean() })),
  submittedForReviewBy: Uuid.nullable(),
  submittedForReviewAt: z.string().nullable(),
  releaseApprovedBy: Uuid.nullable(),
  releaseApprovedAt: z.string().nullable(),
  reviewNote: z.string().nullable(),
  releasedBy: Uuid.nullable(),
  releasedAnswer: z.string().nullable(),
  releasedVersion: z.number().int().nullable(),
  releasedAt: z.string().nullable(),
  allowedCommands: z.array(z.string()),
  people: People,
});

export const FindingDto = z.object({
  id: Uuid,
  code: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  materiality: z.enum(MATERIALITY),
  material: z.boolean(),
  partnerId: Uuid.nullable(),
  roomId: Uuid.nullable(),
  diligenceRequestId: Uuid.nullable(),
  riskId: Uuid.nullable(),
  remediation: z.string().nullable(),
  remediationOwnerUserId: Uuid.nullable(),
  remediationDueDate: z.string().nullable(),
  valuationImplication: z.string().nullable(),
  documentImplication: z.string().nullable(),
  cpImplication: z.string().nullable(),
  conditionId: Uuid.nullable(),
  status: z.enum(FINDING_STATUSES),
  statusReason: z.string().nullable(),
  allowedCommands: z.array(z.string()),
  classification: ClassificationSchema,
  isDemo: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
  version: z.number().int(),
});

// ---------------------------------------------------------------------------------------------------------------
// Signing & closing events, checklists, CPs, funds flow, post-close (REQ-LCY-009, REQ-JV-012..018)

export const EventBlockerDto = z.object({ kind: z.enum(['signing', 'condition', 'checklist_item']), ref: z.string(), message: z.string(), messageI18n: ServerMessages });

export const EventDto = z.object({
  id: Uuid,
  kind: z.enum(CLOSING_KINDS),
  code: z.string().nullable(),
  sequence: z.number().int(),
  name: z.string(),
  partnerId: Uuid.nullable(),
  signingId: Uuid.nullable(),
  targetDate: z.string().nullable(),
  status: z.enum(CLOSING_STATUSES),
  confirmedBy: Uuid.nullable(),
  confirmedAt: z.string().nullable(),
  isDemo: z.boolean(),
  createdAt: z.string(),
  version: z.number().int(),
});

export const ChecklistItemDto = z.object({
  id: Uuid,
  eventId: Uuid,
  code: z.string().nullable(),
  title: z.string(),
  responsibleParty: z.string().nullable(),
  ownerUserId: Uuid.nullable(),
  dueDate: z.string().nullable(),
  decisionId: Uuid.nullable(),
  status: z.enum(CLOSING_DELIVERABLE_STATUSES),
  documentId: Uuid.nullable(),
  executedVersionId: Uuid.nullable(),
  deliveredBy: Uuid.nullable(),
  deliveredAt: z.string().nullable(),
  verifiedBy: Uuid.nullable(),
  verifiedAt: z.string().nullable(),
  statusNote: z.string().nullable(),
  evidence: Evidence,
  isDemo: z.boolean(),
  version: z.number().int(),
});

export const ConditionDto = z.object({
  id: Uuid,
  closingId: Uuid.nullable(),
  reference: z.string(),
  kind: z.enum(CONDITION_KINDS),
  title: z.string(),
  description: z.string().nullable(),
  ownerUserId: Uuid.nullable(),
  parties: z.string().nullable(),
  blocking: z.boolean(),
  waivable: z.boolean(),
  waiverAuthorityRole: Role.nullable(),
  waivabilityBasis: z.string().nullable(),
  waivabilityDeterminedBy: Uuid.nullable(),
  validTo: z.string().nullable(),
  longStopDate: z.string().nullable(),
  /** DOM-P4-04 (G6-C03): the approved extension of the long-stop date, when one was recorded. */
  longStopExtensionDecisionId: Uuid.nullable(),
  longStopExtendedBy: Uuid.nullable(),
  longStopExtendedAt: z.string().nullable(),
  status: z.enum(CONDITION_STATUSES),
  evidenceSubmittedBy: Uuid.nullable(),
  verifiedBy: Uuid.nullable(),
  verifiedAt: z.string().nullable(),
  statusNote: z.string().nullable(),
  waiverId: Uuid.nullable(),
  /** The waiver is approved and unexpired (a bare "waived" status never clears a blocker). */
  waiverEffective: z.boolean(),
  gateKey: z.string().nullable(),
  evidence: Evidence,
  allowedCommands: z.array(z.string()),
  isDemo: z.boolean(),
  updatedAt: z.string(),
  version: z.number().int(),
});

export const FundsFlowDto = z.object({
  id: Uuid,
  closingId: Uuid,
  code: z.string().nullable(),
  description: z.string(),
  payer: z.string(),
  payee: z.string(),
  amount: MoneySchema.nullable(),
  valueDate: z.string().nullable(),
  status: z.enum(FUNDS_FLOW_STATUSES),
  confirmedBy: Uuid.nullable(),
  confirmedAt: z.string().nullable(),
  settlementReference: z.string().nullable(),
  settlementReportedBy: Uuid.nullable(),
  settlementReportedAt: z.string().nullable(),
  statusNote: z.string().nullable(),
  isDemo: z.boolean(),
  version: z.number().int(),
});

export const EventDetailDto = EventDto.extend({
  description: z.string().nullable(),
  executedDocumentId: Uuid.nullable(),
  confirmationDecisionId: Uuid.nullable(),
  confirmationAuthority: z.string().nullable(),
  confirmationRequest: ApprovalStep.nullable(),
  /** The decision linked to the pending confirmation — null when none or the caller cannot read it. */
  decision: LinkedDecisionSummaryDto.nullable(),
  statusReason: z.string().nullable(),
  allowedCommands: z.array(z.string()),
  /**
   * For a signing: gate G5 (JV Signing Readiness) — the signing is requested and recorded only while its current cycle is
   * approved and not flagged for reassessment, on the decision that approved it (DOM-P4-02). Null for a closing.
   */
  signingGate: z
    .object({
      gateKey: z.string(),
      assessmentId: Uuid.nullable(),
      status: z.enum(GATE_ASSESSMENT_STATUSES).nullable(),
      underReassessment: z.boolean(),
      passed: z.boolean(),
    })
    .nullable(),
  /** Live server evaluation — the same rule the confirm command enforces inside its transaction. */
  blockers: z.array(EventBlockerDto),
  ready: z.boolean(),
  /** This event's checklist (a signing's and a closing's checklists are separate). */
  checklist: z.array(ChecklistItemDto),
  /** Conditions precedent of a closing (always empty for a signing). */
  conditions: z.array(ConditionDto),
  fundsFlows: z.array(FundsFlowDto),
  /** For a signing: the closings that follow it (each with its own CP set). */
  closings: z.array(z.object({ id: Uuid, code: z.string().nullable(), status: z.enum(CLOSING_STATUSES) })),
  people: People,
});

export const ObligationDto = z.object({
  id: Uuid,
  code: z.string(),
  kind: z.enum(POST_CLOSE_KINDS),
  title: z.string(),
  description: z.string().nullable(),
  responsibleParty: z.string().nullable(),
  ownerUserId: Uuid.nullable(),
  dueDate: z.string().nullable(),
  status: z.enum(POST_CLOSE_STATUSES),
  overdue: z.boolean(),
  daysOverdue: z.number().int(),
  overdueSince: z.string().nullable(),
  escalationId: Uuid.nullable(),
  completionReportedBy: Uuid.nullable(),
  verifiedBy: Uuid.nullable(),
  verifiedAt: z.string().nullable(),
  closingId: Uuid.nullable(),
  statusNote: z.string().nullable(),
  evidence: Evidence,
  allowedCommands: z.array(z.string()),
  isDemo: z.boolean(),
  updatedAt: z.string(),
  version: z.number().int(),
});

export const ProgramClosureDto = z.object({
  closure: z
    .object({
      id: Uuid,
      status: z.enum(PROGRAM_CLOSURE_STATUSES),
      handoverNote: z.string(),
      requestedBy: Uuid,
      requestedAt: z.string(),
      confirmedBy: Uuid.nullable(),
      confirmedAt: z.string().nullable(),
      statusNote: z.string().nullable(),
      version: z.number().int(),
    })
    .nullable(),
  g7: z.object({
    assessmentId: Uuid.nullable(),
    status: z.enum(GATE_ASSESSMENT_STATUSES).nullable(),
    /** The G7 approval is flagged for controlled reassessment: it no longer counts (DOM-P4-11). */
    underReassessment: z.boolean(),
  }),
  /** Program closure is allowed only after G7 passes (REQ-JV-019) and while that approval is not under reassessment. */
  g7Passed: z.boolean(),
});

const WaiverDto = z.object({
  id: Uuid,
  conditionId: Uuid,
  basis: z.string(),
  impact: z.string(),
  conditions: z.string().nullable(),
  expiresOn: z.string().nullable(),
  status: z.string(),
  authorityRole: Role.nullable(),
  requestedBy: Uuid,
  decidedBy: Uuid.nullable(),
  decidedAt: z.string().nullable(),
  version: z.number().int(),
});

// ---------------------------------------------------------------------------------------------------------------
// Bodies

const CreatePartnerBody = z.object({
  code: z.string().trim().regex(/^[A-Z0-9][A-Z0-9-]{1,31}$/, 'Upper-case code').optional(),
  name: RequiredText(200),
  description: Text(4000).optional(),
  legalEntityId: Uuid.optional(),
  classification: ClassificationSchema.default('confidential'),
});
const UpdatePartnerBody = z.object({ expectedVersion: ExpectedVersion, name: RequiredText(200).optional(), description: Text(4000).nullable().optional(), legalEntityId: Uuid.nullable().optional() });
const EventCommandNames = ['start_preparation', 'mark_ready', 'back_to_preparation', 'abort'] as const;

export const jvRoutes = registerRoutes({
  // ---------------------------------------------------------------- partners
  listPartners: defineRoute({
    id: 'jv.listPartners',
    method: 'GET',
    path: `${P}/partners`,
    summary: 'Partner longlist / shortlist (no real default names; bootstrap has none)',
    tags,
    access: 'jv.partner.read',
    params: ProjectParams,
    query: PageQuery.extend({ stage: Stage.optional(), shortlisted: z.enum(['true', 'false']).optional(), sort: SortParam(['code', 'name', 'stage', 'updatedAt']) }),
    response: paged(PartnerDto),
  }),
  getPartner: defineRoute({ id: 'jv.getPartner', method: 'GET', path: `${P}/partners/:partnerId`, summary: 'Partner detail: stage, outreach approval, NDA, conflicts, contacts', tags, access: 'jv.partner.read', params: PartnerParams, response: PartnerDetailDto }),
  createPartner: defineRoute({ id: 'jv.createPartner', method: 'POST', path: `${P}/partners`, summary: 'Add a partner to the longlist (stage Identified)', tags, access: 'jv.partner.manage', params: ProjectParams, body: CreatePartnerBody, response: CreatedResult }),
  updatePartner: defineRoute({ id: 'jv.updatePartner', method: 'PATCH', path: `${P}/partners/:partnerId`, summary: 'Edit descriptive partner fields (never the stage)', tags, access: 'jv.partner.manage', params: PartnerParams, body: UpdatePartnerBody, response: VersionResult }),
  shortlistPartner: defineRoute({
    id: 'jv.shortlistPartner',
    method: 'POST',
    path: `${P}/partners/:partnerId/shortlist`,
    summary: 'Move a partner onto / off the shortlist (documented reason)',
    tags,
    access: 'jv.partner.manage',
    command: true,
    params: PartnerParams,
    body: z.object({ expectedVersion: ExpectedVersion, shortlisted: z.boolean(), reason: RequiredText(2000) }),
    response: VersionResult,
  }),
  requestOutreach: defineRoute({
    id: 'jv.requestOutreach',
    method: 'POST',
    path: `${P}/partners/:partnerId/outreach-request`,
    summary: 'Request approval to contact the partner (outreach approval is separate from NDA and materials access)',
    tags,
    access: 'jv.partner.manage',
    command: true,
    params: PartnerParams,
    body: z.object({ expectedVersion: ExpectedVersion, note: RequiredText(4000) }),
    response: VersionResult,
  }),
  decideOutreach: defineRoute({
    id: 'jv.decideOutreach',
    method: 'POST',
    path: `${P}/partners/:partnerId/outreach-approval`,
    summary: 'Approve / reject the outreach request (authorized role, not the requester nor a conflicted person, within the authority matrix)',
    tags,
    access: 'jv.partner.approve_contact',
    command: true,
    params: PartnerParams,
    body: z.object({ expectedVersion: ExpectedVersion, outcome: z.enum(['approve', 'reject']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, stage: Stage, version: z.number().int() }),
  }),
  submitNda: defineRoute({
    id: 'jv.submitNda',
    method: 'POST',
    path: `${P}/partners/:partnerId/nda`,
    summary: 'Submit the executed NDA (document + execution date) for recording by Legal — requires outreach approval',
    tags,
    access: 'jv.partner.advance_stage',
    command: true,
    params: PartnerParams,
    body: z.object({ expectedVersion: ExpectedVersion, documentId: Uuid, executedOn: IsoDate, note: Text(4000).optional() }),
    response: VersionResult,
  }),
  recordNda: defineRoute({
    id: 'jv.recordNda',
    method: 'POST',
    path: `${P}/partners/:partnerId/nda/record`,
    summary: 'Record the NDA as executed (Legal; not the submitter). Grants NO document access',
    tags,
    access: 'jv.nda.record',
    command: true,
    params: PartnerParams,
    body: z.object({ expectedVersion: ExpectedVersion, outcome: z.enum(['record', 'reject']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, stage: Stage, version: z.number().int() }),
  }),
  advancePartner: defineRoute({
    id: 'jv.advancePartner',
    method: 'POST',
    path: `${P}/partners/:partnerId/advance`,
    summary: 'Move to the next engagement stage (skipped stages rejected; approval stages need their own command)',
    tags,
    access: 'jv.partner.advance_stage',
    command: true,
    params: PartnerParams,
    body: z.object({ expectedVersion: ExpectedVersion, toStage: Stage, note: Text(4000).optional() }),
    response: z.object({ id: Uuid, stage: Stage, version: z.number().int() }),
  }),
  withdrawPartner: defineRoute({
    id: 'jv.withdrawPartner',
    method: 'POST',
    path: `${P}/partners/:partnerId/withdraw`,
    summary: "Withdraw the partner (its external room grants are revoked; history kept)",
    tags,
    access: 'jv.partner.advance_stage',
    command: true,
    params: PartnerParams,
    body: CmdWithReason,
    response: z.object({ id: Uuid, stage: Stage, version: z.number().int(), grantsRevoked: z.number().int() }),
  }),
  addPartnerConflict: defineRoute({
    id: 'jv.addPartnerConflict',
    method: 'POST',
    path: `${P}/partners/:partnerId/conflicts`,
    summary: 'Record a conflict disclosure (a conflicted person cannot approve this partner’s outreach / NDA)',
    tags,
    access: 'jv.partner.manage',
    params: PartnerParams,
    body: z.object({ declarantUserId: Uuid.optional(), description: RequiredText(4000), mitigation: Text(4000).optional() }),
    response: VersionResult,
  }),
  addPartnerContact: defineRoute({
    id: 'jv.addPartnerContact',
    method: 'POST',
    path: `${P}/partners/:partnerId/contacts`,
    summary: 'Bind an EXTERNAL account to this counterparty (exactly one per project)',
    tags,
    access: 'jv.room.grant_access',
    params: PartnerParams,
    body: z.object({ userId: Uuid, note: Text(1000).optional() }),
    response: z.object({ id: Uuid }),
  }),
  revokePartnerContact: defineRoute({
    id: 'jv.revokePartnerContact',
    method: 'POST',
    path: `${P}/partners/:partnerId/contacts/:contactId/revoke`,
    summary: 'Unbind an external account (its grants in this partner’s rooms are revoked)',
    tags,
    access: 'jv.room.grant_access',
    command: true,
    params: PartnerParams.extend({ contactId: Uuid }),
    body: z.object({ reason: RequiredText(2000) }),
    response: z.object({ id: Uuid, grantsRevoked: z.number().int() }),
  }),
  getCriteria: defineRoute({ id: 'jv.getCriteria', method: 'GET', path: `${P}/partner-criteria`, summary: 'Screening criteria and weights (null until defined)', tags, access: 'jv.partner.read', params: ProjectParams, response: z.object({ criteriaSet: CriteriaSetDto.nullable() }) }),
  setCriteria: defineRoute({
    id: 'jv.setCriteria',
    method: 'PUT',
    path: `${P}/partner-criteria`,
    summary: 'Define / replace the screening criteria (weights must sum to exactly 100). expectedVersion 0 creates',
    tags,
    access: 'jv.partner.manage',
    params: ProjectParams,
    body: z.object({
      expectedVersion: z.number().int().min(0),
      criteria: z.array(z.object({ key: z.string().trim().min(1).max(32), name: RequiredText(200), nameAr: Text(200).nullable().optional(), weight: Weight })).min(1).max(30),
      note: Text(2000).optional(),
    }),
    response: VersionResult,
  }),
  listAssessments: defineRoute({
    id: 'jv.listAssessments',
    method: 'GET',
    path: `${P}/partners/:partnerId/assessments`,
    summary: 'Assessment entries (each tagged fact or judgement), newest first',
    tags,
    access: 'jv.deal.read',
    params: PartnerParams,
    response: z.object({ items: z.array(AssessmentEntryDto), people: People }),
  }),
  addAssessment: defineRoute({
    id: 'jv.addAssessment',
    method: 'POST',
    path: `${P}/partners/:partnerId/assessments`,
    summary: 'Add an assessment entry — basis fact (with its source) or judgement is mandatory',
    tags,
    access: 'jv.proposal.manage',
    params: PartnerParams,
    body: z.object({
      basis: z.string().trim().max(16).optional(),
      statement: RequiredText(4000),
      criterionKey: z.string().trim().max(32).optional(),
      score: Score.optional(),
      proposalId: Uuid.optional(),
      sourceReference: Text(1000).optional(),
      documentId: Uuid.optional(),
    }),
    response: z.object({ id: Uuid }),
  }),
  listProposals: defineRoute({ id: 'jv.listProposals', method: 'GET', path: `${P}/partners/:partnerId/proposals`, summary: 'Proposals received from the partner', tags, access: 'jv.deal.read', params: PartnerParams, response: z.object({ items: z.array(ProposalDto) }) }),
  addProposal: defineRoute({
    id: 'jv.addProposal',
    method: 'POST',
    path: `${P}/partners/:partnerId/proposals`,
    summary: 'Record a proposal (scope, terms summary, source document) — no terms are invented',
    tags,
    access: 'jv.proposal.manage',
    params: PartnerParams,
    body: z.object({
      title: RequiredText(300),
      receivedOn: IsoDate.optional(),
      scope: Text(8000).optional(),
      termsSummary: Text(8000).optional(),
      documentId: Uuid.optional(),
      supersedesProposalId: Uuid.optional(),
      classification: ClassificationSchema.default('confidential'),
    }),
    response: CreatedResult,
  }),
  comparePartners: defineRoute({ id: 'jv.comparePartners', method: 'GET', path: `${P}/partner-comparison`, summary: 'Comparative assessment: weighted scores (only when complete) and fact / judgement counts', tags, access: 'jv.deal.read', params: ProjectParams, response: PartnerComparisonDto }),

  // ---------------------------------------------------------------- deal scenarios & negotiation
  listScenarios: defineRoute({
    id: 'jv.listScenarios',
    method: 'GET',
    path: `${P}/deal-scenarios`,
    summary: 'Ownership / contribution / governance scenarios (no default percentages)',
    tags,
    access: 'jv.deal.read',
    params: ProjectParams,
    query: PageQuery.extend({ partnerId: Uuid.optional(), sort: SortParam(['code', 'name', 'updatedAt']) }),
    response: paged(DealScenarioDto),
  }),
  getScenario: defineRoute({ id: 'jv.getScenario', method: 'GET', path: `${P}/deal-scenarios/:scenarioId`, summary: 'Scenario with its immutable version history', tags, access: 'jv.deal.read', params: idP('scenarioId'), response: DealScenarioDetailDto }),
  createScenario: defineRoute({
    id: 'jv.createScenario',
    method: 'POST',
    path: `${P}/deal-scenarios`,
    summary: 'Create a scenario (version 1). Percentages are entered by people or left TBD — never defaulted',
    tags,
    access: 'jv.scenario.manage',
    params: ProjectParams,
    body: z.object({
      name: RequiredText(200),
      partnerId: Uuid.optional(),
      versionLabel: Text(32).optional(),
      ownership: z.array(OwnershipLine).max(20).default([]),
      contributions: z.array(ContributionLine).max(50).default([]),
      governanceTerms: Text(8000).optional(),
      assumptions: Text(8000).optional(),
      classification: ClassificationSchema.default('confidential'),
    }),
    response: CreatedResult,
  }),
  addScenarioVersion: defineRoute({
    id: 'jv.addScenarioVersion',
    method: 'POST',
    path: `${P}/deal-scenarios/:scenarioId/versions`,
    summary: 'Add a new immutable version of the scenario (previous versions are preserved)',
    tags,
    access: 'jv.scenario.manage',
    command: true,
    params: idP('scenarioId'),
    body: z.object({
      expectedVersion: ExpectedVersion,
      versionLabel: Text(32).optional(),
      ownership: z.array(OwnershipLine).max(20),
      contributions: z.array(ContributionLine).max(50),
      governanceTerms: Text(8000).nullable().optional(),
      assumptions: Text(8000).nullable().optional(),
      changeNote: RequiredText(2000),
    }),
    response: z.object({ id: Uuid, versionNo: z.number().int(), version: z.number().int() }),
  }),
  listNegotiationIssues: defineRoute({
    id: 'jv.listNegotiationIssues',
    method: 'GET',
    path: `${P}/negotiation-issues`,
    summary: 'Terms & negotiation issues register',
    tags,
    access: 'jv.deal.read',
    params: ProjectParams,
    query: PageQuery.extend({ status: z.enum(NEGOTIATION_ISSUE_STATUSES).optional(), partnerId: Uuid.optional(), sort: SortParam(['code', 'status', 'updatedAt']) }),
    response: paged(NegotiationIssueDto),
  }),
  createNegotiationIssue: defineRoute({
    id: 'jv.createNegotiationIssue',
    method: 'POST',
    path: `${P}/negotiation-issues`,
    summary: 'Record an issue with the parties’ positions; an issue that requires approval must link its decision',
    tags,
    access: 'jv.negotiation.manage',
    params: ProjectParams,
    body: z.object({
      issue: RequiredText(4000),
      partnerId: Uuid.optional(),
      agreementId: Uuid.optional(),
      positions: z.array(Position).max(10).default([]),
      alternatives: Text(4000).optional(),
      requiredApproval: Text(1000).optional(),
      requiresApproval: z.boolean().default(false),
      decisionId: Uuid.optional(),
      documentId: Uuid.optional(),
      documentRef: Text(500).optional(),
      classification: ClassificationSchema.default('confidential'),
    }),
    response: CreatedResult,
  }),
  updateNegotiationIssue: defineRoute({
    id: 'jv.updateNegotiationIssue',
    method: 'PATCH',
    path: `${P}/negotiation-issues/:issueId`,
    summary: 'Edit positions, alternatives, approval link and document (never the status)',
    tags,
    access: 'jv.negotiation.manage',
    params: idP('issueId'),
    body: z.object({
      expectedVersion: ExpectedVersion,
      issue: RequiredText(4000).optional(),
      positions: z.array(Position).max(10).optional(),
      alternatives: Text(4000).nullable().optional(),
      requiredApproval: Text(1000).nullable().optional(),
      requiresApproval: z.boolean().optional(),
      decisionId: Uuid.nullable().optional(),
      documentId: Uuid.nullable().optional(),
      documentRef: Text(500).nullable().optional(),
      resolution: Text(4000).nullable().optional(),
    }),
    response: VersionResult,
  }),
  transitionNegotiationIssue: defineRoute({
    id: 'jv.transitionNegotiationIssue',
    method: 'POST',
    path: `${P}/negotiation-issues/:issueId/transition`,
    summary: 'Negotiation issue lifecycle command (agree/close need the linked decision’s FINAL approval when required)',
    tags,
    access: 'jv.negotiation.manage',
    command: true,
    params: idP('issueId'),
    body: z.object({ expectedVersion: ExpectedVersion, command: z.enum(['propose_resolution', 'agree', 'escalate', 'close', 'reopen']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(NEGOTIATION_ISSUE_STATUSES), version: z.number().int() }),
  }),

  // ---------------------------------------------------------------- rooms, grants, index, disclosures
  listRooms: defineRoute({
    id: 'jv.listRooms',
    method: 'GET',
    path: `${P}/partner-rooms`,
    summary: 'Rooms: those the caller is granted (openable) and, for room administrators, the metadata of the others',
    tags,
    access: 'jv.room.read',
    params: ProjectParams,
    query: PageQuery.extend({ type: z.enum(ROOM_TYPES).optional(), sort: SortParam(['name', 'createdAt']) }),
    response: paged(RoomDto),
  }),
  getRoom: defineRoute({ id: 'jv.getRoom', method: 'GET', path: `${P}/partner-rooms/:roomId`, summary: 'Open a room (grant required — audited read)', tags, access: 'jv.room.read', params: RoomParams, response: RoomDetailDto }),
  createRoom: defineRoute({
    id: 'jv.createRoom',
    method: 'POST',
    path: `${P}/partner-rooms`,
    summary: 'Create a partner / internal / clean-team room (the creator of a non-clean-team room receives a manage grant)',
    tags,
    access: 'jv.room.manage',
    params: ProjectParams,
    body: z.object({ name: RequiredText(200), type: z.enum(ROOM_TYPES), partnerId: Uuid.optional(), description: Text(2000).optional(), classification: ClassificationSchema.default('confidential') }),
    response: z.object({ id: Uuid, version: z.number().int(), creatorGrantId: Uuid.nullable() }),
  }),
  updateRoom: defineRoute({
    id: 'jv.updateRoom',
    method: 'PATCH',
    path: `${P}/partner-rooms/:roomId`,
    summary: 'Edit the room name / description',
    tags,
    access: 'jv.room.manage',
    params: RoomParams,
    body: z.object({ expectedVersion: ExpectedVersion, name: RequiredText(200).optional(), description: Text(2000).nullable().optional() }),
    response: VersionResult,
  }),
  lockRoom: defineRoute({ id: 'jv.lockRoom', method: 'POST', path: `${P}/partner-rooms/:roomId/lock`, summary: 'Lock the room: every grant and download is suspended immediately (containment)', tags, access: 'jv.room.lock', command: true, params: RoomParams, body: CmdWithReason, response: VersionResult }),
  unlockRoom: defineRoute({ id: 'jv.unlockRoom', method: 'POST', path: `${P}/partner-rooms/:roomId/unlock`, summary: 'Unlock the room (grants that are still valid apply again)', tags, access: 'jv.room.lock', command: true, params: RoomParams, body: CmdWithReason, response: VersionResult }),
  listRoomGrants: defineRoute({
    id: 'jv.listRoomGrants',
    method: 'GET',
    path: `${P}/partner-rooms/:roomId/access-grants`,
    summary: 'Grants of the room, including revoked and expired ones (history is retained)',
    tags,
    access: 'jv.room.revoke_access',
    params: RoomParams,
    response: z.object({ items: z.array(RoomGrantDto) }),
  }),
  grantRoomAccess: defineRoute({
    id: 'jv.grantRoomAccess',
    method: 'POST',
    path: `${P}/partner-rooms/:roomId/access-grants`,
    summary: 'Grant room access. An NDA alone never grants access: external grants need Materials access, the counterparty binding and an expiry',
    tags,
    access: 'jv.room.grant_access',
    params: RoomParams,
    body: z.object({
      userId: Uuid,
      accessLevel: z.enum(ROOM_ACCESS_LEVELS).default('read'),
      role: z.enum(['clean_team', 'external_partner_limited']).nullable().default(null),
      expiresAt: IsoInstant.optional(),
      reason: RequiredText(2000),
      attestationRef: Text(500).optional(),
    }),
    response: z.object({ id: Uuid }),
  }),
  revokeRoomAccess: defineRoute({
    id: 'jv.revokeRoomAccess',
    method: 'POST',
    path: `${P}/partner-rooms/:roomId/access-grants/:grantId/revoke`,
    summary: 'Revoke a grant — effective immediately (downloads included); the grant and its history are kept',
    tags,
    access: 'jv.room.revoke_access',
    command: true,
    params: RoomParams.extend({ grantId: Uuid }),
    body: z.object({ reason: RequiredText(2000) }),
    response: z.object({ id: Uuid, revokedAt: z.string() }),
  }),
  getRoomIndex: defineRoute({
    id: 'jv.getRoomIndex',
    method: 'GET',
    path: `${P}/partner-rooms/:roomId/index`,
    summary: 'VDR index: documents filed in the room with their disclosure state (fixed order: title, then id)',
    tags,
    access: 'jv.room.read',
    params: RoomParams,
    query: PageQuery,
    response: paged(RoomIndexItemDto),
  }),
  listDisclosures: defineRoute({
    id: 'jv.listDisclosures',
    method: 'GET',
    path: `${P}/partner-rooms/:roomId/disclosures`,
    summary: 'Disclosure history of the room, newest request first (requested, released, rejected, revoked)',
    tags,
    access: 'jv.disclosure_log.read',
    params: RoomParams,
    query: PageQuery.extend({ status: z.enum(DISCLOSURE_STATUSES).optional() }),
    response: paged(DisclosureDto),
  }),
  requestDisclosure: defineRoute({
    id: 'jv.requestDisclosure',
    method: 'POST',
    path: `${P}/partner-rooms/:roomId/disclosures`,
    summary: 'Request release of a specific document version into the partner room',
    tags,
    access: 'jv.room.manage',
    params: RoomParams,
    body: z.object({ documentId: Uuid, documentVersionId: Uuid.optional(), note: Text(2000).optional() }),
    response: z.object({ id: Uuid, version: z.number().int() }),
  }),
  releaseDisclosure: defineRoute({
    id: 'jv.releaseDisclosure',
    method: 'POST',
    path: `${P}/partner-rooms/:roomId/disclosures/:disclosureId/release`,
    summary: 'Approve the release (not the requester or uploader) — the version becomes visible to the counterparty',
    tags,
    access: 'jv.disclosure.release',
    command: true,
    params: RoomParams.extend({ disclosureId: Uuid }),
    body: z.object({ expectedVersion: ExpectedVersion, outcome: z.enum(['release', 'reject']), note: Text(2000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(DISCLOSURE_STATUSES), version: z.number().int() }),
  }),
  revokeDisclosure: defineRoute({
    id: 'jv.revokeDisclosure',
    method: 'POST',
    path: `${P}/partner-rooms/:roomId/disclosures/:disclosureId/revoke`,
    summary: 'Withdraw a released item (copies already downloaded cannot be recalled — the history shows who downloaded)',
    tags,
    access: 'jv.disclosure.revoke',
    command: true,
    params: RoomParams.extend({ disclosureId: Uuid }),
    body: CmdWithReason,
    response: z.object({ id: Uuid, status: z.enum(DISCLOSURE_STATUSES), version: z.number().int() }),
  }),
  listRoomAccessLog: defineRoute({
    id: 'jv.listRoomAccessLog',
    method: 'GET',
    path: `${P}/partner-rooms/:roomId/access-log`,
    summary: 'Append-only access & disclosure history (grants, revocations, releases, downloads, locks)',
    tags,
    access: 'jv.disclosure_log.read',
    params: RoomParams,
    query: PageQuery.extend({ kind: z.enum(ROOM_ACCESS_EVENT_KINDS).optional() }),
    response: paged(RoomAccessEventDto).extend({ people: People }),
  }),

  // ---------------------------------------------------------------- external (counterparty) projection
  // The three counterparty LISTS are session-level at the route (the guard still enforces the project scope → 404) so that
  // query validation answers every caller alike; the service asserts the external permission (`jv.disclosure.view` /
  // `jv.dd_request.read_external`, held by external_partner_limited only) with the room conditions — 403 / 404 otherwise.
  listExternalRooms: defineRoute({
    id: 'jv.listExternalRooms',
    method: 'GET',
    path: `${P}/partner-access/rooms`,
    summary: 'Counterparty view: the rooms the external account is granted (service-enforced permission jv.disclosure.view)',
    tags,
    access: 'authenticated',
    params: ProjectParams,
    response: z.object({ items: z.array(ExternalRoomDto) }),
  }),
  listExternalDisclosures: defineRoute({
    id: 'jv.listExternalDisclosures',
    method: 'GET',
    path: `${P}/partner-access/rooms/:roomId/disclosures`,
    summary: 'Counterparty view: items released into its room (disclosed version only — audited; service-enforced permission jv.disclosure.view)',
    tags,
    access: 'authenticated',
    params: RoomParams,
    response: z.object({ items: z.array(ExternalDisclosureDto) }),
  }),
  downloadExternalDisclosure: defineRoute({
    id: 'jv.downloadExternalDisclosure',
    method: 'GET',
    path: `${P}/partner-access/rooms/:roomId/disclosures/:disclosureId/download`,
    summary: 'Counterparty download of a released version (audited; refused after revocation or room lock)',
    tags,
    access: 'jv.disclosure.download',
    binary: true,
    params: RoomParams.extend({ disclosureId: Uuid }),
    response: z.any(),
  }),
  listExternalDdRequests: defineRoute({
    id: 'jv.listExternalDdRequests',
    method: 'GET',
    path: `${P}/partner-access/rooms/:roomId/dd-requests`,
    summary: 'Counterparty view of its DD requests (question, status, due date, RELEASED answer only; service-enforced permission jv.dd_request.read_external)',
    tags,
    access: 'authenticated',
    params: RoomParams,
    response: z.object({ items: z.array(ExternalDdRequestDto) }),
  }),
  createExternalDdRequest: defineRoute({
    id: 'jv.createExternalDdRequest',
    method: 'POST',
    path: `${P}/partner-access/rooms/:roomId/dd-requests`,
    summary: 'Counterparty raises a DD question in its own room',
    tags,
    access: 'jv.dd_request.create',
    params: RoomParams,
    body: z.object({ question: RequiredText(4000), domain: z.enum(DD_DOMAINS) }),
    response: z.object({ id: Uuid, number: z.number().int() }),
  }),

  // ---------------------------------------------------------------- DD requests / Q&A
  listDdRequests: defineRoute({
    id: 'jv.listDdRequests',
    method: 'GET',
    path: `${P}/diligence-requests`,
    summary: 'DD requests of the rooms the caller is granted (internal projection)',
    tags,
    access: 'jv.dd_request.read',
    params: ProjectParams,
    query: PageQuery.extend({ roomId: Uuid.optional(), releaseStatus: z.enum(DD_RELEASE_STATUSES).optional(), sort: SortParam(['number', 'dueDate', 'createdAt']) }),
    response: paged(DdRequestDto).extend({ people: People }),
  }),
  getDdRequest: defineRoute({ id: 'jv.getDdRequest', method: 'GET', path: `${P}/diligence-requests/:requestId`, summary: 'DD request with the answer workflow', tags, access: 'jv.dd_request.read', params: idP('requestId'), response: DdRequestDetailDto }),
  createDdRequest: defineRoute({
    id: 'jv.createDdRequest',
    method: 'POST',
    path: `${P}/diligence-requests`,
    summary: 'Raise a DD request in a room (contribute grant required)',
    tags,
    access: 'jv.dd_request.create',
    params: ProjectParams,
    body: z.object({ roomId: Uuid, question: RequiredText(4000), domain: z.enum(DD_DOMAINS), requesterLabel: Text(200).optional(), dueDate: IsoDate.optional(), classification: ClassificationSchema.default('confidential') }),
    response: z.object({ id: Uuid, number: z.number().int() }),
  }),
  assignDdRequest: defineRoute({
    id: 'jv.assignDdRequest',
    method: 'POST',
    path: `${P}/diligence-requests/:requestId/assign`,
    summary: 'Assign the answer owner and the reviewer (different people) and the due date',
    tags,
    access: 'jv.dd_request.assign',
    command: true,
    params: idP('requestId'),
    body: z.object({ expectedVersion: ExpectedVersion, assigneeUserId: Uuid, reviewerUserId: Uuid.optional(), dueDate: IsoDate.nullable().optional() }),
    response: VersionResult,
  }),
  draftDdAnswer: defineRoute({
    id: 'jv.draftDdAnswer',
    method: 'POST',
    path: `${P}/diligence-requests/:requestId/answer`,
    summary: 'Save the answer draft and its evidence documents (documents must be in the same room)',
    tags,
    access: 'jv.dd_answer.draft',
    command: true,
    params: idP('requestId'),
    body: z.object({ expectedVersion: ExpectedVersion, answerDraft: RequiredText(20000), evidenceDocumentIds: z.array(Uuid).max(20).default([]) }),
    response: VersionResult,
  }),
  submitDdAnswer: defineRoute({ id: 'jv.submitDdAnswer', method: 'POST', path: `${P}/diligence-requests/:requestId/submit-for-review`, summary: 'Submit the drafted answer for review', tags, access: 'jv.dd_answer.draft', command: true, params: idP('requestId'), body: Cmd, response: VersionResult }),
  reviewDdAnswer: defineRoute({
    id: 'jv.reviewDdAnswer',
    method: 'POST',
    path: `${P}/diligence-requests/:requestId/review`,
    summary: 'Review the answer (not the drafter): approve for release, return to draft, or withhold',
    tags,
    access: 'jv.dd_answer.review',
    command: true,
    params: idP('requestId'),
    body: z.object({ expectedVersion: ExpectedVersion, outcome: z.enum(['approve', 'return', 'withhold']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, releaseStatus: z.enum(DD_RELEASE_STATUSES), version: z.number().int() }),
  }),
  releaseDdAnswer: defineRoute({
    id: 'jv.releaseDdAnswer',
    method: 'POST',
    path: `${P}/diligence-requests/:requestId/release`,
    summary: 'Release the approved answer to the partner room (release without approval is rejected); evidence documents are disclosed with it',
    tags,
    access: 'jv.disclosure.release',
    command: true,
    params: idP('requestId'),
    body: Cmd,
    response: z.object({ id: Uuid, releaseStatus: z.enum(DD_RELEASE_STATUSES), version: z.number().int(), disclosures: z.number().int() }),
  }),

  // ---------------------------------------------------------------- findings
  listFindings: defineRoute({
    id: 'jv.listFindings',
    method: 'GET',
    path: `${P}/diligence-findings`,
    summary: 'DD findings (a room’s findings are visible to that room’s members only)',
    tags,
    access: 'jv.dd_request.read',
    params: ProjectParams,
    query: PageQuery.extend({ materiality: z.enum(MATERIALITY).optional(), status: z.enum(FINDING_STATUSES).optional(), roomId: Uuid.optional(), sort: SortParam(['code', 'materiality', 'status', 'updatedAt']) }),
    response: paged(FindingDto),
  }),
  getFinding: defineRoute({ id: 'jv.getFinding', method: 'GET', path: `${P}/diligence-findings/:findingId`, summary: 'DD finding', tags, access: 'jv.dd_request.read', params: idP('findingId'), response: FindingDto }),
  createFinding: defineRoute({
    id: 'jv.createFinding',
    method: 'POST',
    path: `${P}/diligence-findings`,
    summary: 'Record a finding (from a DD request or in a room); a material finding requires a remediation owner and plan',
    tags,
    access: 'jv.finding.manage',
    params: ProjectParams,
    body: z.object({
      title: RequiredText(300),
      description: Text(8000).optional(),
      materiality: z.enum(MATERIALITY),
      diligenceRequestId: Uuid.optional(),
      roomId: Uuid.optional(),
      partnerId: Uuid.optional(),
      riskId: Uuid.optional(),
      remediation: Text(4000).optional(),
      remediationOwnerUserId: Uuid.optional(),
      remediationDueDate: IsoDate.optional(),
      valuationImplication: Text(4000).optional(),
      documentImplication: Text(4000).optional(),
      cpImplication: Text(4000).optional(),
      conditionId: Uuid.optional(),
      classification: ClassificationSchema.default('confidential'),
    }),
    response: CreatedResult,
  }),
  updateFinding: defineRoute({
    id: 'jv.updateFinding',
    method: 'PATCH',
    path: `${P}/diligence-findings/:findingId`,
    summary: 'Edit finding details, materiality and remediation (never the status)',
    tags,
    access: 'jv.finding.manage',
    params: idP('findingId'),
    body: z.object({
      expectedVersion: ExpectedVersion,
      title: RequiredText(300).optional(),
      description: Text(8000).nullable().optional(),
      materiality: z.enum(MATERIALITY).optional(),
      riskId: Uuid.nullable().optional(),
      remediation: Text(4000).nullable().optional(),
      remediationOwnerUserId: Uuid.nullable().optional(),
      remediationDueDate: IsoDate.nullable().optional(),
      valuationImplication: Text(4000).nullable().optional(),
      documentImplication: Text(4000).nullable().optional(),
      cpImplication: Text(4000).nullable().optional(),
      conditionId: Uuid.nullable().optional(),
    }),
    response: VersionResult,
  }),
  transitionFinding: defineRoute({
    id: 'jv.transitionFinding',
    method: 'POST',
    path: `${P}/diligence-findings/:findingId/transition`,
    summary: 'Finding lifecycle command (remediation planned / remediated / accepted risk / closed / reopened)',
    tags,
    access: 'jv.finding.manage',
    command: true,
    params: idP('findingId'),
    body: z.object({ expectedVersion: ExpectedVersion, command: z.enum(['plan_remediation', 'mark_remediated', 'accept_risk', 'close', 'reopen']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(FINDING_STATUSES), version: z.number().int() }),
  }),

  // ---------------------------------------------------------------- signing & closing events
  listSignings: defineRoute({
    id: 'jv.listSignings',
    method: 'GET',
    path: `${P}/signings`,
    summary: 'Signing events (separate from closings)',
    tags,
    access: 'jv.deal.read',
    params: ProjectParams,
    query: PageQuery.extend({ sort: SortParam(['sequence', 'targetDate', 'status']) }),
    response: paged(EventDto),
  }),
  createSigning: defineRoute({
    id: 'jv.createSigning',
    method: 'POST',
    path: `${P}/signings`,
    summary: 'Create a signing event with its own checklist',
    tags,
    access: 'jv.closing_checklist.manage',
    params: ProjectParams,
    body: z.object({ name: RequiredText(300), partnerId: Uuid.optional(), targetDate: IsoDate.optional(), description: Text(4000).optional() }),
    response: CreatedResult,
  }),
  getSigning: defineRoute({ id: 'jv.getSigning', method: 'GET', path: `${P}/signings/:eventId`, summary: 'Signing with its checklist, blockers and the closings that follow it', tags, access: 'jv.deal.read', params: EventParams, response: EventDetailDto }),
  getSigningChecklist: defineRoute({ id: 'jv.getSigningChecklist', method: 'GET', path: `${P}/signings/:eventId/checklist`, summary: 'Signing checklist (items belong to exactly one event)', tags, access: 'jv.deal.read', params: EventParams, response: z.object({ eventId: Uuid, kind: z.enum(CLOSING_KINDS), items: z.array(ChecklistItemDto) }) }),
  listClosings: defineRoute({
    id: 'jv.listClosings',
    method: 'GET',
    path: `${P}/closings`,
    summary: 'Closing events (one transaction can have several; each has its own CPs)',
    tags,
    access: 'jv.deal.read',
    params: ProjectParams,
    query: PageQuery.extend({ signingId: Uuid.optional(), sort: SortParam(['sequence', 'targetDate', 'status']) }),
    response: paged(EventDto),
  }),
  createClosing: defineRoute({
    id: 'jv.createClosing',
    method: 'POST',
    path: `${P}/closings`,
    summary: 'Create a closing that follows a signing (its own CP set, checklist, confirmation and status)',
    tags,
    access: 'jv.closing_checklist.manage',
    params: ProjectParams,
    body: z.object({ signingId: Uuid, name: RequiredText(300), partnerId: Uuid.optional(), targetDate: IsoDate.optional(), description: Text(4000).optional() }),
    response: CreatedResult,
  }),
  getClosing: defineRoute({ id: 'jv.getClosing', method: 'GET', path: `${P}/closings/:eventId`, summary: 'Closing with CPs, checklist, funds flow and live blockers', tags, access: 'jv.deal.read', params: EventParams, response: EventDetailDto }),
  getClosingChecklist: defineRoute({ id: 'jv.getClosingChecklist', method: 'GET', path: `${P}/closings/:eventId/checklist`, summary: 'Closing checklist (items belong to exactly one event)', tags, access: 'jv.deal.read', params: EventParams, response: z.object({ eventId: Uuid, kind: z.enum(CLOSING_KINDS), items: z.array(ChecklistItemDto) }) }),
  transitionEvent: defineRoute({
    id: 'jv.transitionEvent',
    method: 'POST',
    path: `${P}/transaction-events/:eventId/transition`,
    summary: 'Signing / closing preparation commands (mark_ready is refused while blockers exist). Confirmation is separate',
    tags,
    access: 'jv.closing_checklist.manage',
    command: true,
    params: EventParams,
    body: z.object({ expectedVersion: ExpectedVersion, command: z.enum(EventCommandNames), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(CLOSING_STATUSES), version: z.number().int() }),
  }),
  requestEventConfirmation: defineRoute({
    id: 'jv.requestEventConfirmation',
    method: 'POST',
    path: `${P}/transaction-events/:eventId/request-confirmation`,
    summary: 'Request the authorized confirmation of a ready signing / closing, linking the governance decision',
    tags,
    access: 'jv.closing_checklist.manage',
    command: true,
    params: EventParams,
    body: z.object({ expectedVersion: ExpectedVersion, decisionId: Uuid, executedDocumentId: Uuid.optional(), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, version: z.number().int(), approvalRequestId: Uuid }),
  }),
  recordSigning: defineRoute({
    id: 'jv.recordSigning',
    method: 'POST',
    path: `${P}/signings/:eventId/record`,
    summary: 'Record the signing (authorized, not the requester, final approved decision, executed copy) — signing never closes the transaction',
    tags,
    access: 'jv.signing.record',
    command: true,
    params: EventParams,
    body: Cmd,
    response: z.object({ id: Uuid, status: z.enum(CLOSING_STATUSES), version: z.number().int() }),
  }),
  confirmClosing: defineRoute({
    id: 'jv.confirmClosing',
    method: 'POST',
    path: `${P}/closings/:eventId/confirm`,
    summary: 'Authorized closing confirmation — the CP set is re-evaluated inside this transaction; any unmet blocking CP rejects (and is logged)',
    tags,
    access: 'jv.closing.declare',
    command: true,
    params: EventParams,
    body: Cmd,
    response: z.object({ id: Uuid, status: z.enum(CLOSING_STATUSES), version: z.number().int() }),
  }),

  // ---------------------------------------------------------------- checklist items / deliverables
  createChecklistItem: defineRoute({
    id: 'jv.createChecklistItem',
    method: 'POST',
    path: `${P}/checklist-items`,
    summary: 'Add an item to ONE signing or closing checklist (closing deliverables included)',
    tags,
    access: 'jv.closing_checklist.manage',
    params: ProjectParams,
    body: z.object({ eventId: Uuid, title: RequiredText(300), responsibleParty: Text(200).optional(), ownerUserId: Uuid.optional(), dueDate: IsoDate.optional(), decisionId: Uuid.optional() }),
    response: CreatedResult,
  }),
  deliverChecklistItem: defineRoute({
    id: 'jv.deliverChecklistItem',
    method: 'POST',
    path: `${P}/checklist-items/:itemId/deliver`,
    summary: 'Record delivery with the executed document version',
    tags,
    access: 'jv.closing_checklist.manage',
    command: true,
    params: idP('itemId'),
    body: z.object({ expectedVersion: ExpectedVersion, documentId: Uuid, documentVersionId: Uuid.optional(), note: Text(2000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(CLOSING_DELIVERABLE_STATUSES), version: z.number().int() }),
  }),
  acceptChecklistItem: defineRoute({
    id: 'jv.acceptChecklistItem',
    method: 'POST',
    path: `${P}/checklist-items/:itemId/accept`,
    summary: 'Accept a delivered item (requires the executed document; not the owner or deliverer)',
    tags,
    access: 'jv.cp.verify',
    command: true,
    params: idP('itemId'),
    body: Cmd,
    response: z.object({ id: Uuid, status: z.enum(CLOSING_DELIVERABLE_STATUSES), version: z.number().int() }),
  }),
  setChecklistItemNotRequired: defineRoute({
    id: 'jv.setChecklistItemNotRequired',
    method: 'POST',
    path: `${P}/checklist-items/:itemId/not-required`,
    summary: 'Mark an item not required (documented reason)',
    tags,
    access: 'jv.closing_checklist.manage',
    command: true,
    params: idP('itemId'),
    body: CmdWithReason,
    response: z.object({ id: Uuid, status: z.enum(CLOSING_DELIVERABLE_STATUSES), version: z.number().int() }),
  }),

  // ---------------------------------------------------------------- conditions precedent
  listConditions: defineRoute({
    id: 'jv.listConditions',
    method: 'GET',
    path: `${P}/closing-conditions`,
    summary: 'Conditions precedent (CP register)',
    tags,
    access: 'jv.deal.read',
    params: ProjectParams,
    query: PageQuery.extend({ closingId: Uuid.optional(), status: z.enum(CONDITION_STATUSES).optional(), blocking: z.enum(['true', 'false']).optional(), sort: SortParam(['reference', 'status', 'longStopDate', 'updatedAt']) }),
    response: paged(ConditionDto).extend({ people: People }),
  }),
  getCondition: defineRoute({ id: 'jv.getCondition', method: 'GET', path: `${P}/closing-conditions/:conditionId`, summary: 'Condition precedent with its waivers', tags, access: 'jv.deal.read', params: idP('conditionId'), response: ConditionDto.extend({ waivers: z.array(WaiverDto), people: People }) }),
  createCondition: defineRoute({
    id: 'jv.createCondition',
    method: 'POST',
    path: `${P}/closing-conditions`,
    summary: 'Add a CP to ONE closing (not waivable until a specialist determines otherwise)',
    tags,
    access: 'jv.cp.manage',
    params: ProjectParams,
    body: z.object({
      closingId: Uuid,
      reference: z.string().trim().regex(/^[A-Z0-9][A-Z0-9-]{1,31}$/, 'Upper-case reference').optional(),
      title: RequiredText(300),
      description: Text(4000).optional(),
      ownerUserId: Uuid,
      parties: Text(1000).optional(),
      blocking: z.boolean().default(true),
      validTo: IsoDate.optional(),
      longStopDate: IsoDate.optional(),
      gateKey: z.enum(['G6']).optional(),
    }),
    response: CreatedResult,
  }),
  updateCondition: defineRoute({
    id: 'jv.updateCondition',
    method: 'PATCH',
    path: `${P}/closing-conditions/:conditionId`,
    summary:
      'Edit CP description, owner, parties, validity and long-stop date (never status or waivability). The validity of a verified / waived CP changes only after a reopen; a long-stop date moves later only through an approved extension',
    tags,
    access: 'jv.cp.manage',
    params: idP('conditionId'),
    body: z.object({
      expectedVersion: ExpectedVersion,
      title: RequiredText(300).optional(),
      description: Text(4000).nullable().optional(),
      ownerUserId: Uuid.optional(),
      parties: Text(1000).nullable().optional(),
      validTo: IsoDate.nullable().optional(),
      longStopDate: IsoDate.nullable().optional(),
    }),
    response: VersionResult,
  }),
  determineConditionWaivability: defineRoute({
    id: 'jv.determineConditionWaivability',
    method: 'POST',
    path: `${P}/closing-conditions/:conditionId/determine-waivability`,
    summary: 'Legal specialist determination of blocking status, waivability and waiver authority (documented basis; never releases a blocking CP)',
    tags,
    access: 'jv.cp.set_waivability',
    command: true,
    params: idP('conditionId'),
    body: z.object({ expectedVersion: ExpectedVersion, blocking: z.boolean(), waivable: z.boolean(), waiverAuthorityRole: Role.nullable(), basis: RequiredText(4000) }),
    response: VersionResult,
  }),
  extendConditionLongStop: defineRoute({
    id: 'jv.extendConditionLongStop',
    method: 'POST',
    path: `${P}/closing-conditions/:conditionId/extend-long-stop`,
    summary: 'Record an approved extension of the CP long-stop date (FINAL decision; a lapsed CP is open again)',
    tags,
    access: 'jv.cp.manage',
    command: true,
    params: idP('conditionId'),
    body: z.object({ expectedVersion: ExpectedVersion, longStopDate: IsoDate, decisionId: Uuid, reason: RequiredText(4000) }),
    response: z.object({ id: Uuid, status: z.enum(CONDITION_STATUSES), version: z.number().int() }),
  }),
  submitConditionEvidence: defineRoute({
    id: 'jv.submitConditionEvidence',
    method: 'POST',
    path: `${P}/closing-conditions/:conditionId/submit-evidence`,
    summary: 'Submit the CP for verification (linked evidence required)',
    tags,
    access: 'jv.cp.manage',
    command: true,
    params: idP('conditionId'),
    body: Cmd,
    response: z.object({ id: Uuid, status: z.enum(CONDITION_STATUSES), version: z.number().int() }),
  }),
  verifyCondition: defineRoute({
    id: 'jv.verifyCondition',
    method: 'POST',
    path: `${P}/closing-conditions/:conditionId/verify`,
    summary: 'verifyCP — evidence required; not the owner or evidence submitter; human only',
    tags,
    access: 'jv.cp.verify',
    command: true,
    params: idP('conditionId'),
    body: z.object({ expectedVersion: ExpectedVersion, outcome: z.enum(['verify', 'reject_evidence']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(CONDITION_STATUSES), version: z.number().int() }),
  }),
  reopenCondition: defineRoute({ id: 'jv.reopenCondition', method: 'POST', path: `${P}/closing-conditions/:conditionId/reopen`, summary: 'Reopen a verified / waived CP (defective evidence)', tags, access: 'jv.cp.manage', command: true, params: idP('conditionId'), body: CmdWithReason, response: z.object({ id: Uuid, status: z.enum(CONDITION_STATUSES), version: z.number().int() }) }),
  requestConditionWaiver: defineRoute({
    id: 'jv.requestConditionWaiver',
    method: 'POST',
    path: `${P}/closing-conditions/:conditionId/waivers`,
    summary: 'Request a waiver — refused (and logged) for a non-waivable CP (AT-13)',
    tags,
    access: 'jv.cp.manage',
    params: idP('conditionId'),
    body: z.object({ basis: RequiredText(4000), impact: RequiredText(4000), conditions: Text(4000).optional(), expiresOn: IsoDate.optional() }),
    response: z.object({ id: Uuid, status: z.string(), version: z.number().int() }),
  }),
  approveConditionWaiver: defineRoute({
    id: 'jv.approveConditionWaiver',
    method: 'POST',
    path: `${P}/closing-condition-waivers/:waiverId/approve`,
    summary: 'Approve a CP waiver (waiver authority; not the requester; waivable CP only; human only)',
    tags,
    access: 'jv.cp.waive',
    command: true,
    params: idP('waiverId'),
    body: Cmd,
    response: z.object({ id: Uuid, status: z.string(), version: z.number().int() }),
  }),
  rejectConditionWaiver: defineRoute({
    id: 'jv.rejectConditionWaiver',
    method: 'POST',
    path: `${P}/closing-condition-waivers/:waiverId/reject`,
    summary: 'Reject a CP waiver request',
    tags,
    access: 'jv.cp.waive',
    command: true,
    params: idP('waiverId'),
    body: z.object({ expectedVersion: ExpectedVersion, note: RequiredText(4000) }),
    response: z.object({ id: Uuid, status: z.string(), version: z.number().int() }),
  }),

  // ---------------------------------------------------------------- funds flow (record-only)
  listFundsFlows: defineRoute({
    id: 'jv.listFundsFlows',
    method: 'GET',
    path: `${P}/closings/:eventId/funds-flows`,
    summary: 'Funds flow of a closing — RECORD ONLY (the platform never executes payments)',
    tags,
    access: 'jv.deal.read',
    params: EventParams,
    response: z.object({ items: z.array(FundsFlowDto), notice: z.string() }),
  }),
  createFundsFlow: defineRoute({
    id: 'jv.createFundsFlow',
    method: 'POST',
    path: `${P}/closings/:eventId/funds-flows`,
    summary: 'Record a planned funds-flow line (amount + currency + unit scale, or TBD)',
    tags,
    access: 'jv.funds_flow.manage',
    params: EventParams,
    body: z.object({ description: RequiredText(1000), payer: RequiredText(200), payee: RequiredText(200), amount: MoneySchema.optional(), valueDate: IsoDate.optional() }),
    response: CreatedResult,
  }),
  transitionFundsFlow: defineRoute({
    id: 'jv.transitionFundsFlow',
    method: 'POST',
    path: `${P}/funds-flows/:flowId/transition`,
    summary: 'confirm / report_settled (with the external settlement reference) / cancel — nothing is paid by the platform',
    tags,
    access: 'jv.funds_flow.manage',
    command: true,
    params: idP('flowId'),
    body: z.object({ expectedVersion: ExpectedVersion, command: z.enum(['confirm', 'report_settled', 'cancel']), settlementReference: Text(500).optional(), note: Text(2000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(FUNDS_FLOW_STATUSES), version: z.number().int() }),
  }),

  // ---------------------------------------------------------------- conditions subsequent / post-close obligations
  listObligations: defineRoute({
    id: 'jv.listObligations',
    method: 'GET',
    path: `${P}/post-close-obligations`,
    summary: 'Conditions subsequent and post-close obligations (overdue computed in the project timezone)',
    tags,
    access: 'jv.deal.read',
    params: ProjectParams,
    query: PageQuery.extend({ status: z.enum(POST_CLOSE_STATUSES).optional(), kind: z.enum(POST_CLOSE_KINDS).optional(), sort: SortParam(['code', 'dueDate', 'status', 'updatedAt']) }),
    response: paged(ObligationDto).extend({ people: People }),
  }),
  createObligation: defineRoute({
    id: 'jv.createObligation',
    method: 'POST',
    path: `${P}/post-close-obligations`,
    summary: 'Record a condition subsequent / post-close obligation / appointment / governance / benefit / handover item',
    tags,
    access: 'jv.closing_checklist.manage',
    params: ProjectParams,
    body: z.object({
      kind: z.enum(POST_CLOSE_KINDS),
      title: RequiredText(300),
      description: Text(4000).optional(),
      responsibleParty: Text(200).optional(),
      ownerUserId: Uuid.optional(),
      dueDate: IsoDate.optional(),
      closingId: Uuid.optional(),
    }),
    response: CreatedResult,
  }),
  transitionObligation: defineRoute({
    id: 'jv.transitionObligation',
    method: 'POST',
    path: `${P}/post-close-obligations/:obligationId/transition`,
    summary: 'start / report_complete / cancel (verification is a separate command)',
    tags,
    access: 'jv.closing_checklist.manage',
    command: true,
    params: idP('obligationId'),
    body: z.object({ expectedVersion: ExpectedVersion, command: z.enum(['start', 'report_complete', 'cancel']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(POST_CLOSE_STATUSES), version: z.number().int() }),
  }),
  verifyObligation: defineRoute({
    id: 'jv.verifyObligation',
    method: 'POST',
    path: `${P}/post-close-obligations/:obligationId/verify`,
    summary: 'Verify a completed obligation with evidence (not the owner or reporter) or reject the completion',
    tags,
    access: 'jv.cp.verify',
    command: true,
    params: idP('obligationId'),
    body: z.object({ expectedVersion: ExpectedVersion, outcome: z.enum(['verify', 'reject_completion']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(POST_CLOSE_STATUSES), version: z.number().int() }),
  }),

  // ---------------------------------------------------------------- program closure (REQ-JV-019)
  getProgramClosure: defineRoute({ id: 'jv.getProgramClosure', method: 'GET', path: `${P}/program-closure`, summary: 'Program closure state (separate from transaction closing; requires G7)', tags, access: 'portfolio.project.read', params: ProjectParams, response: ProgramClosureDto }),
  requestProgramClosure: defineRoute({
    id: 'jv.requestProgramClosure',
    method: 'POST',
    path: `${P}/program-closure/request`,
    summary: 'Request administrative program closure (rejected before G7 passes)',
    tags,
    access: 'jv.closing_checklist.manage',
    command: true,
    params: ProjectParams,
    body: z.object({ handoverNote: RequiredText(4000) }),
    response: z.object({ id: Uuid, status: z.enum(PROGRAM_CLOSURE_STATUSES), version: z.number().int() }),
  }),
  confirmProgramClosure: defineRoute({
    id: 'jv.confirmProgramClosure',
    method: 'POST',
    path: `${P}/program-closure/confirm`,
    summary: 'Authorized confirmation of program closure (G7 re-checked; not the requester)',
    tags,
    access: 'portfolio.project.archive',
    command: true,
    params: ProjectParams,
    body: z.object({ expectedVersion: ExpectedVersion, outcome: z.enum(['confirm', 'reject']), note: Text(4000).optional() }),
    response: z.object({ id: Uuid, status: z.enum(PROGRAM_CLOSURE_STATUSES), version: z.number().int() }),
  }),
});

