import { z } from 'zod';
import { defineRoute, registerRoutes } from './route';
import { NoSort, PageQuery, Uuid } from './common';
import { IntegrationStatusSchema } from './integrations';

/**
 * In-app notifications (REQ-PLT-008, REQ-INT-012, C-33). Produced by the worker from outbox events after re-checking the
 * recipient's CURRENT access; read here with a second re-check (a notification whose source the reader can no longer see
 * is not listed or counted). Notifications carry codes, record codes and a deep link — the content is read behind the link.
 * Email and Teams are adapters of the integrations registry and stay Not configured (nothing is sent outside).
 */
const T = ['Notifications'];

export const NotificationDto = z.object({
  id: Uuid,
  kind: z.string(),
  projectId: Uuid.nullable(),
  projectCode: z.string().nullable(),
  /** English rendering (also the text of AI messages, marked as AI-generated by the platform). */
  title: z.string(),
  body: z.string().nullable(),
  /** Code + parameters for notifications of the notifications module (translated by the web); null for AI messages. */
  messageCode: z.string().nullable(),
  messageParams: z.record(z.string(), z.union([z.string(), z.number()])).nullable(),
  link: z.string().nullable(),
  createdAt: z.string(),
  readAt: z.string().nullable(),
});
export type NotificationDtoT = z.infer<typeof NotificationDto>;

export const NotificationChannelDto = z.object({
  channel: z.enum(['in_app', 'email', 'teams', 'sms']),
  /** in_app is always on; the others follow their connector's honest status. */
  status: z.union([z.literal('enabled'), IntegrationStatusSchema]),
  adapterKey: z.string().nullable(),
});

export const notificationsRoutes = registerRoutes({
  listMyNotifications: defineRoute({
    id: 'notifications.list',
    method: 'GET',
    path: '/api/v1/me/notifications',
    summary: 'My notifications, newest first (fixed order), re-authorised at read time',
    tags: T,
    access: 'authenticated',
    query: PageQuery.extend({ sort: NoSort, unread: z.enum(['true', 'false']).optional() }),
    response: z.object({ items: z.array(NotificationDto), page: z.number().int(), pageSize: z.number().int(), total: z.number().int() }),
  }),
  unreadCount: defineRoute({
    id: 'notifications.unreadCount',
    method: 'GET',
    path: '/api/v1/me/notifications/unread-count',
    summary: 'Number of my unread notifications (same re-check as the list)',
    tags: T,
    access: 'authenticated',
    response: z.object({ count: z.number().int() }),
  }),
  markRead: defineRoute({
    id: 'notifications.markRead',
    method: 'POST',
    path: '/api/v1/me/notifications/:notificationId/read',
    summary: 'Mark one of my notifications read',
    tags: T,
    access: 'authenticated',
    command: true,
    params: z.object({ notificationId: Uuid }),
    response: z.object({ id: Uuid, readAt: z.string() }),
  }),
  markAllRead: defineRoute({
    id: 'notifications.markAllRead',
    method: 'POST',
    path: '/api/v1/me/notifications/read-all',
    summary: 'Mark all my notifications read',
    tags: T,
    access: 'authenticated',
    command: true,
    response: z.object({ updated: z.number().int() }),
  }),
  myChannels: defineRoute({
    id: 'notifications.channels',
    method: 'GET',
    path: '/api/v1/me/notification-channels',
    summary: 'Delivery channels and their honest status (in-app enabled; email / Teams per connector status)',
    tags: T,
    access: 'authenticated',
    response: z.object({ items: z.array(NotificationChannelDto) }),
  }),
});
