import { z } from 'zod';
import { PROJECT_STATUSES, TEMPLATE_KINDS, INCORPORATION_STATUSES, ROLE_KEYS, STATUS_DIMENSION_KEYS } from '@hub/domain';
import { defineRoute, registerRoutes } from './route';
import { Uuid, IsoDate, ClassificationSchema, PageQuery, paged, Text, RequiredText, ProjectParams, Ok, ExpectedVersion } from './common';

export const TemplateVersionDto = z.object({
  id: Uuid,
  templateId: Uuid,
  templateKey: z.string(),
  kind: z.enum(TEMPLATE_KINDS),
  name: z.string(),
  versionNo: z.number().int(),
  status: z.string(),
  counts: z.object({ gates: z.number(), workstreams: z.number(), activities: z.number(), kpis: z.number() }),
  publishedAt: z.string().nullable(),
});

export const ProjectSummaryDto = z.object({
  id: Uuid,
  code: z.string(),
  name: z.string(),
  status: z.enum(PROJECT_STATUSES),
  classification: ClassificationSchema,
  isDemo: z.boolean(),
  templateKey: z.string(),
  templateKind: z.enum(TEMPLATE_KINDS),
  templateVersionNo: z.number().int(),
  programName: z.string().nullable(),
  myRoles: z.array(z.enum(ROLE_KEYS)),
  dimensions: z.array(z.object({ key: z.enum(STATUS_DIMENSION_KEYS), state: z.string(), explanation: z.string().nullable() })),
  openRisks: z.number().int().nullable(),
  overdueActions: z.number().int().nullable(),
  nextGate: z.object({ key: z.string(), name: z.string(), status: z.string() }).nullable(),
});
export type ProjectSummary = z.infer<typeof ProjectSummaryDto>;

export const ProjectDetailDto = ProjectSummaryDto.extend({
  description: z.string().nullable(),
  objective: z.string().nullable(),
  timezone: z.string(),
  workingDays: z.array(z.number().int()),
  plannedStart: z.string().nullable(),
  version: z.number().int(),
  setupState: z.record(z.string(), z.unknown()),
  phases: z.array(z.object({ key: z.string(), name: z.string(), gateKeys: z.array(z.string()) })),
  entities: z.array(z.object({ id: Uuid, name: z.string(), role: z.string(), incorporationStatus: z.string(), verification: z.string(), isDemo: z.boolean() })),
  counts: z.record(z.string(), z.number()),
});

export const CreateProjectBody = z.object({
  templateVersionId: Uuid,
  programId: Uuid.optional(),
  code: z.string().trim().regex(/^[A-Z0-9][A-Z0-9-]{1,30}$/, 'Upper-case letters, digits and dashes'),
  name: RequiredText(200),
  description: Text(4000).optional(),
  objective: Text(4000).optional(),
  classification: ClassificationSchema.default('confidential'),
  plannedStart: IsoDate.optional(),
  projectManagerUserId: Uuid,
  newco: z
    .object({
      mode: z.enum(['none', 'existing', 'new']),
      legalEntityId: Uuid.optional(),
      name: Text(200).optional(),
      incorporationStatus: z.enum(INCORPORATION_STATUSES).default('unconfirmed'),
    })
    .default({ mode: 'none', incorporationStatus: 'unconfirmed' }),
});

export const MembershipDto = z.object({
  id: Uuid,
  userId: Uuid,
  displayName: z.string(),
  email: z.string(),
  role: z.enum(ROLE_KEYS),
  workstreamId: Uuid.nullable(),
  workstreamCode: z.string().nullable(),
  validTo: z.string().nullable(),
  grantedAt: z.string(),
});

export const DirectoryUserDto = z.object({ id: Uuid, displayName: z.string(), email: z.string(), title: z.string().nullable(), isDemo: z.boolean() });

export const WorkstreamDto = z.object({
  id: Uuid,
  code: z.string(),
  name: z.string(),
  nameAr: z.string().nullable(),
  objective: z.string().nullable(),
  scope: z.string().nullable(),
  leadUserId: Uuid.nullable(),
  leadName: z.string().nullable(),
  proposedLeadFunction: z.string().nullable(),
  raci: z.array(z.object({ function: z.string(), raci: z.string() })),
  linkedGateKeys: z.array(z.string()),
  version: z.number().int(),
  counts: z.object({ tasks: z.number(), openRisks: z.number(), deliverables: z.number() }),
});

export const portfolioRoutes = registerRoutes({
  listProjects: defineRoute({
    id: 'portfolio.listProjects',
    method: 'GET',
    path: '/api/v1/projects',
    summary: 'Projects the caller is authorized to see (Portfolio Home)',
    tags: ['portfolio'],
    access: 'authenticated',
    query: PageQuery.extend({ includeDemo: z.enum(['true', 'false']).default('true') }),
    response: paged(ProjectSummaryDto),
  }),
  getProject: defineRoute({
    id: 'portfolio.getProject',
    method: 'GET',
    path: '/api/v1/projects/:projectId',
    summary: 'Project overview & charter data',
    tags: ['portfolio'],
    access: 'portfolio.project.read',
    params: ProjectParams,
    response: ProjectDetailDto,
  }),
  createProject: defineRoute({
    id: 'portfolio.createProject',
    method: 'POST',
    path: '/api/v1/projects',
    summary: 'Create a project from a published template version (no code changes needed)',
    tags: ['portfolio'],
    access: { org: 'portfolio.project.create' },
    command: true,
    body: CreateProjectBody,
    response: z.object({ id: Uuid, code: z.string(), created: z.record(z.string(), z.number()) }),
  }),
  updateProject: defineRoute({
    id: 'portfolio.updateProject',
    method: 'PATCH',
    path: '/api/v1/projects/:projectId',
    summary: 'Update descriptive project fields (no status fields)',
    tags: ['portfolio'],
    access: 'portfolio.project.update',
    params: ProjectParams,
    body: z.object({
      expectedVersion: ExpectedVersion,
      name: RequiredText(200).optional(),
      description: Text(4000).optional(),
      objective: Text(4000).optional(),
      plannedStart: IsoDate.nullable().optional(),
    }),
    response: z.object({ version: z.number().int() }),
  }),
  listTemplates: defineRoute({
    id: 'portfolio.listTemplates',
    method: 'GET',
    path: '/api/v1/templates',
    summary: 'Published project template versions',
    tags: ['config'],
    access: 'authenticated',
    response: z.object({ items: z.array(TemplateVersionDto) }),
  }),
  listPrograms: defineRoute({
    id: 'portfolio.listPrograms',
    method: 'GET',
    path: '/api/v1/programs',
    summary: 'Programs (for project creation)',
    tags: ['portfolio'],
    access: { org: 'portfolio.portfolio.read' },
    response: z.object({ items: z.array(z.object({ id: Uuid, code: z.string(), name: z.string(), portfolioName: z.string(), isDemo: z.boolean() })) }),
  }),
  directory: defineRoute({
    id: 'portfolio.directory',
    method: 'GET',
    path: '/api/v1/directory/users',
    summary: 'Search people for assignment (name/email only)',
    tags: ['identity'],
    access: 'authenticated',
    query: z.object({ q: z.string().trim().max(100).default('') }),
    response: z.object({ items: z.array(DirectoryUserDto) }),
  }),
  listMembers: defineRoute({
    id: 'portfolio.listMembers',
    method: 'GET',
    path: '/api/v1/projects/:projectId/members',
    summary: 'Project memberships (roles by project/workstream)',
    tags: ['portfolio'],
    access: 'admin.role_assignment.read',
    params: ProjectParams,
    response: z.object({ items: z.array(MembershipDto) }),
  }),
  grantMembership: defineRoute({
    id: 'portfolio.grantMembership',
    method: 'POST',
    path: '/api/v1/projects/:projectId/members',
    summary: 'Grant a project or workstream role',
    tags: ['portfolio'],
    access: 'admin.role_assignment.manage',
    command: true,
    params: ProjectParams,
    body: z.object({ userId: Uuid, role: z.enum(ROLE_KEYS), workstreamId: Uuid.optional(), reason: RequiredText(500), validTo: IsoDate.optional() }),
    response: z.object({ id: Uuid }),
  }),
  revokeMembership: defineRoute({
    id: 'portfolio.revokeMembership',
    method: 'POST',
    path: '/api/v1/projects/:projectId/members/:membershipId/revoke',
    summary: 'Revoke a project role (effective immediately, including for queued jobs)',
    tags: ['portfolio'],
    access: 'admin.role_assignment.manage',
    command: true,
    params: ProjectParams.extend({ membershipId: Uuid }),
    body: z.object({ reason: RequiredText(500) }),
    response: Ok,
  }),
  listWorkstreams: defineRoute({
    id: 'portfolio.listWorkstreams',
    method: 'GET',
    path: '/api/v1/projects/:projectId/workstreams',
    summary: 'Workstreams with counts',
    tags: ['planning'],
    access: 'planning.plan.read',
    params: ProjectParams,
    response: z.object({ items: z.array(WorkstreamDto) }),
  }),
  assignWorkstreamLead: defineRoute({
    id: 'portfolio.assignWorkstreamLead',
    method: 'POST',
    path: '/api/v1/projects/:projectId/workstreams/:workstreamId/lead',
    summary: 'Assign the accountable workstream lead',
    tags: ['planning'],
    access: 'planning.ownership.reassign',
    command: true,
    params: ProjectParams.extend({ workstreamId: Uuid }),
    body: z.object({ userId: Uuid, expectedVersion: ExpectedVersion }),
    response: z.object({ version: z.number().int() }),
  }),
  auditTrail: defineRoute({
    id: 'portfolio.auditTrail',
    method: 'GET',
    path: '/api/v1/projects/:projectId/activity',
    summary: 'Activity history for a record or the whole project (visible actions only)',
    tags: ['audit'],
    access: 'portfolio.project.read',
    params: ProjectParams,
    query: PageQuery.extend({ entityType: z.string().max(48).optional(), entityId: Uuid.optional() }),
    response: paged(
      z.object({
        id: Uuid,
        at: z.string(),
        actor: z.string().nullable(),
        actorKind: z.string(),
        action: z.string(),
        entityType: z.string().nullable(),
        entityId: z.string().nullable(),
        outcome: z.string(),
        reason: z.string().nullable(),
      }),
    ),
  }),
});
