// P3 operations without a route yet, owned by backend-workflow-engineer task BE-C (roadmap, deliverables, milestones, T08 dependencies and types) (docs/architecture/p3-work-split.md).
// Remove an entry in the same change that registers its route and exercises it in the contract test. Must be empty
// when the DG3 candidate freezes. Only this task edits this file.
export const P3_PENDING_BE_C: readonly string[] = [
  "listDeliverables",
  "createDeliverable",
  "getDeliverable",
  "updateDeliverable",
  "submitDeliverable",
  "decideDeliverable",
  "listMilestones",
  "createMilestone",
  "getMilestone",
  "updateMilestone",
  "approveMilestoneDate",
  "listRoadmapWaves",
  "createRoadmapWave",
  "getRoadmapWave",
  "updateRoadmapWave",
  "getRoadmap",
  "listT08Dependencies",
  "createT08Dependency",
  "getT08Dependency",
  "updateT08Dependency",
  "archiveT08Dependency",
  "listDependencyTypes",
  "createDependencyType",
  "updateDependencyType",
  "retireDependencyType",
];
