// The operations the P4 contract adds (docs/api/openapi.yaml 1.3.0-p4 onward), one block per architecture task. Frozen
// per block (solution-architect); each later ARCH task appends its own block. Used to keep the P2-scoped generated sweeps
// (aud-write-deny.test.ts) on their P2 scope, as p3-operations.ts does for P3; the P4 slices add their own AUD tests
// once their operations are routed (docs/architecture/p4-work-split.md, S-4).
export const P4_OPERATION_IDS: ReadonlySet<string> = new Set([
  // T-DG4-ARCH-01: slices I and C (51 operations; ADR-0025, ADR-0026).
  "listBusinessCalendars",
  "createBusinessCalendar",
  "getBusinessCalendar",
  "updateBusinessCalendar",
  "listCalendarHolidays",
  "createCalendarHoliday",
  "updateCalendarHoliday",
  "computeWorkingDayDueDate",
  "listJobSchedules",
  "updateJobSchedule",
  "listMyWorkItems",
  "getWorkItem",
  "completeWorkItem",
  "listMyInbox",
  "markInboxNotificationRead",
  "listGroups",
  "createGroup",
  "getGroup",
  "updateGroup",
  "listGroupMembers",
  "addGroupMember",
  "removeGroupMember",
  "listGovernanceParties",
  "listRoleMappings",
  "createRoleMapping",
  "endRoleMapping",
  "resolveGovernanceParty",
  "listDelegations",
  "createDelegation",
  "getDelegation",
  "revokeDelegation",
  "listMyApprovals",
  "requestApproval",
  "getApproval",
  "decideApproval",
  "resubmitApproval",
  "withdrawApproval",
  "listApprovalDecisionRecords",
  "listDecisionRightTemplates",
  "listDecisionRights",
  "createDecisionRight",
  "getDecisionRight",
  "updateDecisionRight",
  "previewDecisionRightDueDate",
  "getRaciTemplate",
  "getTransformationRaci",
  "createRaciDeliverable",
  "updateRaciDeliverable",
  "listGovernanceMatrices",
  "submitGovernanceMatrix",
  "getTransformReadiness",
]);
