M="docs/delivery/test-evidence/DG4/orchestrator/w18-merged-dca6b64/integration.log"
E2E="docs/delivery/test-evidence/DG4/orchestrator/w18-merged-dca6b64/e2e-unset.log"
UNIT="docs/delivery/test-evidence/DG4/orchestrator/w18-merged-dca6b64/unit-unset.log"
QAA="docs/delivery/test-evidence/DG4/qa/T-DG4-QA-A-authoring/HANDBACK-T-DG4-QA-A-qa-verifier.md"
QAB="docs/delivery/test-evidence/DG4/qa/T-DG4-QA-B-authoring/HANDBACK-T-DG4-QA-B-qa-verifier.md"
QAC="docs/delivery/test-evidence/DG4/qa/T-DG4-QA-C-authoring/HANDBACK-T-DG4-QA-C-qa-verifier.md"
A="apps/api/src/modules/"; T="apps/api/test/integration/"; W="apps/web/src/pages/"; WK="apps/worker/"; Q="tests/qa/integration/"
ADR="docs/architecture/adr/"
A25=ADR+"ADR-0025-p4-calendar-time-jobs-work-items.md"; A26=ADR+"ADR-0026-p4-groups-delegation-approvals-t11-t12.md"
A27=ADR+"ADR-0027-p4-kpi-data-model-and-pipeline.md"; A28=ADR+"ADR-0028-p4-kpi-calculation-semantics.md"
A29=ADR+"ADR-0029-p4-benefit-register-lifecycle-allocations.md"; A30=ADR+"ADR-0030-p4-benefit-values-finance-validation-totals.md"
A31=ADR+"ADR-0031-p4-raid-actions-corrective-execution.md"; A32=ADR+"ADR-0032-p4-forums-meetings-t16-escalation.md"
A33=ADR+"ADR-0033-p4-adoption-stakeholders-interventions-assessments.md"; A34=ADR+"ADR-0034-p4-sustainment-bau-handover-closure.md"
A35=ADR+"ADR-0035-p4-phases-g5-g6-exceptions-routing.md"; A36=ADR+"ADR-0036-p4-change-control-impact-assessment.md"
A37=ADR+"ADR-0037-p4-dashboards-t10-my-work-overview-header.md"; A38=ADR+"ADR-0038-p4-traceability-orphans-allocation-impact-modular.md"
P="DG4 analyst check (T-DG4-AN-P4A, base e3acab1): "
R={}
def r(i, ev, note): R[i]=(ev, P+note)

r("REQ-PB-005",[A+"reporting/modular.ts",A+"transformations/missing-links-facts.ts",A+"workflows/gates.ts",W+"traceability/ModularPage.tsx",T+"reporting/modular.test.ts",T+"workflows/modular-precondition.test.ts",T+"workflows/modular-waiver.test.ts",Q+"a03-modular-entry.test.ts","e2e/a03-modular-entry.spec.ts","apps/web/e2e/p4-traceability.spec.ts",A38,QAC,M],
 "A03 is asserted by a03-modular-entry.test.ts: at Design with no baseline and no outcome link both are flagged blocking, G3 submission is 422 gate.modular_links_missing listing both with nothing written, and it is accepted once both are supplied or an accepted, unexpired waiver exists (the D-110 waiver cases, including revoked and expired); e2e/a03-modular-entry.spec.ts shows the same refusal in chromium-en and chromium-ar.")
r("REQ-PB-008",[A+"portfolio/readiness.ts",A+"portfolio/readiness-transform.test.ts",W+"decision-rights/TransformReadinessPage.tsx",T+"governance/raci-matrices.test.ts",A26,M],
 "governance/raci-matrices.test.ts 'REQ-PB-008: Transform readiness' asserts not_ready while the charter decision rights or T11 are empty and ready once they are completed, with the pure checks in readiness-transform.test.ts.")
r("REQ-PB-009",[A+"sustainment/status-model.ts",A+"sustainment/closure.ts",W+"closure/ClosurePage.tsx",W+"closure/closure.test.tsx",T+"sustainment/status-model.test.ts",T+"sustainment/closure.test.ts",Q+"a11-value-closure.test.ts","apps/web/e2e/p4-gates-closure.spec.ts",A34,QAC,M],
 "A11 is asserted by a11-value-closure.test.ts: the label is exactly 'Delivered — value validation pending' and closing an initiative with delivery Complete and no validated benefit is 422 invalid-transition with nothing written; also closure.test.ts and status-model.test.ts, and closure.test.tsx for the UI label.")
r("REQ-PB-010",[A+"reporting/traceability.ts",A+"benefits/register.ts",A+"portfolio/dashboard-facts.ts",T+"reporting/one-source-of-truth.test.ts",A38,M],
 "one-source-of-truth.test.ts asserts that one PATCH of an initiative's name shows at once in the roadmap, the traceability view and the benefits register (initiatives[]), and that the database holds exactly one initiative row. Partial: the 'scorecard' read (the T10 Portfolio area, D-106 (d)) is not re-read after the rename by any test; portfolio/dashboard-facts.ts reads initiative.name live from the same single row, so this is a test-coverage gap rather than a behaviour gap.")
r("REQ-PB-013",[A+"benefits/finance-validation.ts","packages/shared/src/permissions.ts",W+"finance-validation/FinanceValidationPages.tsx",T+"benefits/finance-validation.test.ts",Q+"a10-benefit-integrity.test.ts",A30,QAA,M],
 "A10/A12 are asserted by a10-benefit-integrity.test.ts 'REQ-S08-015, REQ-PB-013': a BO and the auditor get 403 on the Finance decision with the total unchanged, a FIN user succeeds, and the audit event carries the FIN user as actor; also finance-validation.test.ts 'only Finance decides, and the audit names the validator' and the baseline half.")
r("REQ-PB-014",[A+"workflows/phase-steps.ts",W+"phases/PhasesPage.tsx",W+"phases/phases.test.tsx",T+"workflows/phases.test.ts","apps/web/e2e/p4-change-phases.spec.ts",A35,M,E2E],
 "workflows/phases.test.ts 'the phase catalogue (REQ-PB-014)' asserts that GET /phases returns exactly six phases in order with names, purposes and key outputs equal to B0021 and objectives equal to the phase blocks, and the workspace shows the current phase's objective; phases.test.tsx and p4-change-phases.spec.ts render it in en and ar.")
r("REQ-PB-015",[A+"workflows/g5.ts",A+"workflows/g6.ts",A+"workflows/gates.ts",T+"workflows/g5-g6.test.ts",Q+"a08-gate-controls.test.ts","e2e/a08-a09-gates-decisions.spec.ts",A35,QAB,M],
 "A08 is asserted by a08-gate-controls.test.ts: a submission with missing mandatory evidence is 422 with no submission written, a non-approver (BO, WL, TL, AUD) gets 403, and a stale submission number or stale If-Match is 409; g5-g6.test.ts proves the same for G5/G6, and e2e/a08-a09-gates-decisions.spec.ts shows the missing items on the gate page in en and ar.")
r("REQ-PB-020",[A+"workflows/g5.ts",A+"workflows/scale.ts",A+"raid/gate-facts.ts",W+"gates/ScaleRisk.tsx",T+"workflows/g5-g6.test.ts",T+"workflows/risk-dispositions.test.ts",Q+"a08-gate-controls.test.ts",Q+"a11-bau-sustain.test.ts",A35,QAB,M],
 "A08/A11 are asserted by a08-gate-controls.test.ts: G5 with an open High-impact risk and no disposition is refused listing 'Risk closure', and with the G5 approver configured to BO an SP approval is 403 while a BO approval succeeds and records the scale scope; g5-g6.test.ts and risk-dispositions.test.ts at API level; a11-bau-sustain.test.ts reaches and decides G5 natively.")
r("REQ-PB-021",[A+"workflows/g6.ts",A+"sustainment/gate-facts.ts",T+"workflows/g5-g6.test.ts",Q+"a08-gate-controls.test.ts",Q+"a11-bau-sustain.test.ts","apps/web/e2e/p4-gates-closure.spec.ts",A35,QAB,QAC,M],
 "A08/A11 are asserted by a08-gate-controls.test.ts and a11-bau-sustain.test.ts 'G6 without an accepted BAU handover is refused, listing Ownership transfer' (422 gate_criteria_incomplete); p4-gates-closure.spec.ts shows the item missing on the G6 page.")
r("REQ-PB-044",[A+"reporting/traceability.ts",A+"reporting/orphans.ts",W+"traceability/TraceabilityPage.tsx",W+"traceability/traceability.test.tsx",T+"reporting/orphans.test.ts",T+"reporting/traceability.test.ts","apps/web/e2e/p4-traceability.spec.ts",A38,M,E2E],
 "orphans.test.ts asserts that an initiative without a TOM gap link is listed with the expected 'tom_gap → initiative' step; traceability.test.ts 'every node opens its record' asserts that every node's href answers 200 with that record; p4-traceability.spec.ts clicks an orphan's node through to its record in en and ar.")
r("REQ-PB-058",[A+"benefits/register.ts",A+"benefits/allocations.ts",A+"benefits/groups.ts",A+"benefits/totals.ts",A+"benefits/counting.ts",T+"benefits/register.test.ts",T+"benefits/totals.test.ts",T+"benefits/groups.test.ts",Q+"a10-benefit-integrity.test.ts",A29,A30,QAA,M],
 "A10 is asserted by a10-benefit-integrity.test.ts: a benefit with two owners is 400 with no row written; a 10 million SAR benefit allocated 50/50 to two initiatives appears once (planned 10000000, count 1) in the totals and on the Finance dashboard; two records in a shared-benefit group count once. Backed by register.test.ts, totals.test.ts and groups.test.ts.")
r("REQ-PB-060",[A+"governance/forums.ts",A+"governance/meeting-series.ts","packages/shared/src/governance/recurrence.ts",WK+"src/handlers/meetings.ts",W+"forums/ForumsPage.tsx",T+"governance/forums.test.ts",T+"governance/meeting-series.test.ts",WK+"test/integration/meeting-series.test.ts",A32,M],
 "forums.test.ts asserts that a new transformation lists the five B0093 layers in order with the cadence and every source text verbatim; meeting-series.test.ts asserts that a weekly series creates one meeting per week to the horizon and that a re-run creates none; the worker meeting-series.test.ts runs the scheduled generation.")
r("REQ-PB-061",[A+"governance/minutes.ts",A+"governance/agenda.ts",A+"governance/meeting-outputs.ts",W+"meetings/MeetingPage.tsx",T+"governance/minutes.test.ts",T+"governance/agenda.test.ts",T+"governance/meeting-outputs.test.ts",A32,M],
 "minutes.test.ts asserts that Value Review minutes without a benefit evidence or forecast output are 422 meeting_minutes.required_output_missing with nothing written, and publish with a forecast output; agenda.test.ts asserts that a complete brief publishes into a T16 ask and that the Outcome recorded in the meeting appears in T16.")
r("REQ-PB-062",[A+"reporting/dashboards/areas.ts",A+"reporting/dashboards/engine.ts",A+"reporting/dashboards/drilldown.ts",A+"reporting/dashboards/transformation.ts",W+"dashboards/TransformationDashboardPage.tsx",W+"dashboards/dashboards.test.tsx",T+"reporting/dashboards.test.ts","apps/web/e2e/p4-dashboards.spec.ts",A37,M,E2E],
 "dashboards.test.ts 'REQ-PB-062' asserts that all six areas render in Template 10 order from persisted data with the seeded en and ar labels, and that each headline's drilldownHref answers 200 with its contributing records; p4-dashboards.spec.ts renders the six areas in chromium-en and chromium-ar.")
r("REQ-PB-063",[A+"reporting/dashboards/areas.ts",A+"reporting/dashboards/rag-policy.ts",A+"reporting/dashboards/combine.ts",A+"reporting/dashboards/areas.test.ts",T+"reporting/dashboards.test.ts",T+"reporting/rag-policy.test.ts",A37,M],
 "dashboards.test.ts 'REQ-PB-063' asserts that an outcome whose linked initiative has every milestone achieved and its deliverable accepted, but whose KPI is below trajectory, is red/amber (rule dashboard.rag.outcomes.trajectory), and that a KPI with no actual is unknown with a null value (never 0); the area rules are unit-tested in areas.test.ts.")
r("REQ-PB-064",[A+"reporting/dashboards/areas.ts",A+"reporting/dashboards/areas.test.ts",T+"reporting/dashboards.test.ts",Q+"a09-decision-escalation.test.ts",A37,A32,QAB,M],
 "A09 is asserted by a09-decision-escalation.test.ts 'REQ-PB-064, REQ-PB-081': an open T16 decision due yesterday (Asia/Riyadh) makes the Decisions area Red and is listed, and once its Outcome is recorded it no longer counts (dashboard and overview); also dashboards.test.ts 'REQ-PB-064'.")
r("REQ-PB-065",[A+"governance/decision-rights.ts",A+"governance/matrices.ts",A+"workflows/change-requests.ts",W+"decision-rights/DecisionRightsPage.tsx",T+"governance/decision-rights.test.ts",T+"workflows/change-requests.test.ts",A26,A36,M],
 "decision-rights.test.ts asserts that the four T11 rows are seeded verbatim from B0099 (template and per transformation) and that business_scope_change routes to the SP-mapped person; change-requests.test.ts 'REQ-PB-065 routing' asserts that a business_scope change request is routed to the Sponsor, who alone applies it. Partial (D-114): routing is proven by these API integration tests and stubbed web tests only, not on the real-stack e2e.")
r("REQ-PB-066",[A+"governance/decision-rights.ts","packages/shared/src/time/working-days.test.ts",T+"governance/decision-rights.test.ts",Q+"a09-decision-escalation.test.ts",A25,A26,QAB,M],
 "A09 is asserted by a09-decision-escalation.test.ts (5 working days from a Thursday skip the configured weekend; a holiday is skipped) and decision-rights.test.ts 'REQ-PB-066'. Partial (D-114, QA-B): the server clock cannot be set, so the 'raised Thursday' case runs through the calendar API on the same engine and in working-days.test.ts, while a real Business scope change approval checks the weekend and holiday skip from today's date.")
r("REQ-PB-067",[A+"governance/raci.ts",A+"governance/matrices.ts",W+"raci/RaciPage.tsx",T+"governance/raci-matrices.test.ts",A26,M],
 "raci-matrices.test.ts 'REQ-PB-067: T12 seeded from B0101; cell values' asserts that the seeded RACI equals B0101, a cell value 'X' is refused and 'A/R' is accepted.")
r("REQ-PB-068",[A+"governance/agenda.ts",W+"meetings/MeetingPage.tsx",W+"meetings/governance.test.tsx",T+"governance/agenda.test.ts",Q+"a09-decision-escalation.test.ts",A32,QAB,M],
 "A09 is asserted by a09-decision-escalation.test.ts 'REQ-PB-068, REQ-S10-012' and agenda.test.ts: publishing an executive-ask agenda item missing 'Impact of delay' is 422 agenda_item.executive_ask_incomplete at /brief/impactOfDelay with nothing written.")
r("REQ-PB-069",[A+"adoption/interventions.ts",A+"sustainment/status-model.ts",WK+"src/handlers/adoption.ts",W+"adoption/InterventionsPage.tsx",T+"adoption/indicators.test.ts",T+"sustainment/status-model.test.ts",WK+"test/integration/adoption-below-trajectory.test.ts",Q+"a11-adoption.test.ts",A33,QAC,M],
 "A11 is asserted by a11-adoption.test.ts: a below-trajectory adoption actual creates exactly one owned intervention (a redelivery and a second evaluation add none, and an on-trajectory actual creates none); the initiative with delivery Complete shows adoption at_risk; the owner sees the intervention in My Work.")
r("REQ-PB-070",[A+"adoption/register.ts","packages/shared/src/schemas/adoption-register.ts",W+"adoption/AdoptionPage.tsx",W+"adoption/adoption.test.tsx",T+"adoption/stakeholder-groups.test.ts","apps/web/e2e/p4-adoption-bau.spec.ts",A33,M],
 "stakeholder-groups.test.ts 'T13 rows (REQ-PB-070, REQ-S11-001)' asserts that all seven T13 columns persist, stance 'Hostile' is 400 and the four intervention values are accepted (any other is 400); p4-adoption-bau.spec.ts adds a group in the UI and checks the API refusal of a stance outside the list.")
r("REQ-PB-071",[A+"adoption/indicators.ts",WK+"src/handlers/adoption.ts",W+"adoption/IndicatorsPage.tsx",T+"adoption/indicators.test.ts",WK+"test/integration/adoption-below-trajectory.test.ts",Q+"a11-adoption.test.ts",A33,QAC,M],
 "A11 is asserted by a11-adoption.test.ts: GET /adoption-indicator-templates lists exactly the seven B0109-B0115 indicators by name, in order; a below-trajectory actual creates a corrective intervention and an on-trajectory one creates none.")
r("REQ-PB-072",[A+"adoption/training.ts",A+"adoption/assessments.ts",A+"adoption/indicators.ts","packages/shared/src/adoption/measures.ts","packages/shared/src/adoption/measures.test.ts",W+"adoption/TrainingPage.tsx",T+"adoption/indicators.test.ts",Q+"a11-adoption.test.ts",A33,QAC,M],
 "A11 is asserted by a11-adoption.test.ts and indicators.test.ts: with 100% training completion and no proficiency observation, proficiency is unknown with value null (never 0) and not adopted.")
r("REQ-PB-073",[A+"adoption/register.ts",W+"adoption/ChampionConstraints.tsx",W+"decisions/DecisionsPage.tsx",T+"adoption/champion-constraints.test.ts",T+"adoption/stakeholder-groups.test.ts",Q+"a11-adoption.test.ts","apps/web/e2e/p4-adoption-bau.spec.ts",A33,QAC,M],
 "A01/A11 are asserted by a11-adoption.test.ts and champion-constraints.test.ts: a champion's constraint links to a T04 decision and is listed on that decision (and not on another), and a non-champion gets 403; p4-adoption-bau.spec.ts shows it on the decision page.")
r("REQ-PB-074",[A+"benefits/lifecycle.ts",A+"benefits/register-rules.test.ts",W+"benefits/BenefitPage.tsx",T+"benefits/lifecycle.test.ts",Q+"a11-value-closure.test.ts",A29,QAC,M],
 "A04/A10/A11 are asserted by a11-value-closure.test.ts 'REQ-PB-074': without the Plan outputs a benefit cannot move towards Measure (422 benefit.plan_outputs_missing), and Sustain without a BAU owner and control cadence is 422 benefit.sustain_outputs_missing, still 422 with the owner only and 200 with both; also lifecycle.test.ts.")
r("REQ-PB-075",[A+"benefits/register.ts",A+"benefits/values.ts",A+"benefits/totals.ts",W+"benefits/BenefitsPage.tsx",W+"benefits/benefits.test.tsx",T+"benefits/register.test.ts",Q+"a10-benefit-integrity.test.ts",Q+"a04-a05-a10-partials.test.ts",A29,A30,QAA,QAB,M],
 "A10 is asserted by a04-a05-a10-partials.test.ts (the T14 row carries all ten columns, API and DB) and a10-benefit-integrity.test.ts 'REQ-PB-075, REQ-S08-016' (a submitted 250000.10 is labelled submitted/pending and the validated total stays 0 until Finance approves); also register.test.ts 'listBenefits: the T14 register'.")
r("REQ-PB-076",[A+"benefits/register.ts",A+"benefits/totals.ts",A+"reporting/dashboards/finance.ts",W+"benefits/Totals.tsx",T+"benefits/totals.test.ts",T+"benefits/register.test.ts",Q+"a10-benefit-integrity.test.ts",A29,A30,QAA,M],
 "A10 is asserted by a10-benefit-integrity.test.ts 'REQ-PB-076': a CX benefit with Value n/a leaves every SAR figure byte-identical, increments nonFinancialCount and adds no SAR line (never counted as zero); also totals.test.ts and register.test.ts.")
r("REQ-PB-078",[A+"raid/register.ts",A+"raid/dependency-port.ts",A+"workflows/t08-dependencies.ts",W+"raid/RaidPage.tsx",T+"raid/dependency-entries.test.ts",T+"raid/register.test.ts",A31,M],
 "dependency-entries.test.ts 'A01: editing a dependency's owner in T08 changes the same RAID entry; there is no second copy' asserts one canonical row; register.test.ts asserts that the integrated RAID and decision log reads the canonical rows.")
r("REQ-PB-079",[A+"raid/register.ts",A+"raid/raid.test.ts","packages/shared/src/schemas/raid.ts",W+"raid/raid.test.tsx",T+"raid/register.test.ts",A31,M],
 "register.test.ts 'T15 RAID register: the nine columns and the Type rule' asserts that all nine T15 columns persist and that a Type outside Risk/Assumption/Issue/Dependency is 400 raid.type_invalid at /type; unit raid.test.ts.")
r("REQ-PB-080",[A+"raid/register.ts",A+"raid/raid.test.ts",T+"raid/register.test.ts",T+"raid/dependency-entries.test.ts",A31,M],
 "register.test.ts 'T15 Probability (REQ-PB-080)' asserts that an Issue with Probability H is 422 and a Risk without Probability is 422; dependency-entries.test.ts asserts that a Dependency entry has no Probability.")
r("REQ-PB-081",[A+"governance/executive-decisions.ts",W+"executive-decisions/ExecutiveDecisionsPage.tsx",T+"governance/executive-decisions.test.ts",Q+"a09-decision-escalation.test.ts","e2e/a08-a09-gates-decisions.spec.ts",A32,QAB,M],
 "A09 is asserted by a09-decision-escalation.test.ts: T16 persists all nine columns, and a decision whose Outcome is recorded is closed and leaves the overdue list; executive-decisions.test.ts at API level; e2e/a08-a09-gates-decisions.spec.ts renders the nine columns in en and ar.")
r("REQ-PB-082",[A+"governance/blocker-escalation.ts",A+"governance/escalation-rules.ts",WK+"src/handlers/escalations.ts",WK+"test/integration/blocker-escalation.test.ts",T+"governance/blocker-status.test.ts",Q+"a09-decision-escalation.test.ts",A32,QAB,M],
 "A09/A13 are asserted by a09-decision-escalation.test.ts 'N = 2' and the worker blocker-escalation.test.ts: a blocker red in two consecutive cycles produces exactly one open T16 ask with a decision, owner and deadline, and re-running the consumer or the scan creates no duplicate.")
r("REQ-PB-083",[A+"sustainment/handovers.ts",WK+"src/handlers/sustainment.ts",W+"bau/HandoverPage.tsx",T+"sustainment/handovers.test.ts",WK+"test/integration/sustainment-scans.test.ts",Q+"a11-bau-sustain.test.ts","apps/web/e2e/p4-adoption-bau.spec.ts",A34,QAC,M],
 "A11/A13 are asserted by a11-bau-sustain.test.ts: the receiving owner's acceptance creates exactly one review and one My Work task for the BAU owner, a repeated accept is 422, the scans add nothing, and the scan at the review's window schedules the following review once; also handovers.test.ts and sustainment-scans.test.ts.")
r("REQ-PB-084",[A+"sustainment/improvement.ts",W+"improvement/ImprovementPage.tsx",W+"bau/sustain.test.tsx",T+"sustainment/improvement.test.ts",Q+"a11-bau-sustain.test.ts",A34,QAC,M],
 "A11 is asserted by a11-bau-sustain.test.ts: G6 lists the continuous-improvement backlog and the G6 snapshot carries the item, and after closure the CI item is still listed and readable; also improvement.test.ts.")
r("REQ-PB-085",[A+"raid/corrective-cases.ts",A+"raid/corrective-rules.ts",WK+"src/handlers/raid.ts",WK+"src/handlers/benefits.ts",WK+"test/integration/raid-corrective.test.ts",T+"raid/corrective-cases.test.ts",Q+"a11-value-closure.test.ts",A31,QAC,M],
 "A04/A11/A13 are asserted by a11-value-closure.test.ts: two below-plan validated values and a redelivery leave exactly one open case for the benefit, and under a two-cycle rule real red actuals give no case in cycle 1, one case in cycle 2 and the same case updated in cycle 3; also the worker raid-corrective.test.ts.")
r("REQ-DLV-036",[Q+"a04-kpi-propagation.test.ts",Q+"a09-decision-escalation.test.ts",Q+"a10-benefit-integrity.test.ts",Q+"a11-adoption.test.ts",Q+"a11-value-closure.test.ts",Q+"a11-bau-sustain.test.ts","docs/delivery/test-evidence/DG4/qa/T-DG4-QA-C-authoring/logs/dlv-036-a04-a09-a10-a11.log",QAC,M,"docs/architecture/p4-plan.md"],
 "the A04, A09, A10 and A11 executable suites exist, passed 81/81 together in QA-C's REQ-DLV-036 run (dlv-036-a04-a09-a10-a11.log, exit 0), and passed in the merged-tree integration run at dca6b64 (1919/1919, code identical to this base). The run on the frozen DG4 candidate itself is a review-time check that has not happened yet.")
r("REQ-S03-001",[A+"portfolio/structure.ts",W+"traceability/StructurePages.tsx",T+"reporting/bu-scope.test.ts",T+"portfolio/structure.test.ts","apps/web/e2e/p4-traceability.spec.ts",A38,M],
 "A02/A12 are asserted by bu-scope.test.ts 'REQ-S03-001': two transformations in different business units are listed separately, each in its own business unit, and a user scoped to one business unit cannot list or read the other's transformation, portfolio rows or workstreams (404); structure.test.ts covers portfolios and workstreams.")
r("REQ-S03-002",[A+"sustainment/performance-areas.ts",A+"sustainment/controls.ts",WK+"src/handlers/sustainment.ts",T+"sustainment/performance-areas.test.ts",WK+"test/integration/sustainment-scans.test.ts",Q+"a11-bau-sustain.test.ts",A34,QAC,M],
 "A11 is asserted by a11-bau-sustain.test.ts: after the transformation is closed, its performance area's next review task is created on time for the BAU owner and the area's KPI still accepts an actual; also performance-areas.test.ts 'areas outlive their transformation' and sustainment-scans.test.ts.")
r("REQ-S03-003",[A+"sustainment/status-model.ts",A+"sustainment/closure.ts",W+"closure/ClosurePage.tsx",T+"sustainment/status-model.test.ts",T+"sustainment/closure.test.ts",Q+"a11-value-closure.test.ts","apps/web/e2e/p4-gates-closure.spec.ts",A34,QAC,M],
 "A11 is asserted by a11-value-closure.test.ts: setting delivery to Complete leaves adoption, value and closure exactly as they were; closing while validated value is pending is 422 invalid-transition; with an approved transition decision the closure is accepted.")
r("REQ-S03-004",[A+"workflows/scale.ts",A+"workflows/g5.ts",W+"gates/ScaleRisk.tsx",T+"workflows/scale.test.ts",Q+"a08-gate-controls.test.ts",T+"registers.test.ts","apps/web/e2e/p4-change-phases.spec.ts",A35,QAB,M],
 "A08 is asserted by a08-gate-controls.test.ts: a scale transition before G5 approval is 422 invalid-transition gate.g5_not_approved naming G5, and after approval scaling inside the scope succeeds; also scale.test.ts. The A02 'Design-phase draft can be saved before G2' clause is not asserted by a DG4 test: it is proven implicitly by the DG2 registers.test.ts, which creates T03 gaps and T04 design decisions (201) in a world whose G2 is never approved.")
r("REQ-S03-005",[A+"reporting/modular.ts",A+"workflows/gates.ts","packages/shared/src/schemas/missing-links.ts",W+"traceability/ModularPage.tsx",T+"reporting/modular.test.ts",T+"workflows/modular-precondition.test.ts",Q+"a03-modular-entry.test.ts","e2e/a03-modular-entry.spec.ts",A38,QAC,M],
 "A03 is asserted by a03-modular-entry.test.ts: entering at Design, G2 is labelled 'inherited' (never Approved) with no gate decision, the prior approval is listed as a labelled inherited record, and a fabricated prior_approval is 422; the missing baseline and outcome link are flagged and G3 is refused until supplied or waived. e2e/a03-modular-entry.spec.ts shows this in en and ar.")
r("REQ-S03-006",[A+"reporting/traceability.ts",A+"reporting/impact.ts",W+"traceability/TracePanels.tsx",T+"reporting/traceability.test.ts",T+"reporting/allocation.test.ts",T+"reporting/impact.test.ts",Q+"a10-benefit-integrity.test.ts",A38,QAA,M],
 "traceability.test.ts asserts that one initiative links to two gaps and two KPIs (four edges); a10-benefit-integrity.test.ts and allocation.test.ts assert that an allocation link set of 110% is 422 trace_link.allocation_exceeds_total and 100% is accepted; impact.test.ts asserts that a KPI target change lists the linked benefits and the Outcomes/Value dashboards as affected.")
r("REQ-S03-008",[A+"reporting/my-work.ts",W+"my-work/MyWorkPage.tsx",W+"dashboards/MyWorkSections.tsx",T+"reporting/my-work.test.ts","apps/web/e2e/p4-dashboards.spec.ts",A37,M,E2E],
 "my-work.test.ts 'REQ-S03-008' asserts that a KPI owner with a due actual sees the kpi_update_due item under Missing updates with the period-entry link, and that another user's items never appear; p4-dashboards.spec.ts renders the sections in en and ar.")
r("REQ-S03-009",[A+"reporting/executive-overview.ts",A+"reporting/dashboards/drilldown.ts",W+"executive-overview/ExecutiveOverviewPage.tsx",T+"reporting/dashboards.test.ts",Q+"a04-kpi-propagation.test.ts","apps/web/e2e/p4-dashboards.spec.ts",A37,QAA,M],
 "A04 is asserted by a04-kpi-propagation.test.ts (real worker): after an accepted KPI actual, the overview's Outcomes area shows the new actual on exactly one item and the outcomes.kpi_status drill-down lists that kpi_actual; also dashboards.test.ts 'REQ-S03-009'.")
r("REQ-S03-011",[A+"reporting/workspace-header.ts","apps/web/src/components/WorkspaceHeader.tsx",W+"dashboards/dashboards.test.tsx",T+"reporting/workspace-header.test.ts","apps/web/e2e/p4-dashboards.spec.ts",A37,M,E2E],
 "workspace-header.test.ts asserts that the eight elements are present, each Unknown where data is missing; p4-dashboards.spec.ts test 1 clicks the header's RAID link once and lands on /transformations/{id}/raid filtered to that transformation, in chromium-en and chromium-ar.")
r("REQ-S04-001",[A+"workflows/phase-steps.ts",W+"phases/PhasesPage.tsx",W+"phases/phases.test.tsx",T+"workflows/phases.test.ts","apps/web/e2e/p4-change-phases.spec.ts",A35,M],
 "phases.test.ts 'guided phase steps (REQ-S04-001)' asserts that each of the six phases shows steps with required evidence (en and ar), owners (Unknown when unassigned) and a review queue, and that a step with an unmet completion rule cannot be put in review or accepted (422 phase_step.completion_rule_unmet, also not through SQL).")
r("REQ-S04-002",[A+"workflows/phase-steps.ts",A+"workflows/gates.ts",A+"workflows/g5.ts",A+"workflows/g6.ts",T+"workflows/phases.test.ts",T+"workflows/g5-g6.test.ts",Q+"a08-gate-controls.test.ts",A35,QAB,M],
 "A07/A08 are asserted by a08-gate-controls.test.ts 'snapshot and task independence': completing every Diagnose phase task leaves G1 Draft with no submission, and editing a record after submission does not change the snapshot shown to approvers; also phases.test.ts and g5-g6.test.ts.")
r("REQ-S04-007",[A+"workflows/g5.ts",A+"workflows/scale.ts",W+"gates/GateP4.tsx",T+"workflows/scale.test.ts",T+"workflows/risk-dispositions.test.ts",Q+"a08-gate-controls.test.ts","apps/web/e2e/p4-gates-closure.spec.ts",A35,QAB,M],
 "A02/A08 are asserted by a08-gate-controls.test.ts: G5 with an open High-impact risk without resolution or approved disposition is refused listing 'Risk closure' (an approved disposition resolves it); a BO approval records the scale scope; scaling outside the scope is 422 scale.outside_approved_scope and inside it is 201.")
r("REQ-S04-008",[A+"workflows/g6.ts",A+"sustainment/gate-facts.ts",T+"workflows/g5-g6.test.ts",Q+"a08-gate-controls.test.ts",Q+"a11-bau-sustain.test.ts",A35,QAB,QAC,M],
 "A02/A11 are asserted by a08-gate-controls.test.ts: G6 without an accepted BAU handover is refused listing 'Ownership transfer', and a product G6 approval (API and its worker consumer) changes nothing under docs/delivery/ (fingerprinted); a11-bau-sustain.test.ts approves G6 natively with no DG record named.")
r("REQ-S04-009",[A+"workflows/gate-reviews.ts",W+"gates/GateP4.tsx",W+"gates/g5-g6.test.tsx",T+"workflows/gate-reviews.test.ts",Q+"a08-gate-controls.test.ts",A35,QAB,M],
 "A08 is asserted by a08-gate-controls.test.ts: a criterion review persists all nine fields (API and DB), and a gate decision without rationale is refused (400 at /rationale) with nothing written; also gate-reviews.test.ts.")
r("REQ-S04-010",[A+"workflows/gate-reviews.ts",A+"workflows/gates.ts",T+"workflows/gate-reviews.test.ts",Q+"a08-gate-controls.test.ts",A35,QAB,M],
 "A08 is asserted by a08-gate-controls.test.ts: the seven statuses exist, a direct Draft -> Approved is refused, and every transition (Draft -> Submitted -> Under Review -> Changes Requested -> ... -> Approved) writes an audit event. QA-B notes that the refusal is 409 gate.submission_superseded rather than 422; the test pins a refusal with the matching problem type.")
r("REQ-S04-012",[A+"workflows/gate-exceptions.ts",A+"workflows/gates.ts",W+"gates/GateP4.tsx",T+"workflows/gate-exceptions.test.ts",Q+"a08-gate-controls.test.ts","e2e/a08-a09-gates-decisions.spec.ts",A35,QAB,M],
 "A08 is asserted by a08-gate-controls.test.ts: the gate lists the missing items (canSubmit false); with one missing mandatory item the 422 lists exactly that item; with a valid exception the submission succeeds and its snapshot records the exception. e2e/a08-a09-gates-decisions.spec.ts shows the page in en and ar.")
r("REQ-S04-013",[A+"workflows/gate-exceptions.ts",WK+"src/handlers/gates.ts",T+"workflows/gate-exceptions.test.ts",WK+"test/integration/gates.test.ts",Q+"a08-gate-controls.test.ts",A35,QAB,M],
 "A08 is asserted by a08-gate-controls.test.ts: a waiver without an expiry or a compensating action is refused with nothing written, and after expiry the covered item is reported missing again and blocks submission. The expiry uses the product's setGateExceptionClock seam, because the server clock cannot be set through the API.")
r("REQ-S04-014",[A+"workflows/change-requests.ts",A+"workflows/impact.ts",A+"kpi/benefit-formulas.ts",W+"change-requests/ChangeRequestsPage.tsx",W+"change-requests/change-requests.test.tsx",T+"workflows/change-requests.test.ts",T+"workflows/impact.test.ts",A36,M],
 "change-requests.test.ts 'REQ-S04-014' asserts that a new version of an approved G4 benefit formula creates exactly one benefit_logic change request routed to Finance, and that the G4 decision and snapshot rows stay byte-identical before and after. Partial (D-114): proven by API integration tests and stubbed web tests (change-requests.test.tsx) only, not on the real-stack e2e.")
r("REQ-S07-001",[A+"kpi/kpi-definitions.ts",A+"kpi/kpi-versions.ts",T+"kpi-p4/versions.test.ts",A27,M],
 "versions.test.ts 'REQ-S07-001' asserts that a complete active version reads back every listed dictionary field; a create without polarity or unit is 400; a version without an aggregation rule stays draft and its activation is 422 kpi_version.aggregation_rule_required.")
r("REQ-S07-002",["packages/shared/src/kpi/measures.ts","packages/shared/src/kpi/measures.test.ts","packages/shared/src/kpi/a05.test.ts","tests/qa/unit/a05-calc-units.test.ts",Q+"a05-calculation-correctness.test.ts",A28,QAA,UNIT,M],
 "A05 unit tests (a05-calc-units.test.ts and packages/shared/src/kpi/a05.test.ts) assert higher-better 80 vs 90 adverse, lower-better 80 vs 90 favourable, band 5-10 with 12 outside, and a binary milestone not achieved by its due date adverse; the API suite a05-calculation-correctness.test.ts repeats them (adverse asserted as amber or red).")
r("REQ-S07-003",[A+"kpi/actuals.ts",A+"kpi/reporting-periods.ts",W+"kpi/KpiActualPage.tsx",T+"kpi-p4/actuals.test.ts",A27,M],
 "actuals.test.ts 'REQ-S07-003' asserts that a second actual for the same KPI, scope and period is value version 2 of the same row, never a duplicate row.")
r("REQ-S07-004",["packages/shared/src/kpi/change.ts","packages/shared/src/kpi/periods.ts","packages/shared/src/kpi/change.test.ts","tests/qa/unit/a05-calc-units.test.ts",Q+"a05-calculation-correctness.test.ts",A28,QAA,UNIT,M],
 "A05 is asserted by a05-calc-units.test.ts (+2.0 pp and +20%; YTD 10.1+20.2+30.3 = 60.6) and a05-calculation-correctness.test.ts (0.10 -> 0.12 labelled pp with variance 0.02 and ratio 0.2; the cumulative evaluation equals the sum of the period flows).")
r("REQ-S07-005",["packages/shared/src/kpi/change.ts","packages/shared/src/kpi/status.ts","packages/shared/src/kpi/periods.ts","tests/qa/unit/a05-calc-units.test.ts",Q+"a05-calculation-correctness.test.ts",T+"kpi-p4/status.test.ts",T+"kpi-p4/periods.test.ts",A28,QAA,M],
 "A05 is asserted by a05-calculation-correctness.test.ts (a zero denominator gives a null result with formula.division_by_zero, never 0) and a05-calc-units.test.ts (Not computable, negative baseline flagged, 4 vs 5 weeks not comparable); status.test.ts 'comparability' covers Not comparable through the API. The negative-baseline flag is asserted at unit level only.")
r("REQ-S07-006",["packages/shared/src/kpi/status.ts","packages/shared/src/kpi/aggregate.ts",A+"kpi/kpi-status.ts",W+"kpi/KpiPage.tsx",W+"kpi/kpi.test.tsx",T+"kpi-p4/status.test.ts",T+"kpi-p4/pipeline.test.ts",Q+"a05-calculation-correctness.test.ts",Q+"a04-kpi-propagation.test.ts",A28,QAA,M],
 "A05 is asserted by a05-calculation-correctness.test.ts: a KPI with no actual for the period renders Unknown (labelled), never 0 or green, and a roll-up with a scope that reported before but is missing now is Unknown, not a sum with 0; kpi.test.tsx asserts grey, labelled Unknown in the UI.")
r("REQ-S07-007",[A+"kpi/rag-thresholds.ts",A+"kpi/trajectories.ts","packages/shared/src/kpi/rag.ts",WK+"src/handlers/kpi.ts",T+"kpi-p4/thresholds.test.ts",T+"kpi-p4/pipeline.test.ts",Q+"a05-calculation-correctness.test.ts",Q+"a04-a05-a10-partials.test.ts",A27,A28,QAA,QAB,M],
 "A04/A05 are asserted by a04-a05-a10-partials.test.ts (with every Diagnose phase task and every action complete, an actual below the red threshold is Red) and a05-calculation-correctness.test.ts (a new threshold version produces exactly one threshold_changed run and recomputes RAG). As designed (ADR-0027 §8, ADR-0028 §5), a threshold change recomputes the current period only (QA-A observation 3).")
r("REQ-S07-008",[A+"kpi/kpi-status.ts","packages/shared/src/kpi/status.ts",W+"kpi/KpiPage.tsx",W+"kpi/kpi.test.tsx",T+"kpi-p4/status.test.ts","apps/web/e2e/p4-kpi.spec.ts",A28,M,E2E],
 "status.test.ts 'the KPI panel (REQ-S07-008)' asserts the seven elements and an explanation naming the threshold version; kpi.test.tsx and p4-kpi.spec.ts (chromium-en and chromium-ar) render the seven elements with the explanation.")
r("REQ-S07-009",[A+"kpi/rag-overrides.ts",A+"kpi/kpi-status.ts",T+"kpi-p4/overrides.test.ts",T+"kpi-p4/status.test.ts",A27,A28,M],
 "overrides.test.ts asserts that an override without reason, evidence or expiry is 422 with nothing written, an unauthorized user (KDS, AUD, ADM-only) gets 403, the calculated RAG is preserved, and after expiry the override is no longer in force; status.test.ts asserts that the calculated RAG displays again.")
r("REQ-S07-010",["packages/shared/src/kpi/aggregate.ts","packages/shared/src/kpi/aggregate.test.ts","tests/qa/unit/a05-calc-units.test.ts",Q+"a05-calculation-correctness.test.ts",T+"kpi-p4/pipeline.test.ts",A28,QAA,M],
 "A05 is asserted by a05-calculation-correctness.test.ts: 1/10 and 9/10 roll up to 0.5, and a discriminating 1/10 and 80/90 rolls up to 0.81 (weighted, not the 0.494 mean, because the row's own example cannot tell the two apart); an actual in USD on a SAR KPI and SAR + USD in a formula are 422.")
r("REQ-S07-011",[A+"kpi/kpi-formulas.ts",A+"kpi/kpi-versions.ts","packages/shared/src/kpi/formula-binding.ts",T+"kpi-p4/formulas.test.ts",Q+"a05-calculation-correctness.test.ts",A28,QAA,M],
 "A05 is asserted by a05-calculation-correctness.test.ts and formulas.test.ts: with KPI A = B + 1 active, B = A * 2 is 422 kpi_formula.circular; SAR + count is 422.")
r("REQ-S07-012",[A+"kpi/actuals.ts",A+"kpi/accept-pipeline.ts",W+"kpi/KpiUpdatePage.tsx",T+"kpi-p4/actuals.test.ts",Q+"a04-kpi-propagation.test.ts",A27,QAA,M],
 "A04 is asserted by a04-kpi-propagation.test.ts (real worker): on the review route a submitted actual creates no run and the status stays Unknown until accepted, then exactly one run; on the direct-accept route the actual is used at once (the first two A04 cases).")
r("REQ-S07-013",[A+"kpi/accept-pipeline.ts",A+"kpi/calculation-runs.ts",WK+"src/handlers/kpi.ts",WK+"test/integration/kpi-recalculate.test.ts",T+"kpi-p4/pipeline.test.ts",Q+"a04-kpi-propagation.test.ts",A27,QAA,M],
 "A04/A13 are asserted by a04-kpi-propagation.test.ts (real API, worker and PostgreSQL): one accept gives exactly one completed calculation run and one audit event, still 1/1 after the outbox and queues drain, and the linked dashboards show the new value once.")
r("REQ-S07-014",[A+"benefits/values.ts",A+"benefits/totals.ts",WK+"src/handlers/benefits.ts",WK+"test/integration/benefits-queue.test.ts",Q+"a04-kpi-propagation.test.ts",A30,QAA,M],
 "A04/A10 are asserted by a04-kpi-propagation.test.ts 'REQ-S07-014': after an accepted KPI actual, the linked benefit's submitted series is 100000 SAR while validated stays 0 and the transformation's validated total is unchanged; also benefits-queue.test.ts.")
r("REQ-S07-015",[A+"workflows/change-requests.ts",A+"workflows/impact.ts",W+"change-requests/Impact.tsx",W+"change-requests/change-requests.test.tsx",T+"workflows/change-requests.test.ts",T+"workflows/impact.test.ts",A36,M],
 "change-requests.test.ts 'REQ-S07-015' asserts that a KPI target change's preview lists the bound benefit and the approved G2 decision, a direct activation is 422, and after approval v2 is active while v1 stays readable (superseded). Partial (D-114): proven by API integration tests and stubbed web tests only, not on the real-stack e2e.")
r("REQ-S07-017",[A+"kpi/actuals.ts",A+"kpi/downstream.ts",A+"benefits/downstream.ts",W+"kpi/KpiUpdatePage.tsx",W+"kpi/kpi.test.tsx",T+"kpi-p4/actuals.test.ts",Q+"a04-kpi-propagation.test.ts","e2e/a04-kpi-update.spec.ts","docs/delivery/test-evidence/DG4/qa/T-DG4-QA-A-authoring/logs/e2e-final3.log",A27,QAA],
 "A04/A20 are asserted by e2e/a04-kpi-update.spec.ts (chromium-en and chromium-ar, real stack): a keyboard-only user completes the update in exactly four steps, axe finds 0 serious or critical issues, and the confirmation lists a dashboard item and 'Finance review pending'; the API side is in a04-kpi-propagation.test.ts.")
