import { pgTable, uuid, text, integer, jsonb, varchar, date, boolean, unique, uniqueIndex, index } from 'drizzle-orm/pg-core';
import {
  pk,
  orgIdCol,
  projectIdCol,
  createdAt,
  updatedAt,
  createdBy,
  versionCol,
  isDemo,
  ts,
  projectFk,
  moneyCols,
  classification,
  perimeterItemType,
  perimeterDisposition,
  transferStatus,
  agreementStage,
  contractTransferClass,
  consentStatus,
  approvalRegisterCategory,
  applicabilityStatus,
  requirementStatus,
  tsaStatus,
  readinessArea,
  readinessStatus,
  goNoGo,
  cutoverStatus,
  verificationStatus,
  roleKey,
} from './_common';
import { project, site, workstream, legalEntity } from './portfolio';
import { appUser } from './identity';

export const agreement = pgTable(
  'agreement',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    /** Agreement type label as it appears in the source (e.g. "ATA", "TSA", "MSA"); never auto-expanded. */
    kindLabel: varchar('kind_label', { length: 64 }).notNull(),
    kindExpansion: text('kind_expansion'), // proposed expansion, labelled as such
    kindExpansionConfirmed: boolean('kind_expansion_confirmed').notNull().default(false),
    title: text('title').notNull(),
    parties: jsonb('parties').$type<{ legalEntityId?: string; name: string; role?: string }[]>().notNull().default([]),
    scope: text('scope'),
    ownerUserId: uuid('owner_user_id').references(() => appUser.id),
    legalReviewerUserId: uuid('legal_reviewer_user_id').references(() => appUser.id),
    currentDraftVersion: varchar('current_draft_version', { length: 32 }),
    stage: agreementStage('stage').notNull().default('identified'),
    outstandingIssues: text('outstanding_issues'),
    signingDate: date('signing_date', { mode: 'string' }),
    effectiveDate: date('effective_date', { mode: 'string' }),
    renewalDate: date('renewal_date', { mode: 'string' }),
    expiryDate: date('expiry_date', { mode: 'string' }),
    obligations: text('obligations'),
    executedDocumentId: uuid('executed_document_id'),
    classification: classification('classification').notNull().default('confidential'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [unique('agreement_pid_uq').on(t.projectId, t.id), uniqueIndex('agreement_code_uq').on(t.projectId, t.code)],
);

/** Transaction perimeter register (spec §7.1). */
export const perimeterItem = pgTable(
  'perimeter_item',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    type: perimeterItemType('type').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    siteId: uuid('site_id'),
    workstreamId: uuid('workstream_id'),
    currentEntityId: uuid('current_entity_id').references(() => legalEntity.id),
    targetEntityId: uuid('target_entity_id').references(() => legalEntity.id),
    disposition: perimeterDisposition('disposition').notNull().default('pending'),
    legalOwner: text('legal_owner'),
    operator: text('operator'),
    economicBeneficiary: text('economic_beneficiary'),
    plannedEffectiveDate: date('planned_effective_date', { mode: 'string' }),
    actualEffectiveDate: date('actual_effective_date', { mode: 'string' }),
    transferMechanism: text('transfer_mechanism'), // proposed
    agreementId: uuid('agreement_id'),
    ...moneyCols('reference_value'),
    referenceValueSource: text('reference_value_source'),
    consentRequired: boolean('consent_required').notNull().default(false),
    dependencies: text('dependencies'),
    risks: text('risks'),
    transferStatus: transferStatus('transfer_status').notNull().default('not_started'),
    acceptanceEvidenceNote: text('acceptance_evidence_note'),
    inApprovedBaseline: boolean('in_approved_baseline').notNull().default(false),
    verificationStatus: verificationStatus('verification_status').notNull().default('proposed'),
    classification: classification('classification').notNull().default('confidential'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('perimeter_item_pid_uq').on(t.projectId, t.id),
    uniqueIndex('perimeter_item_code_uq').on(t.projectId, t.code),
    projectFk('perimeter_item_site_fk', t.projectId, t.siteId, site),
    projectFk('perimeter_item_ws_fk', t.projectId, t.workstreamId, workstream),
    projectFk('perimeter_item_agreement_fk', t.projectId, t.agreementId, agreement),
    index('perimeter_item_status_idx').on(t.projectId, t.transferStatus),
  ],
);

export const transferRecord = pgTable(
  'transfer_record',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    perimeterItemId: uuid('perimeter_item_id').notNull(),
    fromStatus: transferStatus('from_status').notNull(),
    toStatus: transferStatus('to_status').notNull(),
    mechanism: text('mechanism'),
    effectiveDate: date('effective_date', { mode: 'string' }),
    note: text('note'),
    recordedBy: uuid('recorded_by').notNull(),
    recordedAt: createdAt(),
  },
  (t) => [projectFk('transfer_record_item_fk', t.projectId, t.perimeterItemId, perimeterItem), index('transfer_record_item_idx').on(t.perimeterItemId)],
);

/** Contract consent / novation position — also covers the Day-1 fallback for non-transferable contracts (AT-08). */
export const consent = pgTable(
  'consent',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    perimeterItemId: uuid('perimeter_item_id'),
    agreementId: uuid('agreement_id'),
    counterparty: text('counterparty').notNull(),
    contractRef: text('contract_ref'),
    transferClass: contractTransferClass('transfer_class').notNull().default('unknown'),
    classAssessedBy: text('class_assessed_by'), // specialist role/name — "Assessment pending" when null
    status: consentStatus('status').notNull().default('not_requested'),
    requestedOn: date('requested_on', { mode: 'string' }),
    grantedOn: date('granted_on', { mode: 'string' }),
    conditions: text('conditions'),
    dueDate: date('due_date', { mode: 'string' }),
    interimArrangement: text('interim_arrangement'),
    serviceAccountableUserId: uuid('service_accountable_user_id').references(() => appUser.id),
    billingAccountableUserId: uuid('billing_accountable_user_id').references(() => appUser.id),
    slaAccountableUserId: uuid('sla_accountable_user_id').references(() => appUser.id),
    remediationPlan: text('remediation_plan'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('consent_pid_uq').on(t.projectId, t.id),
    uniqueIndex('consent_code_uq').on(t.projectId, t.code),
    projectFk('consent_item_fk', t.projectId, t.perimeterItemId, perimeterItem),
    projectFk('consent_agreement_fk', t.projectId, t.agreementId, agreement),
  ],
);

/** Regulatory / external-party / internal approval register (spec §7.2). Applicability set by specialists. */
export const regulatoryRequirement = pgTable(
  'regulatory_requirement',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    category: approvalRegisterCategory('category').notNull(),
    authority: text('authority').notNull(), // as named in source, e.g. "CST" — not expanded without confirmation
    title: text('title').notNull(),
    description: text('description'),
    applicability: applicabilityStatus('applicability').notNull().default('assessment_pending'),
    applicabilityAssessedBy: text('applicability_assessed_by'),
    applicabilityNote: text('applicability_note'),
    status: requirementStatus('status').notNull().default('not_started'),
    ownerUserId: uuid('owner_user_id').references(() => appUser.id),
    submittedOn: date('submitted_on', { mode: 'string' }),
    decisionOn: date('decision_on', { mode: 'string' }),
    conditions: text('conditions'),
    validFrom: date('valid_from', { mode: 'string' }),
    validTo: date('valid_to', { mode: 'string' }),
    legalEntityId: uuid('legal_entity_id').references(() => legalEntity.id),
    gateKey: varchar('gate_key', { length: 16 }),
    verificationStatus: verificationStatus('verification_status').notNull().default('proposed'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [unique('regulatory_requirement_pid_uq').on(t.projectId, t.id), uniqueIndex('regulatory_requirement_code_uq').on(t.projectId, t.code)],
);

export const tsaService = pgTable(
  'tsa_service',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    name: text('name').notNull(),
    agreementId: uuid('agreement_id'),
    providerEntityId: uuid('provider_entity_id').references(() => legalEntity.id),
    recipientEntityId: uuid('recipient_entity_id').references(() => legalEntity.id),
    scope: text('scope'),
    dependentServices: text('dependent_services'),
    sla: text('sla'),
    metricMethod: text('metric_method'),
    chargeBasis: text('charge_basis'),
    ...moneyCols('charge'),
    startDate: date('start_date', { mode: 'string' }),
    endDate: date('end_date', { mode: 'string' }),
    extensionTerms: text('extension_terms'),
    terminationTerms: text('termination_terms'),
    ownerUserId: uuid('owner_user_id').references(() => appUser.id),
    replacementService: text('replacement_service'),
    replacementAccepted: boolean('replacement_accepted').notNull().default(false),
    replacementAcceptedBy: uuid('replacement_accepted_by'),
    replacementAcceptedAt: ts('replacement_accepted_at'),
    exitMilestones: jsonb('exit_milestones').$type<{ title: string; dueDate?: string; done?: boolean }[]>().notNull().default([]),
    acceptanceEvidenceNote: text('acceptance_evidence_note'),
    residualRisks: text('residual_risks'),
    isEnduringArrangement: boolean('is_enduring_arrangement').notNull().default(false),
    status: tsaStatus('status').notNull().default('proposed'),
    escalationId: uuid('escalation_id'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('tsa_service_pid_uq').on(t.projectId, t.id),
    uniqueIndex('tsa_service_code_uq').on(t.projectId, t.code),
    projectFk('tsa_service_agreement_fk', t.projectId, t.agreementId, agreement),
  ],
);

export const cutoverPlan = pgTable(
  'cutover_plan',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    title: text('title').notNull(),
    siteId: uuid('site_id'),
    runbookDocumentId: uuid('runbook_document_id'),
    runbookSummary: text('runbook_summary'),
    windowStart: ts('window_start'),
    windowEnd: ts('window_end'),
    serviceImpact: text('service_impact'),
    accountableUserId: uuid('accountable_user_id').references(() => appUser.id),
    communicationsApproved: boolean('communications_approved').notNull().default(false),
    testingSummary: text('testing_summary'),
    rehearsalDone: boolean('rehearsal_done').notNull().default(false),
    contingencyPlan: text('contingency_plan'),
    rollbackPlan: text('rollback_plan'),
    goNoGo: goNoGo('go_no_go').notNull().default('pending'),
    goNoGoDecidedBy: uuid('go_no_go_decided_by'),
    goNoGoDecidedAt: ts('go_no_go_decided_at'),
    goNoGoRationale: text('go_no_go_rationale'),
    status: cutoverStatus('status').notNull().default('planning'),
    postTransitionAccepted: boolean('post_transition_accepted').notNull().default(false),
    postTransitionAcceptedBy: uuid('post_transition_accepted_by'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('cutover_plan_pid_uq').on(t.projectId, t.id),
    uniqueIndex('cutover_plan_code_uq').on(t.projectId, t.code),
    projectFk('cutover_plan_site_fk', t.projectId, t.siteId, site),
  ],
);

/** Day-1 readiness check (site/workstream checklist item with blocker flag and specialist sign-off). */
export const readinessCheck = pgTable(
  'readiness_check',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    area: readinessArea('area').notNull(),
    title: text('title').notNull(),
    titleAr: text('title_ar'),
    siteId: uuid('site_id'),
    workstreamId: uuid('workstream_id'),
    cutoverPlanId: uuid('cutover_plan_id'),
    mandatory: boolean('mandatory').notNull().default(true),
    blocker: boolean('blocker').notNull().default(false),
    status: readinessStatus('status').notNull().default('not_started'),
    signoffRole: roleKey('signoff_role'),
    signedOffBy: uuid('signed_off_by'),
    signedOffAt: ts('signed_off_at'),
    testResult: text('test_result'),
    failureContingency: text('failure_contingency'),
    dueDate: date('due_date', { mode: 'string' }),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('readiness_check_pid_uq').on(t.projectId, t.id),
    uniqueIndex('readiness_check_code_uq').on(t.projectId, t.code),
    projectFk('readiness_check_site_fk', t.projectId, t.siteId, site),
    projectFk('readiness_check_ws_fk', t.projectId, t.workstreamId, workstream),
    projectFk('readiness_check_cutover_fk', t.projectId, t.cutoverPlanId, cutoverPlan),
  ],
);

/** History of readiness test runs (a failed test stays visible even after a later pass). */
export const readinessTestRun = pgTable(
  'readiness_test_run',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    readinessCheckId: uuid('readiness_check_id').notNull(),
    result: readinessStatus('result').notNull(),
    note: text('note'),
    recordedBy: uuid('recorded_by').notNull(),
    recordedAt: createdAt(),
    seq: integer('seq').notNull().default(1),
  },
  (t) => [projectFk('readiness_test_run_check_fk', t.projectId, t.readinessCheckId, readinessCheck)],
);
