import { pgTable, uuid, text, integer, jsonb, varchar, date, boolean, numeric, unique, uniqueIndex, index } from 'drizzle-orm/pg-core';
import {
  pk,
  orgIdCol,
  projectIdCol,
  createdAt,
  updatedAt,
  createdBy,
  versionCol,
  isDemo,
  ts,
  projectFk,
  classification,
  partnerStage,
  ndaStatus,
  ddReleaseStatus,
  materiality,
  findingStatus,
  negotiationIssueStatus,
  closingKind,
  closingStatus,
  conditionKind,
  conditionStatus,
  closingDeliverableStatus,
  postCloseKind,
  postCloseStatus,
  fundsFlowStatus,
  approvalState,
  roleKey,
} from './_common';
import { project, legalEntity } from './portfolio';
import { appUser } from './identity';
import { agreement } from './carveout';

/** Partner (longlist/shortlist). No real default names: demo partners are fictional and flagged. */
export const partner = pgTable(
  'partner',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    name: text('name').notNull(),
    legalEntityId: uuid('legal_entity_id').references(() => legalEntity.id),
    stage: partnerStage('stage').notNull().default('identified'),
    shortlisted: boolean('shortlisted').notNull().default(false),
    ndaStatus: ndaStatus('nda_status').notNull().default('none'),
    ndaExecutedOn: date('nda_executed_on', { mode: 'string' }),
    outreachApprovedBy: uuid('outreach_approved_by'),
    outreachApprovedAt: ts('outreach_approved_at'),
    materialsAccessApprovedBy: uuid('materials_access_approved_by'),
    materialsAccessApprovedAt: ts('materials_access_approved_at'),
    criteriaScores: jsonb('criteria_scores').$type<{ criterion: string; weight: number; score: number | null; basis: 'fact' | 'judgment'; note?: string }[]>().notNull().default([]),
    conflictDisclosures: text('conflict_disclosures'),
    proposalSummary: text('proposal_summary'),
    factsVsJudgmentNote: text('facts_vs_judgment_note'),
    classification: classification('classification').notNull().default('strictly_confidential'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [unique('partner_pid_uq').on(t.projectId, t.id), uniqueIndex('partner_code_uq').on(t.projectId, t.code)],
);

/** Access-controlled partner / VDR room (also used for clean-team rooms). */
export const partnerRoom = pgTable(
  'partner_room',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    partnerId: uuid('partner_id'),
    name: text('name').notNull(),
    isCleanTeam: boolean('is_clean_team').notNull().default(false),
    classification: classification('classification').notNull().default('strictly_confidential'),
    createdAt: createdAt(),
    createdBy: createdBy(),
    version: versionCol(),
  },
  (t) => [unique('partner_room_pid_uq').on(t.projectId, t.id), projectFk('partner_room_partner_fk', t.projectId, t.partnerId, partner)],
);

/** Explicit, revocable room access grant — the only way into a room (an NDA alone grants nothing). */
export const roomGrant = pgTable(
  'room_grant',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    roomId: uuid('room_id').notNull(),
    userId: uuid('user_id').notNull().references(() => appUser.id),
    accessLevel: varchar('access_level', { length: 16 }).notNull().default('read'), // read | contribute | manage
    /** Room-scoped role (clean_team / external_partner_limited). Null = access under the user's project roles. */
    role: roleKey('role'),
    reason: text('reason').notNull(),
    grantedBy: uuid('granted_by').notNull(),
    grantedAt: createdAt(),
    expiresAt: ts('expires_at'),
    revokedAt: ts('revoked_at'),
    revokedBy: uuid('revoked_by'),
  },
  (t) => [projectFk('room_grant_room_fk', t.projectId, t.roomId, partnerRoom), index('room_grant_user_idx').on(t.userId)],
);

/** Ownership / contribution / governance scenario — versioned, never assumes control or percentages. */
export const dealScenario = pgTable(
  'deal_scenario',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    partnerId: uuid('partner_id'),
    name: text('name').notNull(),
    versionLabel: varchar('version_label', { length: 32 }).notNull(),
    ownership: jsonb('ownership').$type<{ party: string; percent: string | null; note?: string }[]>().notNull().default([]),
    contributions: jsonb('contributions').$type<{ party: string; description: string; amount?: string; currency?: string; unitScale?: number }[]>().notNull().default([]),
    governanceTerms: text('governance_terms'),
    approvalState: approvalState('approval_state').notNull().default('proposed'),
    approvedBy: uuid('approved_by'),
    approvedAt: ts('approved_at'),
    classification: classification('classification').notNull().default('strictly_confidential'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [unique('deal_scenario_pid_uq').on(t.projectId, t.id), projectFk('deal_scenario_partner_fk', t.projectId, t.partnerId, partner)],
);

export const negotiationIssue = pgTable(
  'negotiation_issue',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    partnerId: uuid('partner_id'),
    agreementId: uuid('agreement_id'),
    code: varchar('code', { length: 32 }).notNull(),
    issue: text('issue').notNull(),
    positions: jsonb('positions').$type<{ party: string; position: string }[]>().notNull().default([]),
    alternatives: text('alternatives'),
    requiredApproval: text('required_approval'),
    documentRef: text('document_ref'),
    status: negotiationIssueStatus('status').notNull().default('open'),
    classification: classification('classification').notNull().default('strictly_confidential'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('negotiation_issue_pid_uq').on(t.projectId, t.id),
    uniqueIndex('negotiation_issue_code_uq').on(t.projectId, t.code),
    projectFk('negotiation_issue_partner_fk', t.projectId, t.partnerId, partner),
    projectFk('negotiation_issue_agreement_fk', t.projectId, t.agreementId, agreement),
  ],
);

export const diligenceRequest = pgTable(
  'diligence_request',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    partnerId: uuid('partner_id'),
    roomId: uuid('room_id'),
    number: integer('number').notNull(),
    question: text('question').notNull(),
    domain: varchar('domain', { length: 32 }).notNull(), // legal | finance | tax | technical | commercial | hr | regulatory | other
    requesterLabel: text('requester_label'),
    assigneeUserId: uuid('assignee_user_id').references(() => appUser.id),
    dueDate: date('due_date', { mode: 'string' }),
    answerDraft: text('answer_draft'),
    evidenceDocumentIds: jsonb('evidence_document_ids').$type<string[]>().notNull().default([]),
    reviewerUserId: uuid('reviewer_user_id').references(() => appUser.id),
    releaseStatus: ddReleaseStatus('release_status').notNull().default('draft'),
    releaseApprovedBy: uuid('release_approved_by'),
    releasedAnswer: text('released_answer'), // frozen disclosed version
    releasedVersion: integer('released_version'),
    releasedAt: ts('released_at'),
    classification: classification('classification').notNull().default('strictly_confidential'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('diligence_request_pid_uq').on(t.projectId, t.id),
    uniqueIndex('diligence_request_number_uq').on(t.projectId, t.partnerId, t.number),
    projectFk('diligence_request_partner_fk', t.projectId, t.partnerId, partner),
    projectFk('diligence_request_room_fk', t.projectId, t.roomId, partnerRoom),
  ],
);

export const diligenceFinding = pgTable(
  'diligence_finding',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    partnerId: uuid('partner_id'),
    code: varchar('code', { length: 32 }).notNull(),
    title: text('title').notNull(),
    description: text('description'),
    materiality: materiality('materiality').notNull(),
    riskId: uuid('risk_id'),
    remediation: text('remediation'),
    valuationImplication: text('valuation_implication'),
    documentImplication: text('document_implication'),
    cpImplication: text('cp_implication'),
    status: findingStatus('status').notNull().default('open'),
    classification: classification('classification').notNull().default('strictly_confidential'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('diligence_finding_pid_uq').on(t.projectId, t.id),
    uniqueIndex('diligence_finding_code_uq').on(t.projectId, t.code),
    projectFk('diligence_finding_partner_fk', t.projectId, t.partnerId, partner),
  ],
);

/** A signing or closing event. Multiple closings supported via `sequence`. */
export const closing = pgTable(
  'closing',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    partnerId: uuid('partner_id'),
    kind: closingKind('kind').notNull(),
    sequence: integer('sequence').notNull().default(1),
    name: text('name').notNull(),
    targetDate: date('target_date', { mode: 'string' }),
    status: closingStatus('status').notNull().default('planned'),
    confirmedBy: uuid('confirmed_by'),
    confirmedAt: ts('confirmed_at'),
    confirmationAuthority: text('confirmation_authority'),
    confirmationDecisionId: uuid('confirmation_decision_id'),
    readinessSnapshot: jsonb('readiness_snapshot').$type<Record<string, unknown>>(),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('closing_pid_uq').on(t.projectId, t.id),
    uniqueIndex('closing_seq_uq').on(t.projectId, t.kind, t.sequence),
    projectFk('closing_partner_fk', t.projectId, t.partnerId, partner),
  ],
);

/** Condition precedent / subsequent. */
export const closingCondition = pgTable(
  'closing_condition',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    closingId: uuid('closing_id'),
    kind: conditionKind('kind').notNull().default('condition_precedent'),
    reference: varchar('reference', { length: 32 }).notNull(),
    title: text('title').notNull(),
    description: text('description'),
    ownerUserId: uuid('owner_user_id').references(() => appUser.id),
    parties: text('parties'),
    blocking: boolean('blocking').notNull().default(true),
    waivable: boolean('waivable').notNull().default(false),
    waiverAuthorityRole: roleKey('waiver_authority_role'),
    waiverAuthorityNote: text('waiver_authority_note'),
    validTo: date('valid_to', { mode: 'string' }),
    longStopDate: date('long_stop_date', { mode: 'string' }),
    status: conditionStatus('status').notNull().default('open'),
    verifiedBy: uuid('verified_by'),
    verifiedAt: ts('verified_at'),
    waiverId: uuid('waiver_id'),
    gateKey: varchar('gate_key', { length: 16 }),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('closing_condition_pid_uq').on(t.projectId, t.id),
    uniqueIndex('closing_condition_ref_uq').on(t.projectId, t.reference),
    projectFk('closing_condition_closing_fk', t.projectId, t.closingId, closing),
  ],
);

export const closingDeliverable = pgTable(
  'closing_deliverable',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    closingId: uuid('closing_id').notNull(),
    title: text('title').notNull(),
    responsibleParty: text('responsible_party'),
    ownerUserId: uuid('owner_user_id').references(() => appUser.id),
    status: closingDeliverableStatus('status').notNull().default('pending'),
    documentId: uuid('document_id'),
    verifiedBy: uuid('verified_by'),
    verifiedAt: ts('verified_at'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [unique('closing_deliverable_pid_uq').on(t.projectId, t.id), projectFk('closing_deliverable_closing_fk', t.projectId, t.closingId, closing)],
);

/** Funds-flow tracking only — the platform never executes payments. */
export const fundsFlowItem = pgTable(
  'funds_flow_item',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    closingId: uuid('closing_id').notNull(),
    description: text('description').notNull(),
    payer: text('payer').notNull(),
    payee: text('payee').notNull(),
    amount: numeric('amount', { precision: 20, scale: 4 }),
    currency: varchar('currency', { length: 3 }),
    unitScale: integer('unit_scale'),
    status: fundsFlowStatus('status').notNull().default('planned'),
    confirmedBy: uuid('confirmed_by'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    version: versionCol(),
  },
  (t) => [projectFk('funds_flow_closing_fk', t.projectId, t.closingId, closing)],
);

export const postCloseObligation = pgTable(
  'post_close_obligation',
  {
    id: pk(),
    orgId: orgIdCol(),
    projectId: projectIdCol().references(() => project.id),
    code: varchar('code', { length: 32 }).notNull(),
    kind: postCloseKind('kind').notNull(),
    title: text('title').notNull(),
    ownerUserId: uuid('owner_user_id').references(() => appUser.id),
    dueDate: date('due_date', { mode: 'string' }),
    status: postCloseStatus('status').notNull().default('open'),
    evidenceNote: text('evidence_note'),
    verifiedBy: uuid('verified_by'),
    verifiedAt: ts('verified_at'),
    closingId: uuid('closing_id'),
    isDemo: isDemo(),
    createdAt: createdAt(),
    createdBy: createdBy(),
    updatedAt: updatedAt(),
    version: versionCol(),
  },
  (t) => [
    unique('post_close_obligation_pid_uq').on(t.projectId, t.id),
    uniqueIndex('post_close_obligation_code_uq').on(t.projectId, t.code),
    projectFk('post_close_obligation_closing_fk', t.projectId, t.closingId, closing),
  ],
);
