import { defineConfig } from 'drizzle-kit';

// Migrations are generated by the lead (single migration owner) and applied with the OWNER role.
export default defineConfig({
  dialect: 'postgresql',
  schema: './src/schema/index.ts',
  out: './migrations',
  dbCredentials: {
    url: process.env.DATABASE_MIGRATION_URL ?? 'postgres://hub_owner:hub_dev_only@127.0.0.1:5432/hub_dev',
  },
  strict: true,
  verbose: false,
});
