// Response types of the P1, P2 and P3 contracts (docs/api/openapi.yaml), taken from the shared zod mirrors so the web and the
// API agree on one definition (ADR-0007).
import type { z } from "zod";
import type {
  AuditEvent,
  BusinessUnit,
  Me,
  Organization,
  Role,
  RoleAssignment,
  Transformation,
  User,
  permissionEntry,
  baseline,
  capabilityHeatmapEntry,
  charter,
  charterVersion,
  charterView,
  decision,
  decisionOption,
  dependency,
  diagnosticFinding,
  diagnosticItem,
  evidence,
  evidenceLink,
  gateCriterionEvaluation,
  gateDecision,
  gateSubmission,
  gateSubmissionView,
  gateView,
  journey,
  journeyPainPoint,
  kpiDefinition,
  methodologyCatalogue,
  northStar,
  outcome,
  outcomeKpi,
  strategicGuardrail,
  roleAccountability,
  teamAssignment,
  tomCanvasCellView,
  tomGap,
  tomWorkshop,
  tomWorkshopItem,
  valuePool,
  workstreamOutput,
  actionItem,
  deliverableList,
  fundingDecisionPage,
  gateDispensationPage,
  initiativePage,
  portfolioSelectionPage,
} from "@mth/shared/schemas";

export type { AuditEvent, BusinessUnit, Me, Organization, Role, RoleAssignment, Transformation, User };
export type PermissionEntry = z.infer<typeof permissionEntry>;

export interface Page<T> {
  readonly items: readonly T[];
  readonly nextCursor: string | null;
}

export type TransformationSort =
  | "updatedAt:desc"
  | "updatedAt:asc"
  | "name:asc"
  | "name:desc"
  | "code:asc"
  | "code:desc";

// ------------------------------------------------------------------------------------------------ P2 (DG2)
// Response types of the P2 contract, inferred from the shared zod mirrors (BE + KBE; docs/api/openapi.yaml).

export type MethodologyCatalogue = z.infer<typeof methodologyCatalogue>;
export type DiagnosticDimension = MethodologyCatalogue["diagnosticDimensions"][number];
export type DiagnosticWorkstream = MethodologyCatalogue["diagnosticWorkstreams"][number];
export type TomDimension = MethodologyCatalogue["tomDimensions"][number];
export type GateDefinition = MethodologyCatalogue["gateDefinitions"][number];
export type CharterScopeCheckDefinition = MethodologyCatalogue["charterScopeChecks"][number];
export type GoodOutcomeCriterion = MethodologyCatalogue["goodOutcomeCriteria"][number];
export type DiagnosticItem = z.infer<typeof diagnosticItem>;
export type DiagnosticFinding = z.infer<typeof diagnosticFinding>;
export type WorkstreamOutput = z.infer<typeof workstreamOutput>;
export type Baseline = z.infer<typeof baseline>;
export type ValuePool = z.infer<typeof valuePool>;
export type KpiDefinition = z.infer<typeof kpiDefinition>;
export type OutcomeKpi = z.infer<typeof outcomeKpi>;
export type Charter = z.infer<typeof charter>;
export type CharterVersion = z.infer<typeof charterVersion>;
export type CharterView = z.infer<typeof charterView>;
export type NorthStar = z.infer<typeof northStar>;
export type Outcome = z.infer<typeof outcome>;
export type StrategicGuardrail = z.infer<typeof strategicGuardrail>;
export type TomGap = z.infer<typeof tomGap>;
export type CapabilityHeatmapEntry = z.infer<typeof capabilityHeatmapEntry>;
export type Journey = z.infer<typeof journey>;
export type JourneyPainPoint = z.infer<typeof journeyPainPoint>;
export type TomCanvasCellView = z.infer<typeof tomCanvasCellView>;
export type TomWorkshop = z.infer<typeof tomWorkshop>;
export type TomWorkshopItem = z.infer<typeof tomWorkshopItem>;
export type Dependency = z.infer<typeof dependency>;
export type ActionItem = z.infer<typeof actionItem>;
export type Decision = z.infer<typeof decision>;
export type DecisionOption = z.infer<typeof decisionOption>;
export type GateView = z.infer<typeof gateView>;
export type GateCriterionEvaluation = z.infer<typeof gateCriterionEvaluation>;
export type GateSubmission = z.infer<typeof gateSubmission>;
export type GateSubmissionView = z.infer<typeof gateSubmissionView>;
export type GateDecision = z.infer<typeof gateDecision>;
export type Evidence = z.infer<typeof evidence>;
export type EvidenceLink = z.infer<typeof evidenceLink>;
export type TeamAssignment = z.infer<typeof teamAssignment>;
export type RoleAccountability = z.infer<typeof roleAccountability>;

// ------------------------------------------------------------------------------------------------ P3 (DG3)
// Response types of the P3 `portfolio` tag (T-DG3-BE-A; ADR-0021, ADR-0023), from the shared zod mirrors
// (@mth/shared/schemas portfolio.ts). Amounts are exact decimal strings; Unknown is null, never 0 (ADR-0019).
// FE-B and FE-C do not edit this file (p3-work-split §4): they import any further P3 type from @mth/shared/schemas.
export type {
  AcceptanceDecision,
  Deliverable,
  DiagnosticArea,
  DiagnosticAreaCoverage,
  FundingDecision,
  FundingState,
  GateDispensation,
  GateReadiness,
  Initiative,
  InitiativeDecisionLink,
  InitiativeGapLink,
  InitiativeOutcomeContribution,
  InitiativeStatus,
  Milestone,
  OutcomeHierarchy,
  PortfolioSelection,
  ScheduleFlag,
  TransformationReadiness,
} from "@mth/shared/schemas";
/** G1 leadership agreement confirmations (ADR-0021 §8) as sent, and as recorded on the gate decision. */
export type { GateAgreements, GateAgreementRecord } from "@mth/shared/schemas";

/** A list answer that may carry a warning (e.g. the 3-7 deliverables warning of GET …/deliverables). */
export type DeliverableList = z.infer<typeof deliverableList>;
/** A page of the P3 paged lists (cursor pagination as everywhere else). */
export type InitiativeListPage = z.infer<typeof initiativePage>;
export type PortfolioSelectionPage = z.infer<typeof portfolioSelectionPage>;
export type FundingDecisionPage = z.infer<typeof fundingDecisionPage>;
export type GateDispensationPage = z.infer<typeof gateDispensationPage>;

/**
 * T07 wave as returned by GET /transformations/{id}/waves (`RoadmapWave` in docs/api/openapi.yaml). No zod mirror exists
 * in @mth/shared/schemas at this base, so the fields the portfolio screens read are typed here (T-DG3-FE-A).
 */
export interface RoadmapWave {
  readonly id: string;
  readonly transformationId: string;
  readonly code: string;
  readonly ordinal: number;
  readonly isSourceSeeded: boolean;
  readonly nameEn: string;
  readonly nameAr: string;
  readonly horizonEn: string;
  readonly horizonAr: string;
  readonly plannedStart: string | null;
  readonly plannedEnd: string | null;
  readonly status: "active" | "archived";
  readonly version: number;
}
