// T04 Design Decision Log (REQ-PB-043): the canonical decision register read with GET /decisions?kind=design. Codes
// D-01, D-02… are generated by the server; options are A/B/C…; a new decision is Open. Deciding is a business decision
// by the decision owner (decision.decide) and is never automatic; gate decisions are read-only here.
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { decisionCreate, decisionOptionCreate, decisionUpdate } from "@mth/shared/schemas";
import { useDecisions, useP2Refresh } from "../../api/queries.ts";
import type { Decision } from "../../api/types.ts";
import { useLocale } from "../../app/locale.ts";
import { Unknown } from "../../components/Badges.tsx";
import { Icon } from "../../components/Icon.tsx";
import { RecordStatus } from "../../components/P2Badges.tsx";
import { PersonName, usePeople } from "../../components/People.tsx";
import { RecordDialog, type FieldSpec } from "../../components/RecordForm.tsx";
import { RegisterTable, type RegisterColumn } from "../../components/RegisterTable.tsx";
import { NoteDecisionDialog } from "../../components/RowActions.tsx";
import { Section, TextCell } from "../../components/Section.tsx";
import { QueryState } from "../../components/States.tsx";
import { useWorkspace, WorkspaceFrame } from "../../components/Workspace.tsx";
import { formatBusinessDate, formatDateTime } from "../../lib/format.ts";
import { tomDimensionLabel, tomDimensionOptions } from "../../lib/methodology.ts";

export function DecisionsPage() {
  const { t } = useTranslation();
  return (
    <WorkspaceFrame
      tab="decisions"
      title={t("decisions.title")}
      subtitle={t("decisions.intro")}
      writePermissions={["decision.edit", "decision.decide"]}
    >
      <DecisionLog />
      <GateDecisionLog />
    </WorkspaceFrame>
  );
}

function DecisionLog() {
  const { t } = useTranslation();
  const locale = useLocale();
  const ws = useWorkspace();
  const decisions = useDecisions(ws.tid, "design");
  const { people, byId } = usePeople(ws.tid);
  const refresh = useP2Refresh(ws.tid);
  const [dialog, setDialog] = useState<{ record: Decision | null } | null>(null);
  const [addingOption, setAddingOption] = useState<Decision | null>(null);
  const [deciding, setDeciding] = useState<Decision | null>(null);
  const canEdit = ws.can("decision.edit");
  const canDecide = ws.can("decision.decide");

  const createFields: FieldSpec[] = [
    { name: "title", kind: "text", label: t("decisions.field.title"), required: true, maxLength: 500 },
    { name: "context", kind: "textarea", label: t("decisions.field.context"), rows: 4 },
    {
      name: "tomDimensionCode",
      kind: "select",
      label: t("design.dimension"),
      options: tomDimensionOptions(ws.methodology, locale),
    },
    { name: "ownerUserId", kind: "person", label: t("decisions.field.owner"), hint: t("decisions.field.ownerHint") },
    { name: "dueDate", kind: "date", label: t("decisions.field.dueDate") },
    {
      name: "optionA",
      kind: "text",
      label: t("decisions.option.labelN", { label: "A" }),
      maxLength: 300,
      createOnly: true,
    },
    {
      name: "optionB",
      kind: "text",
      label: t("decisions.option.labelN", { label: "B" }),
      maxLength: 300,
      createOnly: true,
    },
    {
      name: "optionC",
      kind: "text",
      label: t("decisions.option.labelN", { label: "C" }),
      maxLength: 300,
      createOnly: true,
    },
    { name: "recommendationText", kind: "textarea", label: t("decisions.field.recommendation") },
  ];
  const editFields = (d: Decision): FieldSpec[] => [
    ...createFields.filter((f) => !f.createOnly),
    {
      name: "recommendationOptionId",
      kind: "select",
      label: t("decisions.field.recommendedOption"),
      options: d.options
        .filter((o) => o.status === "active")
        .map((o) => ({ value: o.id, label: `${o.label}. ${o.title}` })),
    },
    {
      name: "status",
      kind: "select",
      label: t("common.field.status"),
      hint: t("decisions.field.statusHint"),
      options: (["open", "deferred", "cancelled"] as const).map((s) => ({
        value: s,
        label: t(`common.recordStatus.${s}`),
      })),
    },
  ];

  const columns: RegisterColumn<Decision>[] = [
    {
      id: "code",
      header: t("decisions.field.code"),
      cell: (d) => (
        <bdi dir="ltr" className="code" id={d.code}>
          {d.code}
        </bdi>
      ),
      sortValue: (d) => d.code,
      hideable: false,
      rowHeader: true,
    },
    {
      id: "title",
      header: t("decisions.field.title"),
      cell: (d) => <span className="text-cell">{d.title}</span>,
      sortValue: (d) => d.title,
    },
    {
      id: "dimension",
      header: t("design.dimension"),
      cell: (d) =>
        tomDimensionLabel(ws.methodology, d.tomDimensionCode, locale) ?? (
          <span className="muted">{t("common.value.none")}</span>
        ),
      sortValue: (d) => tomDimensionLabel(ws.methodology, d.tomDimensionCode, locale),
    },
    {
      id: "options",
      header: t("decisions.option.title"),
      cell: (d) =>
        d.options.length === 0 ? (
          <span className="muted">{t("decisions.option.none")}</span>
        ) : (
          <ol className="plain-list options-list">
            {[...d.options]
              .sort((a, b) => a.ordinal - b.ordinal)
              .map((o) => (
                <li key={o.id} data-option={o.label} className={o.status === "withdrawn" ? "muted" : undefined}>
                  <strong>
                    <bdi dir="ltr">{o.label}</bdi>.
                  </strong>{" "}
                  {o.title}
                  {d.recommendationOptionId === o.id ? (
                    <span className="small"> ({t("decisions.option.recommended")})</span>
                  ) : null}
                  {d.chosenOptionId === o.id ? (
                    <span className="status-chip status-chip--on-track small">
                      <Icon name="check" /> {t("decisions.option.chosen")}
                    </span>
                  ) : null}
                  {o.status === "withdrawn" ? (
                    <span className="small"> ({t("common.recordStatus.withdrawn")})</span>
                  ) : null}
                </li>
              ))}
          </ol>
        ),
      filterText: (d) => d.options.map((o) => o.title).join(" "),
    },
    {
      id: "recommendation",
      header: t("decisions.field.recommendation"),
      cell: (d) => <TextCell value={d.recommendationText} />,
    },
    {
      id: "status",
      header: t("common.field.status"),
      cell: (d) => <RecordStatus status={d.status} />,
      sortValue: (d) => d.status,
    },
    { id: "owner", header: t("decisions.field.owner"), cell: (d) => <PersonName id={d.ownerUserId} people={byId} /> },
    {
      id: "due",
      header: t("decisions.field.dueDate"),
      cell: (d) => formatBusinessDate(d.dueDate, locale) ?? <span className="muted">{t("common.value.none")}</span>,
      sortValue: (d) => d.dueDate,
    },
    {
      id: "outcome",
      header: t("decisions.field.outcome"),
      cell: (d) =>
        d.status === "decided" ? (
          <span>
            <TextCell value={d.outcomeText} />
            <span className="block small muted">
              {formatDateTime(d.decidedAt, locale, ws.tr.timezone)} · <PersonName id={d.decidedBy} people={byId} />
            </span>
          </span>
        ) : (
          <span className="muted">{t("decisions.notDecided")}</span>
        ),
    },
    {
      id: "actions",
      header: t("common.field.actions"),
      hideable: false,
      cell: (d) => {
        const open = d.status === "open" || d.status === "deferred";
        const mayDecide =
          canDecide && d.status === "open" && d.ownerUserId === ws.meId && d.options.some((o) => o.status === "active");
        if (!open || (!canEdit && !mayDecide))
          return <span className="muted small">{open ? t("common.readOnly") : t("common.value.none")}</span>;
        return (
          <span className="row-actions">
            {canEdit ? (
              <>
                <button
                  type="button"
                  className="button button--link button--small"
                  onClick={() => setDialog({ record: d })}
                >
                  <Icon name="pencil" /> {t("common.action.edit")}
                  <span className="visually-hidden">: {d.code}</span>
                </button>
                {d.status === "open" ? (
                  <button
                    type="button"
                    className="button button--link button--small"
                    onClick={() => setAddingOption(d)}
                  >
                    <Icon name="plus" /> {t("decisions.option.add")}
                    <span className="visually-hidden">: {d.code}</span>
                  </button>
                ) : null}
              </>
            ) : null}
            {mayDecide ? (
              <button type="button" className="button button--link button--small" onClick={() => setDeciding(d)}>
                <Icon name="check" /> {t("decisions.decide")}
                <span className="visually-hidden">: {d.code}</span>
              </button>
            ) : null}
          </span>
        );
      },
    },
  ];

  return (
    <Section
      id="t04"
      title={t("decisions.log")}
      intro={t("decisions.logIntro")}
      actions={
        canEdit ? (
          <button
            type="button"
            className="button button--primary button--small"
            onClick={() => setDialog({ record: null })}
          >
            <Icon name="plus" /> {t("decisions.add")}
          </button>
        ) : null
      }
    >
      <QueryState query={decisions}>
        {(list) => (
          <RegisterTable
            id="t04"
            caption={t("decisions.log")}
            rows={list}
            columns={columns}
            getRowId={(d) => d.id}
            emptyTitle={t("decisions.empty")}
            emptyBody={t("decisions.emptyBody")}
            defaultSort={{ id: "code", dir: "asc" }}
          />
        )}
      </QueryState>
      {dialog ? (
        <RecordDialog<Decision>
          title={dialog.record ? t("decisions.editTitle", { code: dialog.record.code }) : t("decisions.add")}
          description={dialog.record ? undefined : t("decisions.createNote")}
          fields={dialog.record ? editFields(dialog.record) : createFields}
          record={dialog.record}
          defaults={{ ownerUserId: ws.meId }}
          extra={{ transformationId: ws.tid, kind: "design" }}
          mapCreate={(body) => {
            const { optionA, optionB, optionC, ...rest } = body as Record<string, unknown> & {
              optionA?: string;
              optionB?: string;
              optionC?: string;
            };
            const options = [optionA, optionB, optionC]
              .filter((o): o is string => typeof o === "string" && o.trim() !== "")
              .map((title) => ({ title }));
            return options.length > 0 ? { ...rest, options } : rest;
          }}
          createSchema={decisionCreate}
          updateSchema={decisionUpdate}
          createUrl="/api/v1/decisions"
          updateUrl={(r) => `/api/v1/decisions/${r.id}`}
          people={people}
          submitLabel={dialog.record ? t("common.action.save") : t("common.action.create")}
          onSaved={async () => {
            if (!(await refresh())) return;
            setDialog(null);
          }}
          onCancel={() => setDialog(null)}
        />
      ) : null}
      {addingOption ? (
        <RecordDialog<Decision>
          title={t("decisions.option.addTitle", { code: addingOption.code })}
          fields={[
            { name: "title", kind: "text", label: t("decisions.option.titleField"), required: true, maxLength: 300 },
            { name: "description", kind: "textarea", label: t("common.field.description") },
          ]}
          record={null}
          createSchema={decisionOptionCreate}
          createUrl={`/api/v1/decisions/${addingOption.id}/options`}
          createIfMatch={addingOption.version}
          submitLabel={t("decisions.option.add")}
          onSaved={async () => {
            if (!(await refresh())) return;
            setAddingOption(null);
          }}
          onCancel={() => setAddingOption(null)}
        />
      ) : null}
      {deciding ? (
        <NoteDecisionDialog
          title={t("decisions.decideTitle", { code: deciding.code })}
          description={t("decisions.decideDescription")}
          choiceLabel={t("decisions.chosenOption")}
          choices={deciding.options
            .filter((o) => o.status === "active")
            .map((o) => ({ value: o.id, label: `${o.label}. ${o.title}` }))}
          noteLabel={t("decisions.field.outcome")}
          noteRequired
          confirmLabel={t("decisions.decide")}
          url={`/api/v1/decisions/${deciding.id}/decide`}
          version={deciding.version}
          toBody={({ choice, note }) => ({ chosenOptionId: choice, outcomeText: note })}
          notePointer="/outcomeText"
          onDone={refresh}
          onClose={() => setDeciding(null)}
        />
      ) : null}
    </Section>
  );
}

/** Product gate decisions (kind gate): read-only here; recorded on the Gates screen by the configured approver. */
function GateDecisionLog() {
  const { t } = useTranslation();
  const locale = useLocale();
  const ws = useWorkspace();
  const decisions = useDecisions(ws.tid, "gate");
  const { byId } = usePeople(ws.tid);
  return (
    <Section id="gate-decisions" title={t("decisions.gateLog")} intro={t("decisions.gateLogIntro")}>
      <QueryState query={decisions}>
        {(list) =>
          list.length === 0 ? (
            <p className="muted">{t("decisions.gateLogEmpty")}</p>
          ) : (
            <ul className="plain-list">
              {list.map((d) => (
                <li key={d.id}>
                  <bdi dir="ltr" className="code">
                    {d.code}
                  </bdi>{" "}
                  {d.title} <RecordStatus status={d.status} />{" "}
                  <span className="muted small">
                    {formatDateTime(d.decidedAt, locale, ws.tr.timezone) ?? <Unknown />} ·{" "}
                    <PersonName id={d.decidedBy} people={byId} />
                  </span>
                </li>
              ))}
            </ul>
          )
        }
      </QueryState>
    </Section>
  );
}
