import type { Readable } from 'node:stream';

/**
 * Object storage adapter (ADR-0010). Keys are generated by the server from UUIDs only — never from filenames or other
 * user input — and objects are never publicly linked: downloads stream through the authorised API endpoint.
 */
export interface ObjectStorage {
  readonly driver: 'local' | 's3';
  /** Honest status for health/admin screens: a `not_configured` adapter never claims to work. */
  readonly status: 'configured' | 'not_configured';
  put(key: string, data: Buffer): Promise<void>;
  get(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

export const OBJECT_STORAGE = Symbol('OBJECT_STORAGE');

const UUID = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';
/** `<area>/<projectUuid>/<objectUuid>` — the only key shape the adapters accept (defence against traversal). */
export const STORAGE_KEY_PATTERN = new RegExp(`^(documents|quarantine)/${UUID}/${UUID}$`);

export function storageKey(area: 'documents' | 'quarantine', projectId: string, objectId: string): string {
  const key = `${area}/${projectId.toLowerCase()}/${objectId.toLowerCase()}`;
  assertStorageKey(key);
  return key;
}

export function assertStorageKey(key: string): void {
  if (!STORAGE_KEY_PATTERN.test(key)) throw new Error('Invalid storage key (keys are server-generated UUID paths only)');
}
